### ISSUE TITLE
MysteryBoxes issue regarding on InventoryMove check.

### ISSUE THREAD

**Issue by JuliCarles** [Photon-GitHub/AACAdditionPro#1]
AACAddition Inventory Move check prevents my players opening the MysteryBox on my lobby. The thing is that, they are not moving, they must just right-click the enderchest and the plugin opens a menu for you to select which box you want to open.
When disabling InventoryMove check the chest can be open normally. (It actually does not open, the "oppening" animation does not show, it just open a menu)

Here's the plugin: https://www.spigotmc.org/resources/20-x-mas-sale-%E2%98%85-mysteryboxes-%E2%87%92-best-rewards-plugin-%E2%87%92-new-crafting-mode.12330/

Using latest 1.10 version of AACAddition on a 1.10.2 server.

**Comment by Photon-GitHub** [comment]
Not a real problem, could not be reproduced.
