### ISSUE TITLE
Feature: Detecting More Inventory (XCarry, Inventory+)

### ISSUE THREAD

**Issue by Minemaniak** [Photon-GitHub/AACAdditionPro#102]
Some clients have abbility to let you hold items in crafting slots in your inventory, so you get 4 slots more than normal player. Would it be possible to add check for it? Example clients: Conceit (XCarry), Exeter (XCarry), Wolfram (MoreInventory)

**Comment by Photon-GitHub** [comment]
Already detected by the classic inventory cheats.

**Comment by Minemaniak** [comment]
Last time I tried, it wasn't detected, has anything changed recently?
