### ISSUE TITLE
AACAdditionPro Freecam false positive with FurnitureLib

### ISSUE THREAD

**Issue by Fonzee9** [Photon-GitHub/AACAdditionPro#103]
You need FurnitureLib and DiceFurniture 

Bug: Sit down on a couch given with /Furniture Give Sofa and once you sit down it detects speed but i disabled speed and it really detects Freecam after disabling Freecam and reenabling Speed i found out it was the freecam check messing it up..

Link to furniturelib and dicefurniture: https://www.spigotmc.org/resources/furniturelibary-protectionlib.9368/ https://www.spigotmc.org/resources/dicefurniture-plugin-m%C3%B6bel-plugin.6006/

**Comment by Photon-GitHub** [comment]
I already account for sitting in vehicles, thus your problem shouldn't occur. Can you please show me a video? Moreover I wonder how my plugin should "detect" freecam - there is no detection. Apart from that freecam does disable when it is disabled in the config. Please restart your server to prevent these bugs.

**Comment by Fonzee9** [comment]
This is a problem...

**Comment by Photon-GitHub** [comment]
Please give me the usual information that must be provided:
Serverversion, version of the important plugins as well as a video...

**Comment by Fonzee9** [comment]
This server is running CraftBukkit version git-Spigot-99c2a37-9a82fa7 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
INFO You are running the latest version

Plugins FurnitureLib DiceFurniture latest version, https://www.spigotmc.org/resources/furniturelibary-protectionlib.9368/ and https://www.spigotmc.org/resources/dicefurniture-plugin-m%C3%B6bel-plugin.6006/

Video of freecam giving false positives when sitting on furniture (This problem goes away after disabling freecam check so i know it is freecam check) https://www.youtube.com/watch?v=45fKLmrfRCY&feature=youtu.be

**Comment by Photon-GitHub** [comment]
Please recheck with latest AACAdditionPro and other plugins as well as the latest server and I will reopen.
