### ISSUE TITLE
Idea to improve the MultiInteract detection

### ISSUE THREAD

**Issue by Nvaros** [Photon-GitHub/AACAdditionPro#104]
First I have to say that this IS bypassable, but it will detect most outdated client.

If you open a chest, the mouse is always a bit below its lowest slot row meaning that legits need a certain time to pick items from the upper ones near the "corners" (especially for a double chest).

Literally all cheststealers go from the first slot to the last one. Mostly the delay is so low that the item(s) of the upper slots near the "corners" are picked up faster than a legit could do -> Detection.

I know that you could bypass that like the old autoarmor check by waiting a bit before picking items or just go from the last slot to the first one, but something is better than nothing.

**Comment by Photon-GitHub** [comment]
This will likely not be implemented in MultiInteract as of the very easy bypass, and the few flags it would generate (1-2 detections after the first click -> cancel threshold not reached).
This will make up the first neural network of the InventoryHeuristics though (distance - time), so stay tuned.

**Comment by Photon-GitHub** [comment]
Addressed in 3.5.0
