### ISSUE TITLE
Pingspoof detects for connection issues

### ISSUE THREAD

**Issue by CeIebrimbor** [Photon-GitHub/AACAdditionPro#105]
Players, when logging in and having a temporary unstable connection (1 bar in tab), then jumping from a hub to a lobby are kicked for pingspoof after a long delay.

https://www.youtube.com/watch?v=Tx2cTUZXj0k&feature=youtu.be

- 1.8.8
- AAC 3.2.1-b1
- AACaddition 2.0.3
- ProtocolLib 4.2.0
- Bungee
- My Config

Logs will be provided.

**Comment by Zaino60** [comment]
AAC+ Log: https://pastebin.com/ckp2wHaC (User kicked: MineJam)

**Comment by Photon-GitHub** [comment]
You technically cannot achieve a ping of 53000 as you get disconnected from the server internally at a ping of 30000. Thus either that person used pingspoofer or AAC's ping calculation is far off reality.

**Comment by Janmm14** [comment]
AAC's ping calculation is basically minecraft's internal ping calculation.

**Comment by Photon-GitHub** [comment]
Fixed in 3.0.1
