### ISSUE TITLE
Feature: Moving with inventory open check

### ISSUE THREAD

**Issue by MatheweB** [Photon-GitHub/AACAdditionPro#107]
Some hacked clients let you move while your inventory is open, giving you an unfair PvP advantage. A feature to check for this would be great! (Wurst client has a feature like this I believe)

**Comment by CeIebrimbor** [comment]
InventoryMove is a check in AACaddition. Unless you disabled it. Also, that check with disable if TPS is below 19.5, so if you have a lagged server, clients can bypass that check specifically.

If you need to report a bypass, please record a client bypassing default AAC 3.0.x and this will be reopened.
