### ISSUE TITLE
Entity not working

### ISSUE THREAD

**Issue by thedarthonian** [Photon-GitHub/AACAdditionPro#108]
I get this error, which I presume is also why an entity never shows up in combat

https://pastebin.com/p8K2Kn34

**Comment by thedarthonian** [comment]
Just got this one as well

https://pastebin.com/4RehizR7

**Comment by thedarthonian** [comment]
https://pastebin.com/4RehizR7

The error always appears when a user joins the server.

**Comment by IvanMankov** [comment]
Relevant.

**Comment by Games4k** [comment]
Working only on 1.8.8

**Comment by Photon-GitHub** [comment]
Should be fixed in 3.2.3
