### ISSUE TITLE
Offline False positives (Players are offline are suspected of AACAdditionPro detections)

### ISSUE THREAD

**Issue by MatheweB** [Photon-GitHub/AACAdditionPro#111]
AACAddition pro consistently detects people of pingspoofer, open inventory walking, and an array of other detections in AACAdditionPro when they are offline (not on the server at all). Since I installed AACAdditionPro, my multicraft panel has also shown a false mount of people online, and shows people online when they are not. These "ghost" people are the ones being suspected by AACAdditionPro.

I'm not sure what's happening, but a fix would be great. Please let me know if you need detailed information (No error logs to show, just standard detection notifications).

I am using the latest AAC, AACAdditionPro (3.0.0), and spigot 1.12. I am also using the latest spigot lib (all of my plugins are the latest release versions).

This error only started to occur when I installed AACAdditionPro, as I have not installed anything after it.

**Comment by Photon-GitHub** [comment]
Seems to be some issue with the KillauraEntities. 
Apart from the detection everything is ok though as the bot should not be bypassable by checking the amount of online players.

**Comment by Photon-GitHub** [comment]
Should be fixed in 3.0.1
