### ISSUE TITLE
Errors in console

### ISSUE THREAD

**Issue by TWSSYesterday** [Photon-GitHub/AACAdditionPro#112]
Getting some funky errors on latest AAC, ProtocolLib and AACAdditionPro: https://hastebin.com/ukixawavoc.vbs

**Comment by Photon-GitHub** [comment]
Only the upper one is caused by my plugin, please report the rest on the AAC issue tracker.

**Comment by Janmm14** [comment]
For now please downgrade your ProtocolLib version to 4.3.0 (or 4.2.0 if using 1.8, 1.9 or 1.10 server) for maximum stability.
I can imagine those errors will be fixed once 4.4.0 is not a dev version.

**Comment by Photon-GitHub** [comment]
I cannot reproduce them, if there is no reply I will close, especially as of the reasons that Jan has already pointed out.

**Comment by TWSSYesterday** [comment]
My apologies, downgrading has fixed this. Will re open if updates don't resolve it.
