### ISSUE TITLE
ESP prevention triggers through barrier blocks

### ISSUE THREAD

**Issue by Skuhoo** [Photon-GitHub/AACAdditionPro#113]
Pretty self-explanatory. Players behind barrier blocks have their equipment hidden when they're completely visible to onlookers. Disabling the ESP prevention corrects this issue, but that's obviously not an ideal solution. I assume all that's needed to be done is to have barrier blocks added to the same transparent block list that lets players see equipment through glass blocks.

**Comment by Photon-GitHub** [comment]
Will be fixed in 3.0.1, but is originally a bug in Spigot itself.

**Comment by Photon-GitHub** [comment]
Fixed in 3.0.1
