### ISSUE TITLE
InventoryRotation False Kick

### ISSUE THREAD

**Issue by xGodly** [Photon-GitHub/AACAdditionPro#114]
Everytime I go from spawn (world) to the askyblock world and move around I get kicked for InventoryRotation.

**Comment by Photon-GitHub** [comment]
Your issue lacks lots of information, including your server version, pluign versions (AAC, AACAdditionPro, ProtocolLib), server and plugin logs as well as a video if possible.

**Comment by xGodly** [comment]
Server Ver: 1.11.2

AAC/AACA: Newest

ProtocolLib: Newest

ProtocolSupport: Newest

**Comment by Photon-GitHub** [comment]
Latest is not always good and stable regarding ProtocolLib, apart from that, depending on the website you downloaded "latest" can differ a lot, please just paste the version in there.
Moreover you are still lacking the other info.

**Comment by Photon-GitHub** [comment]
I will close this as the required info has not been provided.

**Comment by CeIebrimbor** [comment]
@xGodly 
This is because the author of askyblock does not close player inventories in an appropriate fashion. There is nothing Photon can do to assume a player is not blatantly hacking when askyblock forces them to "hack".

This needs to be a code cleanup on askyblock's side.
