### ISSUE TITLE
Spamming fishing rods causes server to hang

### ISSUE THREAD

**Issue by spathizilla** [Photon-GitHub/AACAdditionPro#116]
Server: 1.12 (git-Spigot-596221b-b1b9ab0 (MC: 1.12))
ProtocolLib version: v4.3.1-SNAPSHOT-b378
AAC version: 3.2.2
AACAP version:  v3.0.2-b2

After running AACAP 3.0.2-b2 and using the new default config for both AAC and AP, if you right click spam a fishing rod to grab a chicken (works with players too.. spamming the rod only does not seem to cause the problem - checking this more), after a few attempts the server will completely hang. Reproduced twice so far and can demonstrate.

Crash log: https://pastebin.com/vM7u8GwZ

**Comment by spathizilla** [comment]
Checked with AACAP v3.0.0 (regenerated to old default config) and the issue does not occur.

**Comment by spathizilla** [comment]
Checked with AACAP v3.0.1 (allowed config to regenerate) and issue does NOT occur.

**Comment by Photon-GitHub** [comment]
Fixed in 3.0.2-b3
