### ISSUE TITLE
InventoryRotation

### ISSUE THREAD

**Issue by Terrifical** [Photon-GitHub/AACAdditionPro#117]
When a player goes to the ASkyblock world they get kicked for "InventoryRotation". I use the optimized config but the false kick also happens with the default.

### Core information ###
**Server version**: 1.11.2

**AAC version**:  3.2.2-b1

**AACAdditionPro version**:  3.0.2-b2

**ProtocolLib version**:  4.3.0

**Plugin list**:  http://prntscr.com/g3jsvv

### Special environment information ###
**ViaVersion version**:   N/A

**ProtocolSupport version**:  4.26

**ViaBackwards version**:   N/A

**BungeeCord plugins**:   N/A

**Comment by Photon-GitHub** [comment]
Video please.

**Comment by Terrifical** [comment]
Video: https://www.youtube.com/watch?v=2gVBd01kdlo&feature=youtu.be

Server Logs: https://hastebin.com/agivuzemur.md

AACAddition Logs: https://hastebin.com/obixuzibap.rb

**Comment by CeIebrimbor** [comment]
@Photon-GitHub 
I have had at least 10 separate(as many at 15) people bring this up specifically relating to the start of an ASkyBlock game. Why I've been telling people to turn it off on a case by case basis.

**Comment by Terrifical** [comment]
Just noticed something, you only get s false kick if you go to your island through the island panel. What I showed in the video. 

Panel being the gui that showed up before I went to my island.

**Comment by CeIebrimbor** [comment]
Try any teleport or world change, then stand AFK after the teleport. Also, try logging in and not moving from login location. From what I've heard in the past, basically anyone who is AFK can be affected by this, so it is likely more common than just teleporting to an island panel.

**Comment by Photon-GitHub** [comment]
My plugin closes the inventory of a player internally after both a teleport and a playerchangedworldsevent.

**Comment by Photon-GitHub** [comment]
You could maybe ask the dev to properly close the inventory before teleporting.

**Comment by tastybento** [comment]
@Photon-GitHub 
I had a look through my code and as far as I can tell I can closing the inventory before performing the command. Please see https://github.com/tastybento/askyblock/blob/master/src/com/wasteofplastic/askyblock/panels/ControlPanel.java#L415

Do you need to have me wait a tick before the command is performed?

**Comment by Terrifical** [comment]
tastybento (dev of askyblock) replied above ^^^^^

**Comment by Photon-GitHub** [comment]
I listen for InvClose on Monitor, PlayerTp on Monitor and WorldChange...  technically it should close the inventory internally.

**Comment by tastybento** [comment]
@Photon-GitHub Sorry, I don't understand. Are you saying that it should work, but it doesn't? Is there anything I can do to help? If not, then what can @Terrifical do? Anything? Thanks.

**Comment by Janmm14** [comment]
Yes, he says it should work but it doesn't.
