### ISSUE TITLE
Config-Section is null when loading: AutoFish.thresholds

### ISSUE THREAD

**Issue by DrunkBassHD** [Photon-GitHub/AACAdditionPro#121]
Hello,

I have just fully updated all plugins for my HUB and I have this error with your plugin.
https://pastebin.com/9bqhn1Ec

Server Version: 1.10.2-R0.1

ProtocolLib Version: 4.3.0

AAC Version:  3.2.2-b1

AACAdditionPro Version: 3.0.2-b4

Error: https://pastebin.com/9bqhn1Ec 

Hope you can help!

Thanks,

**Comment by CeIebrimbor** [comment]
Please show config.yml for AACaddition.

**Comment by DrunkBassHD** [comment]
I would, But it will not generator anything in config.yml

**Comment by CeIebrimbor** [comment]
What is the full startup log? It sounds like AACaddition is just not starting. So it's missing a requirement or it's in an unsupported environment.

**Comment by DrunkBassHD** [comment]
Sorry I took so long but here you go https://pastebin.com/6a7sKkyE

**Comment by Photon-GitHub** [comment]
Can you delete the whole folder of my plugin and restart the server please?

**Comment by DrunkBassHD** [comment]
Okay, I've done that now what?
