### ISSUE TITLE
Scoreboard team bug (Killaura Entity)

### ISSUE THREAD

**Issue by Hyronymos** [Photon-GitHub/AACAdditionPro#122]
I hope this screenshot should describe this issues: http://prntscr.com/g64sby

Some more information: https://hastebin.com/vibeqobaza.bash

AACAdditionpro Version: latest

**Comment by Hyronymos** [comment]
Server-Log: https://pastebin.com/ACtGuY5g
AACAdditionPro-Log: https://pastebin.com/U4jB42ih
Gif: http://imgur.com/a/A4rP2

**Comment by Photon-GitHub** [comment]
Should be fixed in 3.2.0-b1
