### ISSUE TITLE
Water push = Inventory Move

### ISSUE THREAD

**Issue by Countinq** [Photon-GitHub/AACAdditionPro#123]
When I was moving in water. The anticheat noticed that I was moving and had my inventory open. And actively moving things around. 

AAC: 3.3.0-b1
AACaddition: 3.1.0-b1
Server: 1.8.8
ProtocolLib: 4.2.0

Testing when a player is in their inventory. And another player is hitting that person. I got a little rubber band back. However, I do want to state that I did have that same experience and it did get the player banned. So I am not sure what's happening there. - I did not record both times :/

http://imgur.com/qOcckB2
https://youtu.be/peapapwxX_c

Using Cels configs

**Comment by Photon-GitHub** [comment]
The video was deleted. Please make sure you do not remove videos you post here.

**Comment by CeIebrimbor** [comment]
@photon-github It's basically the same video, but with a kick at the end.

**Comment by CeIebrimbor** [comment]
Update to 3.2.0 (report any new findings if relevant)
