### ISSUE TITLE
KillAuraEntity Issues

### ISSUE THREAD

**Issue by ItzSomebody** [Photon-GitHub/AACAdditionPro#124]
**Server Version: Spigot** 1.8.8
**ProtocolLib Version:** 4.2.1
**AACAdditionPro Version:** 3.2.0-b1

**Issue Number 1:** We are having an issue with the KillAuraEntity that other people might also be having problems with. We have a sky-island spawn and the KillAuraEntity spawns under the island and falls into the void for an eternity not teleporting behind the player as expected. When the player teleports to another location that also happens to be in the sky (one of our pvp arenas for example), the entity teleports under the arena and again falls into the void for an eternity never teleporting back up to behind the player.

**Issue Number 2:** KillAuraEntity is not teleporting back to player on death event.

**Comment by Photon-GitHub** [comment]
Issue number 1 will not be fixed anytime soon, that is just the problem of gravity.
Second one should come in the next release.

**Comment by Photon-GitHub** [comment]
First one will probably not be fixed.
Second one is fixed in 3.2.1.
-> close
