### ISSUE TITLE
LogBot console error

### ISSUE THREAD

**Issue by Minemaniak** [Photon-GitHub/AACAdditionPro#126]
Crash stacktrace: https://pastebin.com/yfDzqDGH
Server version: spigot 1.8.8
ProtocolLib: 4.3.0
AACAdditionPro: 3.2.0
AAC version: 3.3.1

Nothing more to say I think, crash appears on server start

**Comment by Photon-GitHub** [comment]
Should not appear anymore in 3.2.2, but I could not reproduce the bug.
