### ISSUE TITLE
InventoryRotation bug

### ISSUE THREAD

**Issue by FrankHeijden** [Photon-GitHub/AACAdditionPro#127]
Multiple players get kicked when falling from a great distance in water, tried replicating but failed with my alt account. The guy which did it got kicked 9/10 times he did it, i got the scenario + a full log. I hope this is enough to fix it, as i wasnt able to reproduce.

Log: https://pastebin.com/5K2XVVVP
Screen: [![Screenshot from Gyazo](https://gyazo.com/542d6fa1a09b5c8a7a65bf1e21a0fc84/raw)](https://gyazo.com/542d6fa1a09b5c8a7a65bf1e21a0fc84)

**Comment by FrankHeijden** [comment]
Edit: got this replicated.

After i warped to someone's island with my alt acc this happened. (ASkyBlock, 3.0.7)
The sign in the GIF is the welcome sign.
[![Screenshot from Gyazo](https://gyazo.com/346a32e435acc961c0f59fd1bee30edb/raw)](https://gyazo.com/346a32e435acc961c0f59fd1bee30edb)

**Comment by Photon-GitHub** [comment]
ASkyblock is known to cause issues I cannot resolve.
See #117
