### ISSUE TITLE
Kick when opening crates

### ISSUE THREAD

**Issue by AmazedMender16** [Photon-GitHub/AACAdditionPro#13]
people open crates with cratekey and then they getting kicked for killaura/autoarmor
also when people run and click around they getting kicked for killaura

Reproduce: jumping and running around and clicking

Opening crate chest withg cratekey and gettiung kicked

I unloaded the plugin because its kicking my players

play.cwoare.nl

**Comment by Photon-GitHub** [comment]
Incompatibility problem with your crate plugin, as it does not close your inventory.

**Comment by AmazedMender16** [comment]
So what i have to do? :p

**Comment by Photon-GitHub** [comment]
What is your crate plugin?

**Comment by AmazedMender16** [comment]
https://www.spigotmc.org/resources/mystery-crate-cratereloaded-for-the-finest-servers.3663/

**Comment by Photon-GitHub** [comment]
That plugin does not have an api, I am sorry but I probably cannot help you with that as the problem is that the plugin does not internally close the inventory. The plugin is also premium and even if it had an api I would have to buy it to code with it.
