### ISSUE TITLE
Control Heuristics Addition trough API

### ISSUE THREAD

**Issue by Minemaniak** [Photon-GitHub/AACAdditionPro#132]
Simple: make HeuristicsAdditionViolationEvent cancellable like PlayerViolationAddition so we can bypass certain players using API. It would be useful, as Heuristics (when using addition) is the only check that you can't bypass trough API.

**Comment by Photon-GitHub** [comment]
Will be added in the next version.
Why would you want to exempt some players from the Heuristics though? 
The check has few false positives and only targets the detection of combat advantages.

**Comment by Minemaniak** [comment]
On our practice mode you can fight with "combo" equipment (you know, very fast hitting, very similiar to this  https://github.com/konsolas/AAC-Issues/issues/897) checks are going crazy and Heuristics Addition is the only one we can't bypass via API.

**Comment by Photon-GitHub** [comment]
Forgot to close this.
The feature was added in 3.2.3.
