### ISSUE TITLE
AACAdditionPro |  HUGE LAG PROBLEM AND ERROR - 1.12.1

### ISSUE THREAD

**Issue by craftrise** [Photon-GitHub/AACAdditionPro#133]
**Spigot version:** 1.12.1 - LATEST BUILD
**AACAdditionPro version:** 3.2.2 - LATEST
**ProcotolLib version:** 4.3.0

Error (spams everytime): **https://hastebin.com/jebexihogu.vbs**

And huge lag log: **https://hastebin.com/ilupuvukuh.md**

If you can solve these mistakes, it will be very good.

**Comment by Photon-GitHub** [comment]
Duplicate of #108
