### ISSUE TITLE
Reload Error

### ISSUE THREAD

**Issue by aquatrooper** [Photon-GitHub/AACAdditionPro#134]
When reloading aac in 1.12.1 console gets this error: https://pastebin.com/2izNU4ZP

Protocollib 4.3.0
AAC 3.2.2-b2
AACAdditionPro 3.2.3

Cel's Config

**Comment by Photon-GitHub** [comment]
Does this still appear on latest spigot, AAC and AACAdditionPro? If yes please post the stacktrace of the new version.

**Comment by aquatrooper** [comment]
It happened once and has not happened since

**Comment by Photon-GitHub** [comment]
In this case I will close the issue. If it ever appears again do not hesitate to reopen.
