### ISSUE TITLE
A command to manually trigger the KillauraEntity check

### ISSUE THREAD

**Issue by Matthew777k** [Photon-GitHub/AACAdditionPro#135]
Having a command that'd allow for the KillAuraEntity check to manually happen onto certain players.

example: bobby12 is suspected of hacking, me as a staff member would then begin recording and type "/aacprocheck bobby12" while he's fighting which would then spawn the killauraentities around the player for solid evidence of him using cheats.

**Comment by Matthew777k** [comment]
^ suggestion by the way

**Comment by CeIebrimbor** [comment]
👍 

Or automatically summon the entity after a certain min_confidence level is reached in Heuristics. 

Example: Spawn KA entities around players for 30 seconds after they obtain a 60 confidence. Then reset/resummon for 30 seconds each time they sustain or retrip 60.

I suppose this can be done with a combo of a summon command and heuristics-addition, but it would be cleaner to have it as a config setting in KillauraEntities.

**Comment by Janmm14** [comment]
This type of entity checking would require some killaura entities to be hidden before - else this would be far too easy to circumvent for cheat clients.

**Comment by Photon-GitHub** [comment]
Will not happen that soon as it would require various new systems and opens the door for bypasses in most gamemodes, thus I labeled it as unimportant.

**Comment by Photon-GitHub** [comment]
Adressed in 3.4.0
