### ISSUE TITLE
KillAura Bots Suggestions

### ISSUE THREAD

**Issue by Games4k** [Photon-GitHub/AACAdditionPro#137]
Hello. I have some good ideas for KillAuraEntity check:
- [x] Make bots invisible when in GameMode Creative or flying (or remove them)
- [x] Make bots dissapear after a long time if player dont hit any of them, or make something like if killaura (normal) vl is 5+ spawn bot, or if min_confidence is 55+ spawn bot for X minutes
- [x] Let bots go through walls (they can be glitched sometimes and can appear directly in front of player, but its not a big issue because when you hit them, they teleport back to their normal position)
- [x] Make bots change their armor sometimes...
- [x] Make bots change their name once in X minutes

**Comment by Photon-GitHub** [comment]
1) ok
2) As I already said, I will do that some time later, that just opens doors for bypasses 
3) No. That is a direct violation of legit playstyle, thus it will not be added.
4) They already do. Are you sure you didn't disable that in the config?
5) Will be hard as of the gameprofiles. You can use the API for that if you need it.

**Comment by Games4k** [comment]
> They already do. Are you sure you didn't disable that in the config?

I didnt, I'll try again later. Thanks for reviewing :)

**Comment by Photon-GitHub** [comment]
1) Is implemented in 3.2.4

**Comment by Photon-GitHub** [comment]
2. is adressed in 3.4.0.

**Comment by Photon-GitHub** [comment]
Close this issue as only request 5 is still open in favor of #147

**Comment by Photon-GitHub** [comment]
5. is addressed in 3.6.3
