### ISSUE TITLE
Clientcontrol - Suggestion

### ISSUE THREAD

**Issue by aquatrooper** [Photon-GitHub/AACAdditionPro#138]
Hello! I have a suggestion for the clientcontrol feature.

Making a specified player exempt from one of the clientcontrols. So the forge part of the config could look like this:

`   Forge:`
`      # Do you want to enable the Forge-Control`
`      # This cannot be blocked; I recommend to kick if desired`
`      enabled: true`
`      exempt_players:`
`         - "aquatrooper"`
`         - "photon"`
`      commands_on_detection:`
`         - "aackick {player} Forge mod is not allowed!"`

And the same with the other mods. It's good if you dont want to give a player the permission to bypass the whole anticheat, just write the players name in the "exempt_players" section and they wont be kicked for forge mod and so on.

Thanks!

**Comment by Photon-GitHub** [comment]
I am probably going to implement a per - check bypass permission system instead of this not really convenient feature.

**Comment by Photon-GitHub** [comment]
A per-check bypass permission system will be added in 4.1.0
