### ISSUE TITLE
Unhandled exception occured in onPacketReceiving(PacketEvent)

### ISSUE THREAD

**Issue by MinecraftiUndCo** [Photon-GitHub/AACAdditionPro#139]
###Issue description

(On LPmitKev.de Mainserver, Photon knows what I mean xD)

java.lang.IllegalStateException: Asynchronous entity world add!

**https://pastebin.com/GcsKjEDe**

###Core information
**Server version**: 1.8.9
**AAC version**: 3.3.2-b2
**AAC AdditionPro version**: 3.2.3
**ProtocolLib version**: V. 4.3.0
**Plugin list**: AAC, AACAdditionPro, ProtocolLib, GeiloCheat & more own game plugins (network api, etc.)

###Special environment information

**ViaVersion version**: none
**ProtocolSupport version**: none
**ViaBackwards version**: none
**BungeeCord plugins**: Our own plugins (should not affect aac in any way)

**Comment by MinecraftiUndCo** [comment]
Very important bug! When this error occurs the player can't see the world anymore and can't do anything. http://puu.sh/xFpHs/3449ddf80e.jpg

**Comment by Photon-GitHub** [comment]
Does this still appear in 3.2.4? If yes please post the stacktrace of the new version.

**Comment by Photon-GitHub** [comment]
Closed due to inactivity.

**Comment by Photon-GitHub** [comment]
Please comment to confirm this is still valid on the most recent version.

**Comment by MinecraftiUndCo** [comment]
Yeah, ist is valid.
