### ISSUE TITLE
Feature | KillAura check command using old AAC's NPC system.

### ISSUE THREAD

**Issue by SnakeDaoust1232** [Photon-GitHub/AACAdditionPro#14]
AAC 3.0 Removed it's NPC check for KillAura although that check single handedly banned 10k cheaters on my network and it is still doing work. I would love it if you could implement a manual KillAura check command like /kacheck {player} that would spawn and an NPC above and behind a player  a configurable amount of blocks that would follow them for a configurable amount of seconds. If the player doesn't hit either NPC it would simply despawn after the configurable amount of seconds. It would use the same violation system that old AAC used and you would be able to set whether the NPC was invisible or not. If you hit the NPC is would start to sporadically move just like the old AAC and the violation level would rise with each hit.

I understand that konsolas removed this because clients started to bypass it. On the other hand, to this day, it is still catching blatant cheaters on my server and I would really like to see it added again. With that being said I want to be clear that I wouldn't want it to be auto, I like the having to manually check for it. 

Like i said before it would resemble if not copy the way old AAC NPC check used to work. Using the same violation level / commands system that old AAC used.

**Comment by Photon-GitHub** [comment]
The problem is that it were not the bypasses that made us drop the npc check. It was the Protocol. I have the same problem as konsolas: I cannot support all the different protocols when implementing the check. If everyone updated to 1.11 (which will not happen unless Mojang reverts the pvp changes) there would be a npc check again.

**Comment by SnakeDaoust1232** [comment]
I'm just brainstorming but from past experience you can code a plugin to detect what version minecract jar you are using. So maybe you could make version specific checks. So if the plugin detects that I'm using a 1.8 jar, it will enable the 1.8 NPC check code, if it detects 1.7, it would enable the 1.7 code, etc. or just explicitly code it for 1.7-1.8 and state that you can only use the check on 1.7-1.8. (The second method wouldn't be fair to other users but I'm just looking for ideas since I really want this added.) I could even pay you seperate to make a private addition just for me. I use paperspigot 1.8

**Comment by Photon-GitHub** [comment]
You can't even imagine what we tried to get this check working. But this was tried for sure. Also, those who failed the ncp check will likely be detected by the heuristics or high vl ka normal.

**Comment by SnakeDaoust1232** [comment]
:( What about a private version? I could pay you.

**Comment by Photon-GitHub** [comment]
No manual check, but KillauraEntities will come.

**Comment by Photon-GitHub** [comment]
Added in 3.0.0
