### ISSUE TITLE
Freecam problem

### ISSUE THREAD

**Issue by TheIronMinerLv** [Photon-GitHub/AACAdditionPro#140]
Hello!

I have newest version of AAC and AACAdditionPro. Actually I bought this plugin just for one reason - I hoped it would block a serious bug - you can place and light up creepers with freecam (using CreeperEggs). But after successfull installation, it still works (some other freecam features like opening chests between walls doesn't work..)

Using Spigot 1.8.8. Thanks.

**Comment by Photon-GitHub** [comment]
This is not really a bug, as Freecam is a clientsided mod, and I also state in my overview that Freecam might not be blocked in all clients. The illegal interactions you refer to should be posted on AAC‘s issue tracker. My plugin rather trys to limit the information a freecam-user can get with the ESP and the Freecam check.

**Comment by Photon-GitHub** [comment]
If anything occurs regarding this that is indeed the job of my plugin feel free to reopen the issue,
