### ISSUE TITLE
CLIENT CRASH

### ISSUE THREAD

**Issue by d4d3boss** [Photon-GitHub/AACAdditionPro#143]
Please include:
- Server version:  1.8
- ProtocolLib version: 4.3.0
- The version of AACAdditionPro: 3.2.3
- A detailed description of the bug / wanted feature: after a while you get thrown out of the server
https://imgur.com/a/VFYem

**Comment by d4d3boss** [comment]
Client 1.8.x to 1.12.x

**Comment by d4d3boss** [comment]
No console error.No console error.
After 3 hours of testing, the plugin crashed the clients
After 3 hours of testing, the plugin crashed the clients

**Comment by CeIebrimbor** [comment]
#141
