### ISSUE TITLE
Plugin doesn't load

### ISSUE THREAD

**Issue by TheIronMinerLv** [Photon-GitHub/AACAdditionPro#144]
- Server version: PaperSpigot 1.8.8
- ProtocolLib version: 3.7-b232
- The version of AACAdditionPro: 3.2.3

Hello, I put the plugin in server, then 2 times restarted it and I guess it can't load after the second time. I haven't changed anything, please fix!

https://pastebin.com/NttfgHv5

**Comment by TheIronMinerLv** [comment]
An update: I had installed the recommended ProtocolLib version from AAC's official page, now I installed the recommended from ProtocolLib jenkins (there was a link to this: http://ci.shadowvolt.com/job/ProtocolLib/373/) and the AACAdditionPro works. What should I do?

**Comment by Photon-GitHub** [comment]
Sorry, AAC's site does in fact state the wrong version of ProtocolLib, konsolas hasn't updated that one for ages. Please use version 4.2.0 as it is the most stable right now. The flying entity behind you is in fact my KillauraEntity check, it can be disabled in the config.
