### ISSUE TITLE
Tower false kick

### ISSUE THREAD

**Issue by FrankHeijden** [Photon-GitHub/AACAdditionPro#145]
- Server version: CraftBukkit version git-Spigot-93e20b3-9ab758c (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
- ProtocolLib version: v4.4.0-SNAPSHOT-b389
- The version of AACAdditionPro: 3.2.4
- A detailed description of the bug / wanted feature: 

kick + detections: https://pastebin.com/E531Avsn
beacon effects: Jump Boost I, Jump Boost II gives also some detections, but less
steps to replicate: Place a beacon with Jump Boost I enabled and try to build upwards.

**Comment by Photon-GitHub** [comment]
Can you please include a video as I could not really replicate it?

**Comment by FrankHeijden** [comment]
Very weird bugg, i updated AAC to 3.3.4 and it seemed to be fixed.

**Comment by Photon-GitHub** [comment]
It was indeed an error of my plugin, now fixed in 3.3.0
