### ISSUE TITLE
Idea - Toggle NPC in tablist

### ISSUE THREAD

**Issue by thedarthonian** [Photon-GitHub/AACAdditionPro#146]
Please include:
- Server version: 1.8.8
- ProtocolLib version: 4.2.1
- The version of AACAdditionPro: 3.3.0
- A detailed description of the bug / wanted feature: On the tablist, the NPC is shown. Although I can see this being handy, having a formatted tablist it not only mimicks offline players being online, if it does mimick and online player, it will remove the formatting completly. For those people that don't mind this, make the default option true, but for those that don't, let us toggle it.

**Comment by aquatrooper** [comment]
I'd like such a feature, +

**Comment by Portanna** [comment]
I'd like this too, also because it conflicts with other tablist plugins (NameTagEdit)

**Comment by Photon-GitHub** [comment]
Addressed in 3.5.0
