### ISSUE TITLE
Idea - Change NPC every so often

### ISSUE THREAD

**Issue by thedarthonian** [Photon-GitHub/AACAdditionPro#147]
Please include:
- Server version: 1.8.8
- ProtocolLib version: 4.2.1
- The version of AACAdditionPro: 3.3.0
- A detailed description of the bug / wanted feature: Every x seconds (can set in config), it changes the player of the KA entitiy. One bypass I have found for the entity check is, as long as it is mimicking an offline player, to add them as a friend, and the client ignores the entity. By switching it every x seconds, if it switches mid-combat, it will either force the hacker to toggle or get banned.

**Comment by Photon-GitHub** [comment]
Changing in mid-fight is problematic as of ticks-existed bypasses.
The rest can be done via the API, thus I will mark this as unimportant.

**Comment by Photon-GitHub** [comment]
Addressed in 3.6.3
