### ISSUE TITLE
[Feature Request] Remove players from tablist

### ISSUE THREAD

**Issue by ItzSomebody** [Photon-GitHub/AACAdditionPro#149]
Some killauras check the tablist first before attacking another player. Could you make a command that allows us to remove a player from the tablist of a certain player for a certain amount of time?

For example:
```/aacadditionpro tabremove <player> <possiblehacker> <milliseconds to remove from tablist>```

**Comment by jiangdashao** [comment]
This is HackClient's AntiBot feature,but we can use this to make killaura not work,let hack Client all,players are bot,xd

**Comment by Photon-GitHub** [comment]
Addressed in 3.5.0
