### ISSUE TITLE
Inventory Rotation not working anymore?

### ISSUE THREAD

**Issue by SnakeDaoust1232** [Photon-GitHub/AACAdditionPro#15]
Version: Newest Version (0.6.1)
Config: https://hastebin.com/qujecirafe.bash
Video: https://www.youtube.com/watch?v=YgkYOt46HQ0&feature=youtu.be

**Comment by Photon-GitHub** [comment]
Will be fixed in 0.7 as soon as aac 3.0.2 is out.
