### ISSUE TITLE
Disconnected Error

### ISSUE THREAD

**Issue by mcPr0xy** [Photon-GitHub/AACAdditionPro#152]
Please include:
- Server version: 1.12.2
- ProtocolLib version: latest (dev-builds)
- The version of AACAdditionPro: Latest 3.4.0
- A detailed description of the bug / wanted feature: When the plugin is installed I can't connect to the server. I get a "Disconnected" message when trying to join.

`29.10 01:56:11 [Server] ERROR java.lang.NullPointerException
29.10 01:56:11 [Disconnect] User test4321 has disconnected, reason: Internal Exception: io.netty.handler.codec.EncoderException: io.netty.handler.codec.DecoderException: Unable to decode datawatcher object`

edit: It happens when this option is enabled in config under killauraentity.
on_command: true

- If possible a short video of the bug:

**Comment by Photon-GitHub** [comment]
Please provide the full stacktrace, that is probably a shortened error.

**Comment by jiongjionger** [comment]
Server version: 1.10.2
ProtocolLib version: 4.2.0
The version of AACAdditionPro: Latest 3.4.0
same issues with no stackrace and on_command: true.

lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.RuntimeException: An internal error occured.

**Comment by jiongjionger** [comment]
client log might help
https://hastebin.com/olugozalay.vbs
client-version: 1.10.2

**Comment by Photon-GitHub** [comment]
Addressed in 3.4.1
