### ISSUE TITLE
Pingspoof can easy bypass

### ISSUE THREAD

**Issue by jiongjionger** [Photon-GitHub/AACAdditionPro#154]
Server version: 1.10.2 or 1.8.X
ProtocolLib version: 4.2.0
The version of AACAdditionPro: 3.4.1
Client information: 1.8.9 with LiquidBounceb mod(b26.2 or b27)

I use the default plugin configuration and the default client setting(500ms pingspoof), which I've been cheating for 15 minutes, and still haven't kicked by AACAdditionPro, and I can easily bypass multiInteraction(max_ping: 400 default).

**Comment by Photon-GitHub** [comment]
It depends on whether you already join with Pingspoof, your normal ping and how far off the spoofed ping is.

**Comment by Janmm14** [comment]
+ pingspoof settings

**Comment by jiongjionger** [comment]
Thank you for your reply :)

1. pingspoof settings : 500ms (default)
2. client mod: LiquidBounceb b26.2 or b27(1.8.9)

I tried join the server first with no pingspoof, and then wait for 3 minutes, and enable pingspoof(500ms) and just walk around the spawn for about 10 minutes, nothing happened.

**Comment by jiongjionger** [comment]
@Photon-GitHub 
Would you like me to offer you other information?
