### ISSUE TITLE
Console Errors (default config)

### ISSUE THREAD

**Issue by Shottzyy** [Photon-GitHub/AACAdditionPro#156]
- Server version: 1.8.8 PaperSpigot
- ProtocolLib version: 3.6.5
- The version of AACAdditionPro: 3.4.1
- A detailed description of the bug / wanted feature: getting this error https://hastebin.com/umeqipezej.vbs
- If possible a short video of the bug: n/a

**Comment by Photon-GitHub** [comment]
You have a very old ProtocolLib version. Please update to 4.4.0 and try again.

**Comment by Photon-GitHub** [comment]
Closed in favor of #157
