### ISSUE TITLE
Console error spam

### ISSUE THREAD

**Issue by Hamata6** [Photon-GitHub/AACAdditionPro#157]
- Server version: Spigot 1.11.2 with ViaVersion
- ProtocolLib version: 4.3.0 (the release on spigotmc)
- The version of AACAdditionPro: 3.4.1
- A detailed description of the bug / wanted feature: Instantly spamming the console with the issue illustrated below.
- If possible a short video of the bug: 
![Screenshot](https://image.prntscr.com/image/MfALNb5JTPGEibQaPwt5Dw.png)

This error is spammed over 10 times a second.

**Comment by Hamata6** [comment]
Oops, I just saw the issue below me. I think we have the same issue. Except my versions are more up to date ;)

**Comment by Photon-GitHub** [comment]
I will use this issue as of the more up to date versions.

**Comment by Photon-GitHub** [comment]
Adressed in 3.4.2

**Comment by Hamata6** [comment]
Wow, thanks for the very fast update! :)
