### ISSUE TITLE
AACAdditionPro - generated an exception

### ISSUE THREAD

**Issue by Heliosard** [Photon-GitHub/AACAdditionPro#158]
- Server version: **CraftBukkit version git-TacoSpigot-"c2835dfc" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)**
- ProtocolLib version: **ProtocolLib v4.4.0-SNAPSHOT-b389**
- The version of AACAdditionPro: **3.4.2**

Recurring error when players are on the server: https://hastebin.com/upihedahuq.css

Please fix, thanks!

**Comment by Photon-GitHub** [comment]
Disabling KillauraEntity will temporarily fix the problem.

**Comment by Photon-GitHub** [comment]
Addressed in 3.4.3
