### ISSUE TITLE
Huge lag from 3.4.3

### ISSUE THREAD

**Issue by jiongjionger** [Photon-GitHub/AACAdditionPro#159]
![Timings](https://i.loli.net/2017/11/10/5a059f0f579b1.png)
When I downgrade to 3.4.2, everything is smooth.

**Comment by Photon-GitHub** [comment]
Please provide basic information such as server version (and fork), ProtocolLib version and config. If you don’t want to openly share this please message it me on discord.

**Comment by jiongjionger** [comment]
@Photon-GitHub 
server version: paper 1.10.2
protocolib version: 4.2.0
config: https://gist.github.com/jiongjionger/27cf1853ecbbf7e3612bcd5aebe93e1d

**Comment by Photon-GitHub** [comment]
Does your gamemode utilize teams?

**Comment by PatoTheBest** [comment]
https://timings.aikar.co/?id=280abd24e0294c6bacaf2a1a63d4089c

**Comment by Photon-GitHub** [comment]
Yes, scoreboard teams.

**Comment by jiongjionger** [comment]
Yes, some plugins utilize scoreboard teams.

**Comment by PatoTheBest** [comment]
Oh lord yes, for scoreboards and nametags

**Comment by Photon-GitHub** [comment]
Would you mind setting teams to false in the config and recheck?

**Comment by jiongjionger** [comment]
I didn't enable team function.
https://gist.github.com/jiongjionger/27cf1853ecbbf7e3612bcd5aebe93e1d

**Comment by Photon-GitHub** [comment]
Addressed in 3.4.4. Please reopen if the problem persists.

**Comment by jiongjionger** [comment]
This problem has been greatly alleviated, but performance problems still exist. The new version uses several times more CPU usage than 3.4.2. @Photon-GitHub 

<img src="http://ww2.sinaimg.cn/large/0060lm7Tly1fml9z1tj4nj31gz0iytcn.jpg" />

**Comment by Photon-GitHub** [comment]
Is this still a problem on 3.5.1?

**Comment by Photon-GitHub** [comment]
Seems to be fixed as of inactivity. Please comment to request reopening of the issue.
