### ISSUE TITLE
Auto-fishing check

### ISSUE THREAD

**Issue by Dunterra** [Photon-GitHub/AACAdditionPro#16]
For servers where fishing for loot plays a big role, there are problems with players using autofishing mods. Autofishing mods/cheats/hacks make the user automatically pull in their rod once the client detects the fishing "bobbing".

**Comment by Photon-GitHub** [comment]
Implemented for 1.9.4+ servers.
1.8.8 will not get this feature as of the completely different fishing mechanics.
