### ISSUE TITLE
Scaffold Walk Work

### ISSUE THREAD

**Issue by MatinDark** [Photon-GitHub/AACAdditionPro#161]
Please include:
- Server version: 1.12.1 paper spigot
- ProtocolLib version: 4.3.0
- The version of AACAdditionPro: 3.4.3
- A detailed description of the bug / wanted feature:  Scaffold Work On Server
- If possible a short video of the bug: https://mega.nz/#!A2AnwRLY!PrlL3RFVJSs_xh3OfsJbRE7xCt8RGonMuG-S5DjW-nU

**Comment by Photon-GitHub** [comment]
Addressed in 3.4.4
