### ISSUE TITLE
Scaffold Walk

### ISSUE THREAD

**Issue by craftrise** [Photon-GitHub/AACAdditionPro#162]
Please include:
- Server version: 1.8.8
- ProtocolLib version: 4.2.0
- The version of AACAdditionPro: LATEST 
- A detailed description of the bug / wanted feature: Scaffold bug.
- If possible a short video of the bug: 

I do not hava a log.

Watch after 1:16,

[https://youtu.be/plRQHoJjvps?t=1m16s](https://youtu.be/plRQHoJjvps?t=1m16s)

**Comment by Photon-GitHub** [comment]
Without any log whatsoever this might be a bit hard to fix.

**Comment by Photon-GitHub** [comment]
Addressed in 3.4.4
