### ISSUE TITLE
Arrows in npc KillauraEntity

### ISSUE THREAD

**Issue by MikhailY** [Photon-GitHub/AACAdditionPro#163]
Please include:
- Server version: paperspigot 1.12.2
- ProtocolLib version: http://ci.dmulloy2.net/job/ProtocolLib/390/
- The version of AACAdditionPro: 3.4.4
- A detailed description of the bug / wanted feature:  
If I use KillauraEntity
on paperspigot 1.12.2 + protocolsupport, with the 1.8 version such a thing http://prntscr.com/hiq7f3
it is possible to fix it?

**Comment by Photon-GitHub** [comment]
Addressed in 3.5.0

**Comment by SLeSToR** [comment]
Thank you

**Comment by MikhailY** [comment]
Thank you
