### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by FrankHeijden** [Photon-GitHub/AACAdditionPro#164]
- Server version: Paper version git-Paper-1270 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
- ProtocolLib version: 4.4.0-b390
- The version of AACAdditionPro: 3.4.4
- A detailed description of the bug / wanted feature: error in console
- If possible a short video of the bug: -

https://hastebin.com/ezejixebir.vbs

**Comment by Photon-GitHub** [comment]
I assume you AAC.jar is messed up as my plugin couldn't find AAC's api.
