### ISSUE TITLE
Fishing Error

### ISSUE THREAD

**Issue by CeIebrimbor** [Photon-GitHub/AACAdditionPro#167]
Error: https://hastebin.com/ohanenasil.vbs
Happens pretty regularly in console (not spam though).

**Server version:** 1.12.2 PaperSpigot b1272
**ProtocolLib version:** v4.4.0-SNAPSHOT-b390
**AACAdditionPro:** v3.4.6

Nothing screwing with Fishing, except possibly McMMO. I _think_ it only started happening after updating from Paper 126x to 1272(latest)....not sure though. I think I updated AAC+ and Paper the same day.

**Comment by Photon-GitHub** [comment]
Will be fixed in 3.5.0

**Comment by Photon-GitHub** [comment]
Addressed in 3.5.0
