### ISSUE TITLE
False positives of Scaffold check

### ISSUE THREAD

**Issue by Toshka17** [Photon-GitHub/AACAdditionPro#168]
Please include:
- Server version: Spigot 1.8.8 with latest ViaVersion

- ProtocolLib version: Latest release

- The version of AACAdditionPro: latest (3.4.6)

- A detailed description of the bug / wanted feature: 
When a player builds a bridge from the blocks under him without a Shift, occurs the false positives of Scaffold check

- If possible a short video of the bug: 
https://vk.com/videos220083966?z=video220083966_456239090%2Fpl_220083966_-2

- Config of Scaffold check: https://pastebin.com/v45NsLDt

- Log: https://pastebin.com/wVUW3gMn

**Comment by Photon-GitHub** [comment]
Addressed in 3.5.0
