### ISSUE TITLE
 entitycheck entity fällt nach unten

### ISSUE THREAD

**Issue by Henriks9** [Photon-GitHub/AACAdditionPro#171]
Please include:
- Server version: 1.8.9
- ProtocolLib version: 4.2.0 b341
- The version of AACAdditionPro: 3.4.6
- A detailed description of the bug / wanted feature:  Wenn man den Command /aacadditionpro entitycheck [palyer] 500 ausführen lässt oder ihn selber ausführ sieht man nur wie der entity nach unten ins nichts fällt oder der entity spawnt gar nicht 
- If possible a short video of the bug:

**Comment by Photon-GitHub** [comment]
Please provide a video.

**Comment by Henriks9** [comment]
Bei 0:20 Sieht man den Bot kurz bevor er dann nach unten fällt danach spawnt dort kein bot mehr wahrscheinlich weil er dann auch wieder unten gespawnt wird

https://www.youtube.com/watch?v=ptxpVT5Njy4&feature=youtu.be

**Comment by Photon-GitHub** [comment]
Addressed in 3.6.3
