### ISSUE TITLE
Client-Crash Killaura-Entity-Check

### ISSUE THREAD

**Issue by Officialfk** [Photon-GitHub/AACAdditionPro#172]
- Server version:  This server is running CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

- ProtocolLib version: http://ci.dmulloy2.net/job/ProtocolLib/lastStableBuild/

- The version of AACAdditionPro: 3.5.0 (optimized Config v3.5.0 | 1)

- Client-Version: 1.8.8
- Clientcrash-Message: The game crashed whilst rendering entity in world
  `Error: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Byte` 

-description of the bug:
If the client moves quickly (rotation of the view or sprinting) the client will crash. This only happens if on_command is set to true (KillauraEntity Check)

**Comment by CeIebrimbor** [comment]
This also reportedly happens when a client enters F5 and changes view. So basically any time the client can see its own entity (when on_command: true), the crash occurs.

**Comment by 10axl** [comment]
I have also had this happen when trying to look at the Tablist with the above settings.

**Comment by CeIebrimbor** [comment]
Video: https://youtu.be/7NfVi_is0kc

**Comment by Photon-GitHub** [comment]
Addressed in 3.5.1
