### ISSUE TITLE
AACAdditionPro command \\  /aacadditionpro

### ISSUE THREAD

**Issue by LeaderYT** [Photon-GitHub/AACAdditionPro#173]
Please include:
- Server version: 1.11.2  (viaversion and viabackwards)
- ProtocolLib version: latest
- The version of AACAdditionPro: 3.5.1
- A detailed description of the bug / wanted feature: When you do one of the aacadditionpro commands, it will say exactly /aacadditionpro back. 
- If possible a short video of the bug: 
https://www.youtube.com/watch?v=Sp5d7JE8vfw&feature=youtu.be
[log.txt](https://github.com/Photon-GitHub/AACAdditionPro/files/1628584/log.txt)

**Comment by Photon-GitHub** [comment]
Please provide the server logs.

**Comment by LeaderYT** [comment]
The log is added.

**Comment by Photon-GitHub** [comment]
You messed up your config. Sorry to ask, but did you ever even read your log? It is a very obvious startup error.
