### ISSUE TITLE
generated an exception

### ISSUE THREAD

**Issue by Henriks9** [Photon-GitHub/AACAdditionPro#174]
Please include:
- Server version: 1.8.8
- ProtocolLib version: ProtocolLib v4.4.0-SNAPSHOT-b390
- The version of AACAdditionPro: 3.5.1
- A detailed description of the bug / wanted feature:  Sobald ein Spieler Joint tritt der Fehler auf
- If possible a short video of the bug: 

https://hastebin.com/azalakujip.vbs

**Comment by Photon-GitHub** [comment]
I am pretty sure this is some compatibility issue, can you reproduce the error on a clean setup (AAC + AACAdditionPro + ProtocolLib) ?

**Comment by Photon-GitHub** [comment]
Close because of inactivity.
