### ISSUE TITLE
entitycheck Spawnt unten 

### ISSUE THREAD

**Issue by Henriks9** [Photon-GitHub/AACAdditionPro#175]
Please include:
- Server version: 1.8.8
- ProtocolLib version: 4.2.0 b341
- The version of AACAdditionPro: 3.5.1
- A detailed description of the bug / wanted feature:  Der entity spawnt ganz unten wenn es einen boden gibt Spawnt der entity dort wenn es deinen kompletten Boden gibt fällt der entity nur nach unten
- If possible a short video of the bug: 

https://www.youtube.com/watch?v=uAfpxR-HSTA&feature=youtu.be

**Comment by Photon-GitHub** [comment]
Duplicate of #171 , everything else is on purpose.
