### ISSUE TITLE
Unhandled exception occured in onPacketReceiving(PacketEvent) for AACAdditionPro

### ISSUE THREAD

**Issue by craftrise** [Photon-GitHub/AACAdditionPro#177]
- Server version: 1.8.8 - Spigot
- ProtocolLib version: 4.2.0
- The version of AACAdditionPro: 3.6.0 Latest

Errors:
https://hastebin.com/obetonuyey.lua

**Comment by Photon-GitHub** [comment]
Could you please recheck on the newest version? I am not quite sure whether it has been fixed as I cannot reproduce the error.

**Comment by craftrise** [comment]
@Photon-GitHub , most likely, it was fixed in the new version.
