### ISSUE TITLE
Exception in thread "Craft Scheduler Thread - 131"

### ISSUE THREAD

**Issue by Henriks9** [Photon-GitHub/AACAdditionPro#178]
Please include:
- Server version: 1.8.8
- ProtocolLib version: 4.2
- The version of AACAdditionPro: 3.6.1
- A detailed description of the bug / wanted feature: 
- If possible a short video of the bug: 
https://hastebin.com/uqosusikus.bash

**Comment by Photon-GitHub** [comment]
Try again with the latest version. I am not quite sure whether or not this is some entity-plugin compatibility issue. Do you use plugins with their own entities?

**Comment by Photon-GitHub** [comment]
Close due to inactivity.
