### ISSUE TITLE
Auto-Fishing check is too harsh - Any enchanted rod triggers

### ISSUE THREAD

**Issue by JamieSinn** [Photon-GitHub/AACAdditionPro#179]
- Server version: 1.12.2
- ProtocolLib version: 4.3.0-Dev-#390
- The version of AACAdditionPro: 3.6.2
- A detailed description of the bug / wanted feature: AutoFish check is too harsh, triggers when even manually fishing with enchanted rods, and occasionally normal rods
- If possible a short video of the bug:  Will post later
https://www.ecocitycraft.com/forum/threads/fishing-issues-thread.174157/#post-971262
That item causes the check to trigger, kicking players. As well as most regular vanilla enchants.

@CeIebrimbor can confirm the report.

**Comment by Photon-GitHub** [comment]
For best evaluation I need multiple logs (as many as you have) with the according information (e.g. the names of players affected by fps, used items).

**Comment by JamieSinn** [comment]
Logs: https://pastebin.com/DRZ2Y1nK

Video being kicked when using a vanilla rod on mobs: https://puu.sh/zd6YL/c7b8c20c55.mp4
Enchants on above video: https://puu.sh/zd73u/4b9bdbf003.png

Manual fishing being kicked, https://puu.sh/zd7uP/1f5a466494.mp4
Rod: https://puu.sh/zd7zS/9fe5471d1b.png

**Comment by JamieSinn** [comment]
https://vimeo.com/253502637 - Video to show additional issues.

**Comment by Photon-GitHub** [comment]
Not actually false positives, but rather a bug in the vl calculation algorithm which enforces vl of "at least 15" instead of "at most 15" 🙄

**Comment by JamieSinn** [comment]
Thanks for looking into it!
Let me know when there's an updated build, and I'll test it out for you.

**Comment by Photon-GitHub** [comment]
Addressed in 3.6.3
