### ISSUE TITLE
Crazy timings

### ISSUE THREAD

**Issue by ArtNRG** [Photon-GitHub/AACAdditionPro#180]
- Server version: git-Paper-1320 (MC: 1.12.2)
- ProtocolLib version: ProtocolLib v4.4.0-SNAPSHOT-b390
- The version of AACAdditionPro: AACAdditionPro 3.6.2

I have 2 timings reports. Just look:
https://timings.aikar.co/?id=d8dafae986c94e48b9176f5d95ab2c59#plugins
https://timings.aikar.co/?id=d23b3e71773140bdb2a22f1ed3ddb6de#plugins

Timings without AACAdditionPro, all other stuff is the same:
https://timings.aikar.co/?id=52a2e79384d74954a28863fc6c113b7f

**Comment by Photon-GitHub** [comment]
Could you please post new timings without MassiveLag?
To temporarily fix the problem you can disable KillauraEntity. 
(The 1 tick task is the main heartbeat of the entities)

**Comment by ArtNRG** [comment]
@Photon-GitHub Do you need the new timings both without MassiveLag and with enabled KillauraEntity or I can disable KillauraEntity and post the timings?

**Comment by Photon-GitHub** [comment]
I would appreciate timings with KillauraEntity enabled and with MassiveLag disabled.

**Comment by ArtNRG** [comment]
> I would appreciate timings with KillauraEntity enabled and with MassiveLag disabled.
Here they are: https://timings.aikar.co/?id=6d5e04eb09674fe2a7a47c3f7f93e9f2#plugins

**Comment by Photon-GitHub** [comment]
Thank you.

> Seems like /aacreload is not reloading the AACAdditionPro config so I been forced to restart my server. <
That is normal behaviour. I clearly stated on my overview in bold and red color that the plugin is not compatible with reloads.

**Comment by Photon-GitHub** [comment]
Addressed in 3.6.3
