### ISSUE TITLE
False positives of Tower check

### ISSUE THREAD

**Issue by Toshka17** [Photon-GitHub/AACAdditionPro#181]
Please include:
- Server version: 1.8.8 paper
- ProtocolLib version: 4.1.0
- The version of AACAdditionPro: (this happened on 3.4.6)
- A detailed description of the bug / wanted feature: damage during construction up
- If possible a short video of the bug: https://vk.com/video?z=video447582011_456239060%2Fpl_cat_updates

Config: https://pastebin.com/SGiQJE40
Log: https://pastebin.com/8BTbSGqX

**Comment by Photon-GitHub** [comment]
I am not going to try and fix a bug which happened on really outdated ProtocolLib and AACAdditionPro versions. Please update and check again.

**Comment by Toshka17** [comment]
Did the last three versions have any changes to the tower check?
This video was uploaded by the player of my server. Okay. I'll try to record the video myself.

**Comment by Toshka17** [comment]
I can not repeat this on new versions. Perhaps it is already fixed or requires certain circumstances. I will watch what my players will write.

**Comment by Photon-GitHub** [comment]
I will close as resolved with the new versions.
Please don't hesitate to reopen if the bug reappears.

**Comment by Toshka17** [comment]
Latest AACAddition
Log: https://pastebin.com/2KSrSkfm   (Look at Nad33m)
Video: https://www.youtube.com/watch?v=buhZyRX8c70

It seems this is due to short-term falls in TPS.

**Comment by Photon-GitHub** [comment]
You cannot expect a plugin to support TPS drops to 3 or 5 TPS. If that is common on your server you should think of a hardware upgrade.

**Comment by Toshka17** [comment]
Unfortunately, the only reason is that tps falls on servers is anticheats, they consume about 70% of the CPU...
It's ironical :)
But AACAddition, of course, consumes almost nothing, unlike AAC or Spartan.
