### ISSUE TITLE
[AACAdditionPro] Task #354279 for AACAdditionPro v3.6.2 generated an exception

### ISSUE THREAD

**Issue by maxlehot1234** [Photon-GitHub/AACAdditionPro#182]
Please include:
- Server version: PaperSpigot 1.12.2 #1316
- ProtocolLib version: http://ci.dmulloy2.net/job/ProtocolLib/390/ <-- Latest one from the jenkins
- The version of AACAdditionPro: 3.6.2
- The version of AAC: 3.3.9
- The Error: https://pastebin.com/VY6FNLr8

It occured in the console when player login SOMETIMES.

Thanks again and have a nice day/night

**Comment by Photon-GitHub** [comment]
Most likely some plugin which modifies the internal teams list asynchronously, not a bug of my plugin.

**Comment by maxlehot1234** [comment]
Featherboard maybe. Only plugin on my server that use teams.
mardi 6 février 2018 10:20 -0500 de notifications@github.com  <notifications@github.com>:

**Comment by Photon-GitHub** [comment]
You can circumvent this error by disabling the team functionality in KillauraEntity, but that will weaken them a bit.
