### ISSUE TITLE
java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by ArtNRG** [Photon-GitHub/AACAdditionPro#183]
- Server version: git-Paper-1320 (MC: 1.12.2)
- ProtocolLib version: ProtocolLib v4.4.0-SNAPSHOT-b390
- The version of AACAdditionPro: AACAdditionPro 3.6.2
- Seems like this error sometimes appears after player logging in.
Console error:
https://pastebin.com/raw/m4eS08qK

**Comment by Photon-GitHub** [comment]
That is a problem of ProtocolLib. Please refer to this link:
https://www.spigotmc.org/threads/protocollib.36230/page-44#post-2619826
