### ISSUE TITLE
[Feature request] Per pattern commands

### ISSUE THREAD

**Issue by Minemaniak** [Photon-GitHub/AACAdditionPro#184]
Heuristics Addition is very useful, but what I'm missing in it is ability to do different actions based on patterns. Example config would explain it:

Current:

confidences:
      50: "aacstaffnotify {player} in {world} may be using Killaura (Heuristics)"
      75: "aacstaffnotify {player} in {world} is suspected for using Killaura (Heuristics)"
      90: "aacstaffnotify {player} in {world} is highly suspected for using Killaura (Heuristics)"
      97:
       - "aacstaffnotify {player} was banned for Killaura (Heuristics)"
       - "ban {player} Cheating"

After implementing this request:
confidences:
       default:
             50: "aacstaffnotify {player} in {world} may be using Killaura (Heuristics)"
             75: "aacstaffnotify {player} in {world} is suspected for using Killaura (Heuristics)"
             90: "aacstaffnotify {player} in {world} is highly suspected for using Killaura (Heuristics)"
             97:
              - "aacstaffnotify {player} was banned for Killaura (Heuristics)"
              - "ban {player} Cheating"
       P/32!:
       P/76?!:
            75: "aacstaffnotify {player} in {world} is suspected for using Killaura (Heuristics)"
            85: "ban {player} Cheating"

So, all patterns would execute first set of commands, but P/32! and P/76?! would use the latter. Of course, you could set different actions for every pattern.

**Comment by Photon-GitHub** [comment]
You can already do this via the API (although it is a bit bugged right now which will be fixed in the next version). I will not implement this as a config feature as Heuristics comprises over 100 patterns, which is not eligible for usual configuration.
