### ISSUE TITLE
Allow 1.8 - 1.12 protocol support for entity-killaura

### ISSUE THREAD

**Issue by craftrise** [Photon-GitHub/AACAdditionPro#186]
Support all versions, excluding version 1.9.

**Comment by CeIebrimbor** [comment]
It does. Just not servers that cross between 1.10+ and 1.8. Mojang made it impossible.

**Comment by Janmm14** [comment]
As Viaversion can do it, its not impossible.

**Comment by Photon-GitHub** [comment]
Addressed in 3.11.0
