### ISSUE TITLE
Arrows in npc KillauraEntity

### ISSUE THREAD

**Issue by MikhailY** [Photon-GitHub/AACAdditionPro#189]
Please include:
- Server version: paperspigot 1.12.2
- ProtocolLib version: http://ci.dmulloy2.net/job/ProtocolLib/390/
- The version of AACAdditionPro: 3.8.1
- A detailed description of the bug / wanted feature: 
- I already wrote about this bug, but it appeared again.
https://github.com/Photon-GitHub/AACAdditionPro/issues/163

End errors: https://pastebin.com/qJCPXDuV

So same in old versions 3.7.0 remained visible nick. http://prntscr.com/idylee

**Comment by Photon-GitHub** [comment]
The error is not associated with KillauraEntity and I am not sure what arrows you are referring to.

**Comment by Photon-GitHub** [comment]
Addressed in 3.9.0
