### ISSUE TITLE
InventoryRotation FP

### ISSUE THREAD

**Issue by Dunterra** [Photon-GitHub/AACAdditionPro#19]
When a player is running around and right-clicks a chest/container that they can't open (like it's in faction territory or in a protected worldguard region), it triggers InvenoryRotation false positives.

You can replicate this by creating a worldguard region were chest-access is deny and have a player try to open the chest while running around it.

**Comment by CeIebrimbor** [comment]
Can achieve kick level violations/warnings with this bug? (i.e. VL 10+)

**Comment by Dunterra** [comment]
Yes, it kicks then within seconds.

**Comment by Photon-GitHub** [comment]
Should be fixed, please reopen if it persists.
