### ISSUE TITLE
KillAura Entity problem

### ISSUE THREAD

**Issue by MatinDark** [Photon-GitHub/AACAdditionPro#190]
Please include:
- Server version: spigot 1.12.2 also check on paper spigot 
- ProtocolLib version: latest
- The version of AACAdditionPro: 3.8.1
- A detailed description of the bug / wanted feature: I recevie this error on my console
https://hastebin.com/otefinovos.css

**Comment by Photon-GitHub** [comment]
Addressed in 3.9.0
