### ISSUE TITLE
「Request」《Disable Checks in Combo Mode》 

### ISSUE THREAD

**Issue by LinsaFTW** [Photon-GitHub/AACAdditionPro#191]
Hi! I want to request a option to disable checks if the hitdelay is less than x because if it is lower than 10~ it just makes false positives with various checks.

I want it to be in the addition because it looks like better as a Addition than a feature of AAC for me.

It will be a really awesome feature for PvP Servers :D

Example config:

```### Enable or disable checks if the HitDelay is less than specified ###
hitdelay-addon:
# Minimum hitdelay to disable the checks
min-hitdelay: 10
# Disable the Killaura check that makes lot of false positives
disable-killaura: true
# Disable the Hitbox check (NOT REALLY RECOMMENDED)
disable-hitbox: false
# Disable the Fly check that makes lot of false positives in ComboFly
disable-fly: true

**Comment by Photon-GitHub** [comment]
I won’t add something that right out disables checks and is only applicable on a certain group of 1.8 servers. Please create your own addon.

**Comment by LinsaFTW** [comment]
Huh? My server is 1.12.2

**Comment by Janmm14** [comment]
Then ask someone
