### ISSUE TITLE
visible nick

### ISSUE THREAD

**Issue by MikhailY** [Photon-GitHub/AACAdditionPro#192]
Please include:
- Server version:  paperspigot 1.12.2 Latest Build
- ProtocolLib version: http://ci.dmulloy2.net/job/ProtocolLib/390/
- The version of AACAdditionPro: 3.9.0
- A detailed description of the bug / wanted feature: 
Playing on 1.12.2, everything is fine, but if 1.8 then nick is visible, and constantly dangle in front of the screen, the entrance to available 1.8 with protocolsupport
http://prntscr.com/if0u0v
- If possible a short video of the bug: -

**Comment by Photon-GitHub** [comment]
I clearly state on my overview that KillauraEntity is not 1.8.8-1.12.2 protocol compatible.

**Comment by MikhailY** [comment]
He compatible, I have several servers, on some nick invisible. I even tried without plugins and didn't understand why it happens.
