### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 6

### ISSUE THREAD

**Issue by NeNex-GitHub** [Photon-GitHub/AACAdditionPro#193]
- Server version: 1.8.8
- ProtocolLib version: 4.3.0
- The version of AACAdditionPro: 3.9.0
- A detailed description of the bug: 

I get kicked from the server with this error : http://puu.sh/zp8Tl/61e2cab676.png
- the configuration file has been regenerated
- killauraentity is disabled
- the different scaffold subparts are disabled
but the problem is still not solved

I know I did not have this bug with version 3.6.3

**Comment by craftrise** [comment]
If you using ViaVersion plugin, its normal.

**Comment by craftrise** [comment]
@Photon-GitHub , 

I have same error.

Server version: 1.8.8
ProtocolLib version: 4.3.0
AACAdditionPro: 3.9.0 - latest

How does the error occur? : If killauraentity enabled, you will get this error.

**Comment by Janmm14** [comment]
Client version?

**Comment by Photon-GitHub** [comment]
Client version is 1.11 apparently, but I am not really sure what could cause that, especially because of the huge changes between 3.6.3 and 3.9.0 and you cannot provide additional data.

**Comment by NeNex-GitHub** [comment]
I tested, and the bug seems to appear in version 3.7.0

**Comment by Photon-GitHub** [comment]
What about latest?

**Comment by NeNex-GitHub** [comment]
There is no problem in version 3.6.3
The problem exists in all the other version over 3.6.3
