### ISSUE TITLE
[FEATURE] KillAuraEntitySpawnEvent 

### ISSUE THREAD

**Issue by craftrise** [Photon-GitHub/AACAdditionPro#194]
Example: We want to cancel event, if player version not 1.8.

Required arguments:
 - getPlayer()
 - getEntity()
 - setCancelled()

**Comment by Photon-GitHub** [comment]
getEntity is not at all possible as of the internal handling. 
Why would you want to cancel it? Just code a KillauraEntityAddon, as defined in the api.
