### ISSUE TITLE
KAEntity Bypass(AntiBot)

### ISSUE THREAD

**Issue by jiangdashao** [Photon-GitHub/AACAdditionPro#195]
Please include:
- Server version: 1.8.8
- ProtocolLib version: 4.3.0
- The version of AACAdditionPro: latest
- A detailed description of the bug / wanted feature: KillAuraEntity
- If possible a short video of the bug: 

LiquidBounce b35
Antibot
I just use the "Swing" Antibot

https://imgur.com/a/zoyo7

**Comment by Photon-GitHub** [comment]
Please include your configuration of KillauraEntity.

**Comment by jiangdashao** [comment]
I use the Cele's config

**Comment by BlackHawk2306** [comment]
You can bypass the Entity with a Swing check, because it doesn't swing ;)

**Comment by Photon-GitHub** [comment]
Theoretically it is supposed to swing with the swing config option enabled. I will look into it.

**Comment by jiangdashao** [comment]
@Photon-GitHub 
LiquidBounce Antibot-WasInvisiable also can bypass kaentity check
I also try to use entity check command,and I saw the bot was not invisiable,but after i enable "WasInvisiable" antibot,LiquidBounce still ignore the bot
