### ISSUE TITLE
False positive on InventoryRotation

### ISSUE THREAD

**Issue by xion87** [Photon-GitHub/AACAdditionPro#196]
Please include:
- Server version:  paperspigot 1.8.9 + viaversion latest
- ProtocolLib version: 4.3.0
- The version of AACAdditionPro: 3.9.0
- A detailed description of the bug / wanted feature: 
I get kicked  personally after closing a gui of deluxemenu and random jumping and punching blocks around for a little, this happened to me in occcasional time where i get kicked, sometimes it trigger to (high levels 1-18) without kick
- If possible a short video of the bug: 
i have only the logs https://hastebin.com/mucedeyuli.rb

**Comment by Photon-GitHub** [comment]
I do require a video as I do not test everybody’s plugins. Also this rather seems like the problem of the plugin as I do not know of similar issues with normal inventories.

**Comment by xion87** [comment]
Here there is the video
https://gyazo.com/56d3821cfe43860a177e856ca9169a2f

**Comment by Photon-GitHub** [comment]
That is an incompatibility of deluxemenus as you have already said, so I cannot do much. Talk to the author of deluxemenus.

**Comment by CeIebrimbor** [comment]
DeluxeMenu is probably not closing inventories in a timely manner, or not at all. Clip should be able to fix that by treating it like any other menu/inventory.
