### ISSUE TITLE
EqualRotation FP with setbacks/glitches/teleports

### ISSUE THREAD

**Issue by Minemaniak** [Photon-GitHub/AACAdditionPro#197]
Please include:
- Server version: 1.8.8
- ProtocolLib version: 4.2.0
- The version of AACAdditionPro: 3.9.0
- A detailed description of the bug / wanted feature: Discovered along with this issue from AAC's tracker: https://github.com/konsolas/AAC-Issues/issues/1214 , when you are setback because of this FP, you also get EqualRotations VL's with every setback, potentially infinitely if Speed doesn't kick. Don't know if it happens specifically with this speed issue, or with AAC's setbacks in general, I suspect the latter
- If possible a short video of the bug: Easy to reproduce, so I guess video not needed.

**Comment by Minemaniak** [comment]
New info: it's not connected to only AAC's setback, but to setbacks/glitching at all. You probably know, that on 1.8.8 if you run into anvil in certain way, you can get glitched and teleported in place. It also triggers EqualRotation, but not any min_vl from AAC

Anvils: https://imgur.com/sc8W1Xt
Detection from anvils: https://imgur.com/UZu4Al6

**Comment by Minemaniak** [comment]
Not fixed in 3.10.0 beta

**Comment by Photon-GitHub** [comment]
Removed cancellation in 3.10.0
