### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by MikhailY** [Photon-GitHub/AACAdditionPro#199]
Please include:
- Server version: paperspigot 1.12.2
- ProtocolLib version: latest
- The version of AACAdditionPro: 3.9.1
https://hasteb.in/kulicoroca.avrasm

**Comment by Photon-GitHub** [comment]
Please don’t state „latest“, butthe actual Protocollib version.

**Comment by MikhailY** [comment]
http://ci.dmulloy2.net/job/ProtocolLib/390/

**Comment by Photon-GitHub** [comment]
Expired hastebin -> close.
