### ISSUE TITLE
SafeSkinBlinker bug

### ISSUE THREAD

**Issue by JuliCarles** [Photon-GitHub/AACAdditionPro#2]
It seems that the SkinBlinker check kicks players when they just enable and disable part of their skins fast.
(When going to options) 
I know this is a silly issue as I don't know if there's any way to difference when parts of the skin are being disabled by the player or by hacked clients.
This issue is mainly caused by players playing with their skin settings, it's up to you if you think this worth to be fixed.

Using latest AACAddition for 1.10 and a 1.10.2 server.

**Comment by Photon-GitHub** [comment]
Will close this for now as it is not reproducable.
