### ISSUE TITLE
[Suggestion] Add CustomPayload check

### ISSUE THREAD

**Issue by xion87** [Photon-GitHub/AACAdditionPro#201]
I would like to see a new "hack" check for custompayload crasher.
Basically you use the client JigSaw that have a "server crash" that allow to crash a 1.8.x server by sending bad packets.
For fix i see this plugin https://www.spigotmc.org/resources/custompayloadfixer-bungeecord-bukkit-spigot.39891/ but i would like to be integrated also in aacaddition if possible.
Thank you!

**Comment by Minemaniak** [comment]
Anti-crasher/ crasher-detector in general would be great addition to the AACAP. Maybe it's not strictly anticheat-related, but still extremely useful. What dou you think @Photon-GitHub ?

**Comment by Janmm14** [comment]
Those plugins already exist, why do it again?

**Comment by xion87** [comment]
because is not efficenty and author is innactive

**Comment by Photon-GitHub** [comment]
This is rather a Spigot bug itself and the problem has been fixed in 1.12.2. I don't think I will implement such a check as it is not really an anticheat task and has no use on newer versions.
