### ISSUE TITLE
Errror spamming and crash by using MurderMystery

### ISSUE THREAD

**Issue by xion87** [Photon-GitHub/AACAdditionPro#202]
Please include:
- Server version: 1.8.9 + viaversion
- ProtocolLib version: v4.3.0
- The version of AACAdditionPro: v3.10.0
- A detailed description of the bug / wanted feature: error on console https://hastebin.com/ihihopirih.md and a crash report (maybe related) https://hastebin.com/elepiwajox.sm and i use this plugin https://www.spigotmc.org/resources/minigame-murder-mystery-2-bungee-multi-arena-mysql-support.36894/

**Comment by Photon-GitHub** [comment]
I doubt that the error is directly caused by my plugin, but I will see what I can do.

**Comment by Photon-GitHub** [comment]
Is this still a thing?

**Comment by xion87** [comment]
i don't have tested since i dont use aac on 1.8.x version

**Comment by Photon-GitHub** [comment]
If this is still an issue please tag me with a message to reopen the issue.
