### ISSUE TITLE
[Feature request] Tower compatibility with world protection

### ISSUE THREAD

**Issue by Minemaniak** [Photon-GitHub/AACAdditionPro#203]
When you try to tower up fast in protected region, you sometimes get flagged for tower. You can bypass it via API, but why not add compatibility with such basic funcionality into the plugin? You can listen for cancelled BlockPlaceEvent to know when world protection cancelled place.

**Comment by Janmm14** [comment]
I think cancellation listening was especially removed in the past.

**Comment by Minemaniak** [comment]
Sorry, I didn't quite understand :( What has AAC cancel vl to do with tower from aacap?

**Comment by Photon-GitHub** [comment]
The detection of Tower checks might not work well with AAC‘s interact check if ignoring cancelled block places.
