### ISSUE TITLE
False positives of scaffold

### ISSUE THREAD

**Issue by Toshka17** [Photon-GitHub/AACAdditionPro#204]
After version 3.9.0 I had a lot of false positives for scaffold, and I returned to version 3.8.1 for a some time. But then I decided to upgrade to version 3.10.1. There have been fewer complaints about false positives, but there are still a lot of them. (sorry for my English, its google tr-r)

- Server version: 1.8.8 paper
- ProtocolLib version: v4.4.0-SNAPSHOT
- The version of AACAdditionPro: 3.10.2

- If possible a short video of the bug: https://youtu.be/ELXHMwV7g-A?t=3m3s

Log: https://pastebin.com/JjAMpTUC
C-r cnfg: https://pastebin.com/sv5EnMKL

**Comment by Photon-GitHub** [comment]
The video is very delayed and recorded with modded minecraft. Could you please try to replicate the false positive with vanilla minecraft?

**Comment by Toshka17** [comment]
My players use replaymode and can not use direct video recording all the time, because it significantly reduces FPS

**Comment by Toshka17** [comment]
Another of my players left a complaint. He recorded video directly

Video: https://www.youtube.com/watch?v=Zl4zDzZzOQk
Log: https://pastebin.com/2MmJtVRw

**Comment by Toshka17** [comment]
I have about 4 videos that the players sent me, but they are all made through replaymode

**Comment by craftrise** [comment]
@Photon-GitHub , I have no evidence, but it is clear that this problem is certain. We get a lot of feedback from the players.

**Comment by Toshka17** [comment]
When players use essentials /speed command, they are triggered by scaffold-check
https://www.youtube.com/watch?time_continue=61&v=EAJ31mQOjBA

**Comment by Toshka17** [comment]
One more incident
Log: https://pastebin.com/nqfeHjbE
Video: https://www.youtube.com/watch?v=OWepk4FO8kg

**Comment by Photon-GitHub** [comment]
Essentials speed is a compatibility issue I will not fix anytime soon, because why do you even check people who can modify their speed anyways?

**Comment by Janmm14** [comment]
@Photon-GitHub some gamemodes might initially alter speed of players without the player being able to change it

**Comment by Photon-GitHub** [comment]
In that case one needs to modify their average part config times, so it is already partially supported.

**Comment by Toshka17** [comment]
One more incident: 
Video: https://www.youtube.com/watch?v=83UbwSVTuQw
Log: https://pastebin.com/W6Af247B

**Comment by Photon-GitHub** [comment]
Addressed in 3.11.0
