### ISSUE TITLE
False positives of MultiInteraction

### ISSUE THREAD

**Issue by Toshka17** [Photon-GitHub/AACAdditionPro#205]
- Server version: paper 1.12.2
- ProtocolLib version: v4.4.0-SNAPSHOT
- The version of AACAdditionPro: 3.10.2
- A detailed description of the bug / wanted feature: The armor is locked from the removal by BedWarsRel plugin. The player tries to remove it and gets a false positives AACAddition for this.
- If possible a short video of the bug: https://www.youtube.com/watch?v=-SldAgjLB1M

**Comment by Toshka17** [comment]
Do I need to provide logs?

**Comment by Photon-GitHub** [comment]
Well, this is not directly a false positive, rather a compatibility issue. You may want to use the api o cancel as I deliberately decided against ignoring cancelled events.
