### ISSUE TITLE
(Feature request) CheatBreaker integration

### ISSUE THREAD

**Issue by LeaderYT** [Photon-GitHub/AACAdditionPro#206]
An sort feauture to use the public ban api from CheatBreaker to ban / alert staff when someone joins and there ip / account is banned from CheatBreaker.

**Comment by Photon-GitHub** [comment]
Cheatbreaker is a 1.7 client, a version which is unsupported by both AAC and AACAdditionPro. Thus this won't be implemented.

**Comment by Janmm14** [comment]
Additionally you would be required to inform users before such stuff is done because of privacy laws in several countries.

**Comment by LeaderYT** [comment]
I think you can join 1.8 servers with cheatbreaker

**Comment by LeaderYT** [comment]
And i can inform them
