### ISSUE TITLE
ISE:"Asynchronous entity world add!" onPacketReceiving, causing players to bug after teleport

### ISSUE THREAD

**Issue by MinecraftiUndCo** [Photon-GitHub/AACAdditionPro#208]
###Issue description

(On LPmitKev.de Mainserver, Photon knows what I mean)

java.lang.IllegalStateException: Asynchronous entity world add!

The problem occurs after teleportations and causes the player to see a black world where they can't do anything to get out. Does not happen on every teleport, appears just random.

**https://pastebin.com/HFEmFm0g**

###Core information
**Server version**: 1.8.9
**AAC version**: 3.3.13
**AAC AdditionPro version**: 3.10.2
**ProtocolLib version**: V. 4.3.0
**Plugin list**: AAC, AACAdditionPro, ProtocolLib, GeiloCheat & more own game plugins (network api, etc.)

###Special environment information

**ViaVersion version**: none
**ProtocolSupport version**: none
**ViaBackwards version**: none
**BungeeCord plugins**: Our own plugins (should not affect aac in any way)

**Comment by Photon-GitHub** [comment]
Might be fixed in 4.0.3. Please recheck on the newest version.

**Comment by Photon-GitHub** [comment]
Closed as of inactivity. Please tag me if you want to see this issue reopened.
