### ISSUE TITLE
[AACAdditionPro] KillauraEntity: Could not spawn entity as of too few game profiles for player

### ISSUE THREAD

**Issue by andrewkm** [Photon-GitHub/AACAdditionPro#209]
### Issue description

Catching this in console lately:
	Line 2342: 2018-04-01 14:22:39 [ERROR] [AACAdditionPro] KillauraEntity: Could not spawn entity as of too few game profiles for player Italiano_Ducky76
	Line 3585: 2018-04-01 19:36:06 [ERROR] [AACAdditionPro] KillauraEntity: Could not spawn entity as of too few game profiles for player ElenaAvalor
	Line 3589: 2018-04-01 19:36:32 [ERROR] [AACAdditionPro] KillauraEntity: Could not spawn entity as of too few game profiles for player ElenaAvalor

### Core information
**Server version**: 1.12.2 - Spigot Build 1541

**AAC version**: 3.3.13
**AAC config**: 3.3.13|1-Default-Celebrimbor

**AACAdditionPro version**: 3.11.0
**AACAdditionPro config**: 3.11.0|1-Default-Celebrimbor

**ProtocolLib version**: 4.3.0 Build 390

**Plugin list**: (on request via Discord - andrewkm-1759)

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by Photon-GitHub** [comment]
That error just means that you are probably the only person that has ever joined the server, which means no offline profiles are available to spawn the entity.

**Comment by andrewkm** [comment]
@Photon-GitHub shouldn't be labelled as an [Error] then, instead a [Warn] or an [Info]. Bad practice.
