### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by JuliCarles** [Photon-GitHub/AACAdditionPro#21]
It seems AACAdditionPro is trying to check a user which is Disconnected already and gives this error on console:
http://www.youscreenshot.com/4f69327d225efa09d4fb1ed00e785d1f

Server version: 1.10.2
AACAddition+ version: Latest
AAC version: Latest.
ProtocolLib version: 4.2.0

**Comment by Photon-GitHub** [comment]
The usermanager cannot get the user as he logged off just while being checked. I will try to fix it.

**Comment by Photon-GitHub** [comment]
It is not something to be afraid of, the functionality of the plugin persists.

**Comment by Photon-GitHub** [comment]
Should be fixed with 1.0.0
