### ISSUE TITLE
Critical CPU usages (KillAuraEntity) and error list

### ISSUE THREAD

**Issue by craftrise** [Photon-GitHub/AACAdditionPro#210]
**(AAC+: 3.11.0 | Viaversion: YES | Spigot: 1.8.8)**

After the activation of the KillAuraEntity check, CPU usage increased close to 100%.

**Plugin reports:**
http://prntscr.com/izqvte

**Timing reports:**
http://prntscr.com/izqvzp

**Current TPS:**
http://prntscr.com/izqwk5

**HTOP (With enabled KillAuraEntity and 150 more players):**
http://prntscr.com/izr06z

**HTOP (With disabled KillAuraEntity and 300 more players):**
https://prnt.sc/izr0zx

NOTE: Same software, same plugins, same other things.

**Errors:**
- https://hasteb.in/vikobaqa.bash
- https://hasteb.in/zimecidi.rb
- https://hasteb.in/ijepuraj.rb
- https://hasteb.in/oxuvomul.rb
- https://hasteb.in/ocunedux.bash
- https://hasteb.in/uqohubax.bash

Note: Do not consider "3.2.2.jar" because you changed the name in each version.

**Comment by Photon-GitHub** [comment]
The cpu increase of about 100% is normal as the server has to calculate and set movement, equipment, ping and much more for each entity, and there is one entity per player. Thus KillauraEntity usually adds between 1 and 1.5 times the server load.

Could send me your plugin list privately on discord, it might be helpful for fixing the errors.

**Comment by craftrise** [comment]
@Photon-GitHub ,
In general, we use 2 plugins. The others are the various APIs. (ProtocolLib, Viaversion...)
And these two plugins are stable and error-free. (We coded)

**Comment by Photon-GitHub** [comment]
Your ProtocolLib is an old version and might cause some of the errors. Do you mind updating?

**Comment by Reeferx7** [comment]
I have same error with lasted protocollib

ProtocolLib version 4.4.0-SNAPSHOT-b390

https://pastebin.com/Z9yn8Rnv

server: version 1.8.8-R0.1-SNAPSHOT

**Comment by craftrise** [comment]
@Photon-GitHub , We using 4.2.0 version. (1.8.8 Spigot)

**Comment by Photon-GitHub** [comment]
Will close as of the empty hastebins. Performance has already been discussed above.
