### ISSUE TITLE
Request feature

### ISSUE THREAD

**Issue by MatinDark** [Photon-GitHub/AACAdditionPro#213]
Hello if possible add compatibility to crackshot and crackshotplus this too plugin  is  one of most famous plugin on spigot with lot of downloads but the problem is aac and aacpro kick lot of people for false positive for example ak-47 knock back and ...... , if add  compatibility for this plugin i am sure aac and aacpro users will grow up!

**Comment by Photon-GitHub** [comment]
That will not happen anytime soon as of two reasons:
1) the plugin alters gameplay completely and probably needs its own anticheat to effectively stop cheaters 
2) it is easier to make one plugin compatible with an anticheat than making an anticheat compatible with dozens of plugins.

**Comment by MatinDark** [comment]
i am not  talking about make specific section hack block for this plugin i am just talk about false positive for this there is just knockback nothing else to at least when we use aac or aacpro don't kick players for speed or antiknockback!
