### ISSUE TITLE
DamageIndicators not working.

### ISSUE THREAD

**Issue by LinsaFTW** [Photon-GitHub/AACAdditionPro#215]
Please include:
- Server version: 1.12.2 Paper
- ProtocolLib version: Latest
- The version of AACAdditionPro: Latest
- A detailed description of the bug / wanted feature: DamageIndicators cancel is not setting health to static value since latest version; DamageIndicators works fine.

The only error i have: https://hastebin.com/oziloxodos.vbs

**Comment by Photon-GitHub** [comment]
The hastebin is empty.

**Comment by Janmm14** [comment]
No, hastebin just has problems again.

**Comment by LinsaFTW** [comment]
http://file.properties/paste/iwocihuyan.rb

This appears on player-join. Hope you can fix it soon :D

**Comment by Photon-GitHub** [comment]
Please do not state „latest“ as a version in future issues because I need to track back the version after an update. Especially ProtocolLib updates quite often.

**Comment by LinsaFTW** [comment]
http://ci.shadowvolt.com/view/ProtocolLib/job/ProtocolLib/ 6 months...

**Comment by Photon-GitHub** [comment]
Could you try and update to the current latest version? Your version is listed as experimental.

**Comment by LinsaFTW** [comment]
Still not working with the latest in spigotmc.

**Comment by LinsaFTW** [comment]
https://file.properties/paste/ecekuweguy.bash

**Comment by LinsaFTW** [comment]
Sometimes this error appears too:
[01:04:27 ERROR]: [AACAdditionPro] Unhandled exception number 4096 occured in onPacketSending(PacketEvent) for AACAdditionPro
java.lang.ClassCastException: null

**Comment by LinsaFTW** [comment]
Still not working.

**Comment by LinsaFTW** [comment]
Error: **https://hastebin.com/uzezupibaq.swift**

**Comment by Photon-GitHub** [comment]
Fixed in 3.12.2
