### ISSUE TITLE
UnsupportedOperationException isSprinting temporary player

### ISSUE THREAD

**Issue by andrewkm** [Photon-GitHub/AACAdditionPro#218]
### Issue description

Console throwing:
https://pastebin.com/raw/XRr6MQkG

Unsure if this is a dupe of the previous ones I reported, as this one looks a bit different.

### Core information
**Server version**: 1.12.2 - Spigot Build 1632

**AAC version**: 3.3.14
**AAC config**: 3.3.13|1-Default-Celebrimbor

**AACAdditionPro version**: 3.11.1
**AACAdditionPro config**: 3.11.0|1-Default-Celebrimbor

**ProtocolLib version**: 4.3.0 Build 390

**Plugin list**: (on request via Discord - andrewkm-1759)

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by Photon-GitHub** [comment]
This is a verified design problem of ProtocolLib itself in a very short time upon login. I will implement a short "save-time" to ensure this error doesn't appear.
