### ISSUE TITLE
Freecam check causes pvp not to work

### ISSUE THREAD

**Issue by xwolfyxNL** [Photon-GitHub/AACAdditionPro#22]
Hello,

I have had this problem since the purchase of the plugin that when the plugin is enabled pvp doesn't work. I have just found out this is caused by the freecam check. When you disable the check everything works. .fine again.

There are no logs and i am running the plugin version 1.0.0 that has just been released.

Hope this helps :) and that the problem can be fixed.

**Comment by CeIebrimbor** [comment]
Freecam does not create logs. The ONLY thing to really verify is there is no verbose for InventoryHit(AAC+) or Hitbox(AAC).

**Comment by Photon-GitHub** [comment]
Please tell me more about your setup (do you have a working aac, what server + protocollib version and any plugins that might in any way interfere with inventory handling).
If you want I would be willing to join your server to see what I can do, but I need your server-ip for that.

**Comment by Photon-GitHub** [comment]
Will close this as there was no further information given.
