### ISSUE TITLE
KillauraEntity Extra Options

### ISSUE THREAD

**Issue by LinsaFTW** [Photon-GitHub/AACAdditionPro#221]
To bypass the AAC Killaura Check you need to hit invisible zombies, so i though adding a option to make the Killaura Entity invisible and a zombie would be a good addition to prevent AAC Killaura bypasses.

invisible: true
zombie: true

Adding this would make people that try to bypass AAC Killaura hit the Killaura Entity so they get banned by AACAP.

**Comment by Janmm14** [comment]
Idk if it was changed but in earlier aac versions the aac killaura entity was not just a zombie.

**Comment by Photon-GitHub** [comment]
I will close this issue as you can make the entity automatically invisible by setting on_command to true and never execute the entitycheckcommand. I cannot completely replicate the zombies of AAC, thus this is an AAC feature request.
