### ISSUE TITLE
Error: Could not pass event EntityDamageByEntityEvent

### ISSUE THREAD

**Issue by Heliosard** [Photon-GitHub/AACAdditionPro#223]
AAC version: 3.3.14
AACAddition version: 3.11.1
Server version: git-TacoSpigot-"bf023c7d" (MC: 1.8.8)
ProtocolLib version: ProtocolLib v4.4.0-SNAPSHOT-b391
Citizens: Citizens v2.0.16-SNAPSHOT (build 1308)

Error: https://hastebin.com/fupuqawala.vbs

For information this is an error found on a practice server with a pvp system against citizens bots.

Can you fix that? Thanks

**Comment by Janmm14** [comment]
Wrong issue tracker.
