### ISSUE TITLE
AntiWorldDownloader Bypass

### ISSUE THREAD

**Issue by LinsaFTW** [Photon-GitHub/AACAdditionPro#224]
Please include:
- Server version: Paper 1.12.2

- ProtocolLib version: 4.3.0

- The version of AACAdditionPro: 3.12.2

- A detailed description of the bug / wanted feature: 
AntiWorldDownloader can be bypassed.

- If possible a short video of the bug: 
I dont have a video, but my gf has a pic of my lobby in singleplayer. (She doesnt have perms or anything) saying "AntiWorldDownlader is working" joking

**Comment by Janmm14** [comment]
There is a version of WorldDownloader somewhere which does not hint the server that it is about to download the world. Therefore bypasses to that can't be fixed.

**Comment by Photon-GitHub** [comment]
Just as @Janmm14 has already pointed out, there are wdl versions without server-api, thus they cannot be blocked.
