### ISSUE TITLE
ChunkUnloadEvent should be handled in same tick

### ISSUE THREAD

**Issue by new-sashok724** [Photon-GitHub/AACAdditionPro#225]
Hi! I would want to ask you to process ChunkUnloadEvent in same tick and not schedule it or at least save needed info from event/chunk before passing it to scheduled task, because by time scheduled task will execute any action on CraftChunk (Spigot org.bukkit.Chunk implementation), internal weak reference to NMS chunk would be null and server will be forced to load it again.

In our case, we use custom-built spigot with some optimizations and fixes, and one of our fixes updates internal reference to NMS chunk when it becomes obsolete due to chunk unloading. This is INTENDED behavior because internal reference would be null and updated if needed anyways, but possibly after much more time.

We don't want to support 'bug compatibility' with your plugin so we think it's your responsibility to properly handle this event

**Comment by Janmm14** [comment]
Would be probably easier to fix if you output stack traces when a plugin attempts to do this so authors can look up the problematic spots directly.

**Comment by new-sashok724** [comment]
![20180517040624](https://user-images.githubusercontent.com/8599643/40151291-b8c98cee-5987-11e8-971e-595e6820f99f.png)
Let me know if you need something else
