### ISSUE TITLE
Add: killaura entity HUG improvment idea

### ISSUE THREAD

**Issue by Nort721** [Photon-GitHub/AACAdditionPro#226]
Please include:
- Server version: 1.8.8
- ProtocolLib version: latest
- The version of AACAdditionPro: latest
- A detailed description of the bug / wanted feature: 
I think you should make the entity invisible most of the time, but when a player 
has high cps or when the player is fighting someone the entity will be visible for
a few seconds but the entity will be behind the player so he will not hit it by a mistake
that way the entity will not be super annoying and scary, and it will still won't be easy to
bypass because the entity will not be invisible when a player is fighting. also if I remove the bot
from the tab list, you can make the bot name be the name of one of the online players on my server
and then it will bypass the tab check-in AntiBot hacks because there is a player on the tab that has the name of the bot, that way I don't need to have this weird bot on my tab list

**Comment by Photon-GitHub** [comment]
You can already do that either with the api or the on_command option.
