### ISSUE TITLE
Scaffold and Tower bypass.

### ISSUE THREAD

**Issue by craftrise** [Photon-GitHub/AACAdditionPro#227]
Please include:
- Server version: 1.8.8
- ProtocolLib version: 4.2.0 
- The version of AACAdditionPro: 3.12.2 
- A detailed description of the bug / wanted feature: Scaffold and tower bypass. With LiquidBounce

**Watch full Video:** https://www.youtube.com/watch?v=PcwkahNP5AY&feature=youtu.be
**Config link:** https://we.tl/z3zbm9WDWB

Config from Celebrimbor.

**Comment by Photon-GitHub** [comment]
Tower is only merely faster than legits and still only allows short bursts. Thus no real bypass. The scaffold even sneaks to imitate legit behavior and I‘ve seen a lot of legits who were a lot faster than this Scaffold. I will improve the detection of Scaffolds in the next version as I have already planned, but both modules are rather automation than advantage.
