### ISSUE TITLE
Function "d.p.A.aS(PlayerMoveEvent)" executed 10,000-20,000 times a tick

### ISSUE THREAD

**Issue by bob7l** [Photon-GitHub/AACAdditionPro#229]
- Server version: Taco-Spigot 1.8.8
- ProtocolLib version: 4.3.0
- The version of AACAdditionPro:  3.12.2

The function "d.p.A.aS(PlayerMoveEvent)" is called 10,000-20,000 times a tick (20,000 with 200 players online concurrently) and it tends to take up 2-5% of the tick. 

I have everything in the config disabled other then Forge detection, labymod, and Damage Indicators. 

This is with 87 players online: https://i.gyazo.com/a04714a94ee0e13ea7e6dddf44bc3659.png

Here's with around 200: https://i.gyazo.com/1576d863fa8fa34939078ae63b3ff816.png

**Comment by bob7l** [comment]
The class aS registers PlayerToggleSprintEvent, PlayerToggleSneakEvent, and PlayerMoveEvent all for what it appears every single player who enters the server.  

This is also done no matter what's disabled/enabled

**Comment by craftrise** [comment]
@Photon-GitHub , for KillAuraEntitiy same thing: https://prnt.sc/izqvzp
