### ISSUE TITLE
PacketAnalysis problem

### ISSUE THREAD

**Issue by MatinDark** [Photon-GitHub/AACAdditionPro#233]
Please include:
- Server version:  1.12.2 paperspigot
- ProtocolLib version:  4.3.0
- The version of AACAdditionPro:  3.13.1
- A detailed description of the bug / wanted feature: there is some issue about packetanalysis i just install new version of aacpro and every 1 minute 10 people got kick for packetanalysis i check console but there is no error or ....

**Comment by MatinDark** [comment]
i also update protocolib to 4.4.0 dev build but there is no change

**Comment by Photon-GitHub** [comment]
Please show me logs and describe the situations when the players are kicked.

**Comment by Janmm14** [comment]
Do you use bungeecord?

**Comment by MatinDark** [comment]
yes i use bungeecord
https://mega.nz/#!c3pCUApD!CHhJ1VJW77zZGu93_NLctbuT7cUxiSjZf0bK_7EL8sA (log file)

**Comment by Janmm14** [comment]
Disable keepalive parts of packetanalysis due to bungeecord not handling pings properly.

**Comment by MatinDark** [comment]
[04:29:20 WARN]: [AACAdditionPro] Task #86080 for AACAdditionPro v3.13.1 generated an exception
java.lang.NullPointerException: null
and this error is spam on my lobby console idk what is that !

**Comment by andrewkm** [comment]
Same issue here @MatinDark 
https://github.com/Photon-GitHub/AACAdditionPro/issues/234
Seems to be 1.13.1 and something that changed.

**Comment by Photon-GitHub** [comment]
I will close this as of the bungeecord bug.
