### ISSUE TITLE
KillAura Entity check kicks 1.8 clients immedietly after connecting.

### ISSUE THREAD

**Issue by Geeveloper** [Photon-GitHub/AACAdditionPro#236]
Please include:
- Server version: Spigot - 1.12.2
- ProtocolLib version: v4.3.0
- The version of AACAdditionPro: AACadditionPro v3.12.2 (Also tested with the latest version)
- A detailed description of the bug / wanted feature: Players with 1.8 clients are immediately kicked after attempting to join. 
Error (Nothing to go off of):
`[17:35:25] [Server thread/INFO]: ➲ [Citizen] BipolarTaco has joined.
[17:35:25] [Netty Epoll Server IO #0/ERROR]: java.lang.NullPointerException
[17:35:25] [Server thread/INFO]: BipolarTaco lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.RuntimeException: An internal error occured.`

Debugged the issue. Comes from the AACadditionPro v3.12.x optimized config by Celebrimbor from the conditional commands under the thresholds for KillAura Entity check.

- Temporary Solution: Disabled KillAura Entity check (removing the conditional commands works as well)

**Comment by Photon-GitHub** [comment]
Please remember that I support ViaVersion and ViaBackwards, but both plugins do not allow 1.8 players joining a 1.12.2 server.
I close this as you use an unsupported setup, especially as KillauraEntity is already one of the most version-sensitive checks.
