### ISSUE TITLE
WARN [AACAdditionPro] Task #1379 for AACAdditionPro v3.13.1 generated an exception

### ISSUE THREAD

**Issue by leoncp9** [Photon-GitHub/AACAdditionPro#237]
https://drive.google.com/open?id=1JdjdpkxjsdUc-ZmR_Zb0_yE-ws1jg-xC
https://drive.google.com/open?id=1bhvqIlq9JXoR26GGkEb96wL43uGfS4Mq
paper 1.12.2 latest
all plugin latest

**Comment by Photon-GitHub** [comment]
Please use services like Pastebin for showing the errors as I need to manually type in the text of your pictures.
