### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by Tyrelis** [Photon-GitHub/AACAdditionPro#238]
- Server version: 1.12.2
- ProtocolLib version: Latest
- The version of AACAdditionPro: Latest
- A detailed description of the bug / wanted feature: console error https://pastebin.com/WRcARteA
- If possible a short video of the bug: N/A

**Comment by Photon-GitHub** [comment]
The pastebin is no longer available and "Latest" is not a valid version number (is it 3.13.0, 3.13.1 or 4.0.0 by now?).

**Comment by Tyrelis** [comment]
I am closing this issue I had the pastebin expire after a month it's no longer relevant.
