### ISSUE TITLE
Request: Restrict names used

### ISSUE THREAD

**Issue by CypherPhyre** [Photon-GitHub/AACAdditionPro#239]
- Server version: 1.12.2-R0.1-SNAPSHOT
- ProtocolLib version: v4.4.0-SNAPSHOT-b392
- The version of AACAdditionPro: v3.13.1

In a future update to the config, could an option be added to restrict some names from being used for the KillAuraEnt? I just had a player accusing another player of hacking. It was my alt account that I use for testing.

**Comment by Photon-GitHub** [comment]
I am not sure what you want to do with that feature as the next time not your alt account, but some other player will be accused of cheating.
