### ISSUE TITLE
Error in console.

### ISSUE THREAD

**Issue by Francy1978** [Photon-GitHub/AACAdditionPro#249]
Please include:
- Server version: PaperSpigot-1.8.8
- ProtocolLib version: Build 403
- The version of AACAdditionPro: 4.0.0
- A detailed description of the bug / wanted feature: 
- If possible a short video of the bug: The error is generated when a player enters the server or hits you.
Error: https://pastebin.com/raw/7iZgAMsH

**Comment by Photon-GitHub** [comment]
In order to recreate the false positive please create a new issue with the full AACAdditionPro log as well as a video on how to reproduce.
