### ISSUE TITLE
Freecam check incompatibility with BetterChairs

### ISSUE THREAD

**Issue by Fonzee9** [Photon-GitHub/AACAdditionPro#25]
How do i know it was free cam? I didn't have this problem with regular AAC but after i got AACAdditionPro i did so i disabled each check and tested it and i kept getting launched off the chair until i disabled the freecam check.

When a player sits down after 10 seconds they get launched up for freecam... when they are really just sitting on a chair

**Comment by Photon-GitHub** [comment]
Should be fixed in the upcoming version 1.2.
