### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Feerko** [Photon-GitHub/AACAdditionPro#252]
Please include:
- Server version: 1.12.2
- ProtocolLib version: 4.4.0-SNAPSHOT-b406
- The version of AACAdditionPro: 4.0.2
- A detailed description of the bug / wanted feature: 

https://pastebin.com/raw/WtPYxEKi after this error my server get crash.

**Comment by Photon-GitHub** [comment]
Please recheck on 4.0.3 as this might be fixed.

**Comment by Photon-GitHub** [comment]
Any result?

**Comment by Photon-GitHub** [comment]
Closed as of inactivity. Please tag me if you want to have this issue reopened.
