### ISSUE TITLE
Cannot find class FluidType

### ISSUE THREAD

**Issue by Tyloonie** [Photon-GitHub/AACAdditionPro#253]
Please include:
- Server version: Paper 1.12.2
- ProtocolLib version: 4.4.0-SNAPSHOT-b405
- The version of AACAdditionPro: 4.0.2
- A detailed description of the bug / wanted feature: https://hastebin.com/xefexofata.rb (happens every time a player joins or uses a command and is non OP)

**Comment by Janmm14** [comment]
ProtocolLib 404 and higher are 1.13 only. Downgrade to compatible ProtocolLib version.
