### ISSUE TITLE
PacketAnalysis false positives on player login

### ISSUE THREAD

**Issue by DaveDevil** [Photon-GitHub/AACAdditionPro#256]
Please include:
- Server version: 1.12 and 1.12.2
- ProtocolLib version: 403
- The version of AACAdditionPro: 4.0.2
- A detailed description of the bug / wanted feature: 

When a player log in one of the network servers, it reaches immediately the PacketAnalysis threshold (28) and the commands are executed (actually I setup a warn system instead of automatic kick). It is not related with ping, version of the client or other things I could think

- If possible a short video of the bug:

**Comment by BestMark** [comment]
Same problem

**Comment by Photon-GitHub** [comment]
Please include logs and a little video of the affected players spawning. Is the problem only appearing when a player changes the server or also when joining your network?

**Comment by DaveDevil** [comment]
all players are affected, and all on server change, not on network join.

what kind of logs do you need? in console none errors are appearing, and I don't really know what to record on a video...

**Comment by xion87** [comment]
Same problem, having it enabled (only from 4.0.0+ version it cause people be random kicked for PacketAnalysis, so is something that you changed from that version ;)

**Comment by Photon-GitHub** [comment]
If this is still a problem please report back with the AACAdditionPro logs and at best a video with verbose enabled showing the spawining process. Although you might think "there is nothing special, why should I record a video" it is often very helpful and includes lots of hints for me as a developer on what could cause the fps.

**Comment by Photon-GitHub** [comment]
Closed due to inactivity.
