### ISSUE TITLE
Bug Player disappear

### ISSUE THREAD

**Issue by QuiquePineyro** [Photon-GitHub/AACAdditionPro#257]
Please include:
- Server version:  PaperSpigot-1.11.2
- ProtocolLib version:  4.2.1 (4.4.0-SNAPSHOT-b390)
- The version of AACAdditionPro:  4.0.2
- A detailed description of the bug / wanted feature:  
Every time If I away from a player it disappears and not appear until I re-login or try to hit them

- If possible a short video of the bug:  https://streamable.com/a6vcz

**Comment by BestMark** [comment]
Same problem

**Comment by Photon-GitHub** [comment]
Do you have KillauraEntity enabled? If the answer is yes, please disable the check as it is unstable right now.

**Comment by BestMark** [comment]
Yes, when I disabled it, bug is fixed.
