### ISSUE TITLE
Inventory Overwatch

### ISSUE THREAD

**Issue by Photon-GitHub** [Photon-GitHub/AACAdditionPro#26]
In my opinion the easiest way of detecting inventory-cheats is a neural network which differentiates between a legit player and a bot. This is a long-term project and will be implemented over time.

**Comment by timothydavidhart** [comment]
Could you explain this more i dont really get it

**Comment by Janmm14** [comment]
its an idea of a possible check for the far future

**Comment by Photon-GitHub** [comment]
Addressed in 3.5.0
