### ISSUE TITLE
Unhandled exception executing command 'aacap' in plugin AACAdditionPro v4.1.0

### ISSUE THREAD

**Issue by leoncp9** [Photon-GitHub/AACAdditionPro#264]
Please include:
- Server version: paper spigot 1.12.2
- ProtocolLib version: 4.4.0
- The version of AACAdditionPro: 4.1.0
- A detailed description of the bug / wanted feature: i can't do /aacap on game
- If possible a short video of the bug: 
DOWNLOAD LOG (use notepad++)
https://drive.google.com/open?id=1zJMh-kJBfEWAQBOUMqrtdKsuS9w-7WL9

**Comment by Photon-GitHub** [comment]
Duplicate of #263
