### ISSUE TITLE
Inventory click ERROR

### ISSUE THREAD

**Issue by timr2000** [Photon-GitHub/AACAdditionPro#266]
Please include:
- Server version: paperspigot 1.12.2
- ProtocolLib version: 4.4.0-SNAPSHOT-b403
- The version of AACAdditionPro: 4.1.1
- A detailed description of the bug / wanted feature: When opening an inventory menu
- If possible a short video of the bug: Error in the console **>** _https://pastebin.com/neZKMKkD_

**Comment by Photon-GitHub** [comment]
Your AAC seems to have no API provided. Can you try redownloading AAC and making sure it is loaded correctly?

**Comment by timr2000** [comment]
Looks like that worked, thankyou
