### ISSUE TITLE
Getting Kick 

### ISSUE THREAD

**Issue by Terrifical** [Photon-GitHub/AACAdditionPro#269]
- Server version: 1.12.2

- ProtocolLib version: http://ci.dmulloy2.net/job/ProtocolLib/403/

- The version of AACAdditionPro: 4.2.1

- Console error message: https://pastebin.com/uA07wxRJ - & - https://pastebin.com/u0vuSKQ7

- A detailed description: Only happens once when the server first starts up, you get kicked from the server.

**Comment by Janmm14** [comment]
Don' post errors about AAC here @Terrifical, the second prolbem should be on the aac issue tracker.
