### ISSUE TITLE
AutoFish blocker doesn't work with Mcmmo :( 

### ISSUE THREAD

**Issue by Fonzee9** [Photon-GitHub/AACAdditionPro#27]
Just tested autofish on my server with mcmmo for an hour and it never kicked me but on my test server without mcmmo it kicked me..

**Comment by CeIebrimbor** [comment]
Is any server version 1.8?

**Comment by Fonzee9** [comment]
No 1.11.2

**Comment by Photon-GitHub** [comment]
Should be fixed in 1.2.1

**Comment by Photon-GitHub** [comment]
1.2.1 is now released.
