### ISSUE TITLE
PacketAnalysis False Positives

### ISSUE THREAD

**Issue by PiiSaba** [Photon-GitHub/AACAdditionPro#270]
Please include:
- Server version: spigot 1.8.8
- ProtocolLib version: 403
- The version of AACAdditionPro: 4.2.2
- A detailed description of the bug / wanted feature: I am sorry but I cannot describe the problem. Because I am a Japanese. So I made a video. Please watch it!
- If possible a short video of the bug: 
https://www.youtube.com/watch?v=yi1b6h2XgWo&feature=youtu.be

**Comment by Janmm14** [comment]
Your client is not behaving like a normal minecraft client.

**Comment by PiiSaba** [comment]
Um  I used vanilla 1.9.4.

**Comment by Janmm14** [comment]
Ok, I'm sorry didn't watch video long enough :/
