### ISSUE TITLE
Killaura entity error

### ISSUE THREAD

**Issue by MatinDark** [Photon-GitHub/AACAdditionPro#273]
Please include:
- Server version: PaperSpigot 1.12.2
- ProtocolLib version: 4.4.0-SNAPSHOT-b403
- The version of AACAdditionPro: 4.2.2
- A detailed description of the bug / wanted feature: there is an error on the console when enabling KillauraEntity more details in https://hastebin.com/unujolinuy.css
**i am using Cele's config for AAC and AACPRO**

**Comment by Janmm14** [comment]
Please refrain from using hastebin.com, it has server instabilities.

**Comment by Photon-GitHub** [comment]
Not a bug, but a debug statement for me to find certain bugs.
