### ISSUE TITLE
Packet analysis false positive

### ISSUE THREAD

**Issue by MatinDark** [Photon-GitHub/AACAdditionPro#274]
Please include:

- Server version: PaperSpigot 1.12.2
- ProtocolLib version: 4.4.0-SNAPSHOT-b403
- The version of AACAdditionPro: 4.2.2
- A detailed description of the bug / wanted feature: I don't know exactly what happened just I saw 5-10 people were kicked by console because of packet analysis and I am sure they don't do anything wrong more details available on https://paste.ubuntu.com/p/vQwVjkCDKj/
 **I am using Cele's config for AAC and AACPRO**

**Comment by Photon-GitHub** [comment]
The log shows some similarities with toggling Pingspoof behaviour (perfect 500 ping, sudden drop and then about 500 again). That is what PacketAnalysis is supposed to detect if some other packets' response times stay the same. Can you 100% confirm that this is a legit player, i.e. reproduce that bug?

**Comment by Photon-GitHub** [comment]
Closed as of inactivity. Please tag me to reopen the issue.
