### ISSUE TITLE
Plugin doesn't Start :(

### ISSUE THREAD

**Issue by ArrowReport** [Photon-GitHub/AACAdditionPro#276]
Server Version: CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8)
AACAdditionPro Version: 4.3..0
ProtocolLib Version: b341 (v4.2.0)

Error on Start: 
https://paste.ubuntu.com/p/SdCShrkG2q/

The Plugin isn't even shown on /plugins lol

**Comment by Photon-GitHub** [comment]
Please redownload AACAdditionPro.

**Comment by ArrowReport** [comment]
AACAP Works after ReDownloading
