### ISSUE TITLE
GravitationalModifier

### ISSUE THREAD

**Issue by leoncp9** [Photon-GitHub/AACAdditionPro#281]
Please include:
- Server version: 1.12.2
- ProtocolLib version: 4.4.0
- The version of AACAdditionPro: 4.4.0
- A detailed description of the bug / wanted feature: false GravitationalModifier
- If possible a short video of the bug: 
When i walk around of my hub, i get kick cause GravitationalModifier

**Comment by leoncp9** [comment]
try to walk for 2 minutes on my hub with 1.12.2 version, you get kick for nothing for GravitationalModifier
ip aroundcraft.com

**Comment by leoncp9** [comment]
This is my config
# GravitationalModifier improves the detection speed of various movement-cheats
GravitationalModifier:
  # Do you want to enable the GravitationalModifier check
  enabled: true
  # Map of violation levels to command
  thresholds:
    7: "conditionalcommands:cc {player} if -ping->1000&-tps->19.0&-time_online->5000&-uptime->200 do aackick {player} Internet/Server Issues?"
    11: "conditionalcommands:cc {player} if -ping-<50&-tps->19.8 do aackick {player} GravitationalModifier"
    15: "conditionalcommands:cc {player} if -ping-<100&-tps->19.5 do aackick {player} GravitationalModifier"
    19: "aackick {player} GravitationalModifier"

VIDEO:
https://www.youtube.com/watch?v=wg1XeAhzx_U&feature=youtu.be

**Comment by Photon-GitHub** [comment]
The person in the video uses a cheating client.

**Comment by leoncp9** [comment]
yes, i use a client, but i don't have hack active

**Comment by Janmm14** [comment]
You couldve started vanilla mc for the video and as you disabled the hud we dont know whether a cheat was active.

Some cheats maybe dont disable properly or they changed something accidentally which could cause problems.

**Comment by leoncp9** [comment]
i have problem with, 1.8.8, 1.12.2, 1.13.1 version of minecraft, the problem is not client, try you, walk around of my hub, aroundcraft.com

**Comment by Janmm14** [comment]
Ok report is valid.

**Comment by leoncp9** [comment]
ooook
