### ISSUE TITLE
no bug, only question

### ISSUE THREAD

**Issue by leoncp9** [Photon-GitHub/AACAdditionPro#291]
is possbile make a good entity killaura like mineplex? for real, because now, when i join, after some seconds entity get glitch and stay far far of me, entity never control my kill aura like mineplex control

**Comment by leoncp9** [comment]
of you have a config for entity can you send me it?

**Comment by Photon-GitHub** [comment]
Currently KillauraEntity is recoded and in beta, thus such bugs can appear.
There is no config that makes them bugfree, sadly.
