### ISSUE TITLE
Performance problems / ESP

### ISSUE THREAD

**Issue by DarkAndBlue** [Photon-GitHub/AACAdditionPro#294]
Please include:
- Server version: CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
- ProtocolLib version: v4.2.1
- The version of AACAdditionPro: v4.6.1
- A detailed description of the bug / wanted feature: Performance problems after a long server uptime. The problem can be ESP with a few players
- If possible a short video of the bug:

**Comment by Photon-GitHub** [comment]
Closed due to inactivity.
