### ISSUE TITLE
AutoFish not checking for machines

### ISSUE THREAD

**Issue by untuned** [Photon-GitHub/AACAdditionPro#298]
- Server version: 1.12.2 (git-Paper-1594)
- ProtocolLib version: 4.4.0-SNAPSHOT-b403
- The version of AACAdditionPro: 4.5.0
- A detailed description of the bug / wanted feature: AutoFish doesn't detect if a player is holding right clicks, for example with an AFK fish farm.  Instead just causes a violation.
- If possible a short video of the bug: I have a video of the farm they used. https://www.youtube.com/watch?v=Y31TEbKjSpg

**Comment by Photon-GitHub** [comment]
Can you please add logs of such an incident?

**Comment by Photon-GitHub** [comment]
Closed due to inactivity.
