### ISSUE TITLE
liteloade 1.8 full bypass aacadditionalpro control

### ISSUE THREAD

**Issue by leoncp9** [Photon-GitHub/AACAdditionPro#300]
Please include:
- Server version: paper 1.12.2
- ProtocolLib version:  ProtocolLib#422
- The version of AACAdditionPro:  AACAdditionPro 4.6.2
- A detailed description of the bug / wanted feature: 
Forge and Liteloader
https://www.youtube.com/watch?v=7Nj2jqI69iE
antiforge
https://uploadfiles.io/elj2j
- If possible a short video of the bug:

**Comment by leoncp9** [comment]
liteloader mod simulates vanilla mode

**Comment by Photon-GitHub** [comment]
If you modify Liteloader in a way to deliberately modify vanilla, you cannot block the mod. My ClientControl section mostly depends on the cooperation of the mod developers by offering APIs to detect the mod.
