### ISSUE TITLE
he server you were previously on wetn down

### ISSUE THREAD

**Issue by mateulusz** [Photon-GitHub/AACAdditionPro#311]
It kicks players with reason:
`The server you were previously on wetn down, you have been connected to a fallback server.`

I'm using the latest version before beta. It doesn't throw any errors and I'm sure AACAdditionPro is the reason because I added it today and issue appeared.

**Comment by Photon-GitHub** [comment]
That message has nothing to do with AACAdditionPro directly as it is a bungee notification. I need way more information before I am able to figure out the issue including full server logs and AACAdditionPro logs.

**Comment by Photon-GitHub** [comment]
Closed due to inactivity.
