### ISSUE TITLE
Inventory NullPointerException

### ISSUE THREAD

**Issue by ArrowReport** [Photon-GitHub/AACAdditionPro#317]
Someone got banned and then your Plugin was erroring around

https://i.vgy.me/wkH3C6.png

**Comment by Photon-GitHub** [comment]
Do you use a server different from Spigot? Also, please try updating ProtocolLib if possible. That error should not appear as it means that an offline player has sent a packet.

**Comment by ArrowReport** [comment]
At this time i used ProtocolLib 4.4.0 and ViaVersion 1.6.0 and AAC 3.6.4 and 6 other shitty Anticheats

**Comment by Photon-GitHub** [comment]
The picture is no longer available. Please use a service that saves the information at least a few months. Still, you haven't answered my question if you use Spigot or a derivate of it or something else.
