### ISSUE TITLE
normal liteloader 1.12.2 bypass

### ISSUE THREAD

**Issue by leoncp9** [Photon-GitHub/AACAdditionPro#319]
aacap 5.1.1 don't work anymore with liteloader why? i have tryed and i bypassed the control of your plugin, mt server version is paper spigot 1.12.2

**Comment by leoncp9** [comment]
i have used liteloader 1.12.2

**Comment by Photon-GitHub** [comment]
Can you please send me a screenshot of your F3 debug screen during your test? If you want to message it me privately.

**Comment by leoncp9** [comment]
work
