### ISSUE TITLE
Bukkit 1.11.2 Whole plugin doesnt work?

### ISSUE THREAD

**Issue by anonyado** [Photon-GitHub/AACAdditionPro#32]
So i just bought the plugin im running on a 1.11.2 Bukkit server. The plugin just wont load/create a folder?

What to do now?

**Comment by anonyado** [comment]
Nevermind, if possible could i get a refund.
I just saw in the tiny letters i need AAC3 first. 
No $ for the at the moment so this was a waste to buy.

Next time put it with some bigger Letters.

**Comment by CeIebrimbor** [comment]
Just get AAC for your server. It is listed in dependencies. If not, you can just wait until you have enough cash to get AAC. Not like this resource is going away. Heck, you might have just got it at a lower price than if you had waited longer.

**Comment by Photon-GitHub** [comment]
Refunded.
