### ISSUE TITLE
Erroring

### ISSUE THREAD

**Issue by ArrowReport** [Photon-GitHub/AACAdditionPro#323]
Your Plugin is erroring around idk

![Screenshot_2019-05-01-19-37-23](https://user-images.githubusercontent.com/41682827/57031708-b6184600-6c48-11e9-9daf-5d05d34b0bf9.png)

**Comment by Photon-GitHub** [comment]
Please give more information about your server, i.e. spigot version, as well as your AACAdditionPro logs.

**Comment by ArrowReport** [comment]
Server Version: 1.8.8
ViaVersion: 2.0.1
AAC: 3.6.4
ProtocolLib: 4.4.0


https://paste.ubuntu.com/p/y5B8VSP6By/

**Comment by ArrowReport** [comment]
Line 1704 until Line 2742 is the Problem i think

**Comment by Photon-GitHub** [comment]
Might be fixed in 5.1.3. Please test once it is released.
