### ISSUE TITLE
paper spigot 1.13.2 

### ISSUE THREAD

**Issue by leoncp9** [Photon-GitHub/AACAdditionPro#326]
problem
Task #842 for AACAdditionPro v5.1.2 generated an exception
Task #841 for AACAdditionPro v5.1.2 generated an exception
log
https://pastebin.com/SvARBmVG

**Comment by Photon-GitHub** [comment]
Probably caused by changes to how the getCubes method works in 1.13.2.
More drastic changes happened in 1.14, which is why KillauraEntity will not work anymore on 1.14.

**Comment by leoncp9** [comment]
rip killaura entity, is cool options , can you make tutorial for set killaura entity like mineplex ro cubecraft? kill aura entity stay always near of player on mineplex, with you plugin.. after some seconds kill aura entity leave from range of player nad go around for the map
