### ISSUE TITLE
AACAdditionPro errors

### ISSUE THREAD

**Issue by pvpstryker** [Photon-GitHub/AACAdditionPro#328]
Server version 1.8.8
AACAdditionPro: Latest version
AAC: Latest version

https://pastebin.com/GQgsysAa

**Comment by Janmm14** [comment]
AACAdditionPro requires ProtocolLib 4.4.0 or higher if I remember correctly.

**Comment by Photon-GitHub** [comment]
As Janmm14 has already pointed out, please use ProtocolLib 4.4.0 or higher.
