### ISSUE TITLE
Skinblinker/FOV zoom False Positive

### ISSUE THREAD

**Issue by Zaino60** [Photon-GitHub/AACAdditionPro#33]
You get kicked when holding Shift + F3 and pressing the f key multiple times, it's weird.
Video reproducing the bug: https://www.youtube.com/watch?v=EtS5W36UuX8&feature=youtu.be
AACAdditionPro log: http://pastebin.com/cHyR35AH (Look for user: Zainos)
AAC Version: 3.0.5 (latest)
AACAdditionPro version: 1.3.2 (latest)
Spigot Version: This server is running CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
Plugin List: LibsCommands, TopLite, WorldEdit, SpawnTP, EsconderJugadores, Fly, PlayerSkulls, WorldBorder, BuycraftX, Votifier, WorldGuard, VoidSpawn, AntiWDL, ProdigyGadget, AutoSaveWorld, UltimateMenu, MVdWPlaceholderAPI, ExecuteEverywhere, EmeraldLauncher2, Emotes, Portal_Menu, EchoPet, LobbyBow, PermissionsEx, LagMeter, FeatherBoard, DiscoArmor, ConditionalCommands, ViaVersion, CustomJoinItems, Vault, ServerTokens, PwnFilter, HiddenSpectators, ProtocolLib, LibsDisguises, DeluxeChat, SexyPEX, AAC, eZProtector, WelcomeBookRecoded, AnimatedTab, AACAdditionPro, HolographicDisplays, HappyCrates, BossShop

**Comment by Photon-GitHub** [comment]
Will be fixed in 1.4 (the next update).
