### ISSUE TITLE
ConcurrentModificationException NPC

### ISSUE THREAD

**Issue by leoncp9** [Photon-GitHub/AACAdditionPro#331]
server version: paperspigot 1.12.2
log
https://pastebin.com/6sKCx3Ci

**Comment by Photon-GitHub** [comment]
This is either caused by some plugin that modifies teams asynchronously or it is a bug in the scoreboard management of Bukkit. AACAdditionPro only reads all the teams from the scoreboard and doesn't modify teams outside the main thread.
