### ISSUE TITLE
Scaffold false positives

### ISSUE THREAD

**Issue by Toshka17** [Photon-GitHub/AACAdditionPro#333]
I myself was kicked for using cheats :/
Log: https://pastebin.com/5GJRFfm6

paperspigot 1.12.2
latest aacap (5.1.2)
protocollib 4.4.0

**Comment by Janmm14** [comment]
you used vanilla mc? which version? what build technique?

**Comment by Toshka17** [comment]
Vanilla MC 1.12.2 + Optifine + Litemod (WorldeditCUI + MacrosMod)

**Comment by Photon-GitHub** [comment]
As this is the sprinting check that should not cause any fps whatsoever I am inclined to believe that your mods might cause that. Can you please try to replicate this without mods and record the false positives?

**Comment by Toshka17** [comment]
How can a mod to select cubes and mods to create hotkeys affect this?

**Comment by Photon-GitHub** [comment]
Idk, but I have seen a few mods that seem to have no effect on movement at all but then modifying movement packets nonetheless. Can you please test it without the mods and record it on video?

**Comment by Photon-GitHub** [comment]
Inactivity.
