### ISSUE TITLE
 KillauraEntity: Could not spawn entity as of too few game profiles for player

### ISSUE THREAD

**Issue by leoncp9** [Photon-GitHub/AACAdditionPro#334]
log
https://pastebin.com/RvYaHaf6

server version paper 1.12.2

**Comment by Photon-GitHub** [comment]
This just means that your server has not yet been visited by enough players to have sufficient game profiles.
It is not an error, just join with a few other accounts.

**Comment by leoncp9** [comment]
grrrrrr

**Comment by Photon-GitHub** [comment]
?
