### ISSUE TITLE
double entity killaura for player

### ISSUE THREAD

**Issue by leoncp9** [Photon-GitHub/AACAdditionPro#339]
photo:
https://prnt.sc/oiyw9u

server version: paperspigot 1.12.2
Why i can see two entity killaura ??

**Comment by leoncp9** [comment]
and why they are far to me and walk around of lobby?

**Comment by Photon-GitHub** [comment]
I will remove KillauraEntity in the next version.

**Comment by leoncp9** [comment]
ook
