### ISSUE TITLE
Inventory checks false positives

### ISSUE THREAD

**Issue by MedicOP** [Photon-GitHub/AACAdditionPro#34]
The inventory checks, such as InventoryRotation and InventoryMove seem to give a lot of false positives, both when using the default config and using Celebrimbor's optimized config, to the point where it's kicking legitimate players.

AACAdditionPro version: latest
AAC version: latest
Spigot version: 1.8

Let me know if you need any specific info

**Comment by MedicOP** [comment]
After some debugging, it appears that sometimes AACAdditionPro thinks a player still has an inventory open even though it is already closed on the player's side. Walking around causes VL to skyrocket for these checks. Re-opening and closing an inventory seems to fix it.

Not sure if this is a Bukkit bug or if it can be fixed on AACAddition's side

**Comment by CeIebrimbor** [comment]
It sounds like you may have something manipulating inventories if your players skyrocket in VL.

Plugins? AACaddition logs? (video would be nice)

**Comment by MedicOP** [comment]
It seems to be caused by my dueling plugin, it opens an inventory menu for sending a duel request to another player.

However, in the source code it calls player.closeInventory() upon clicking sending the request, so I'm not sure why AACAddition still thinks the inventory is open. The inventory closes properly in the Minecraft client.

What does AACAddition use to check if an inventory is open?

**Comment by MedicOP** [comment]
The duel request inventory I'm opening does have a custom name for each player by intercepting the OPEN_WINDOW packet using ProtocolLib and changing the title in the packet.

However, the Minecraft protocol only uses this string to display the window title, all the other inventory-related logic uses the Window ID instead.

May I know exactly what code is used to check if a player has an inventory open? Does it just the regular Bukkit API player.getOpenInventory() ?

**Comment by CeIebrimbor** [comment]
@Photon-GitHub

**Comment by Photon-GitHub** [comment]
It uses several methods to determine if someone has an open inventory, e.g. interactions, as well as the openinv event.

**Comment by Photon-GitHub** [comment]
Implemented some mechanics in 1.4.2.

**Comment by MedicOP** [comment]
Problem still seems to happening in 1.4.2.

**Comment by Photon-GitHub** [comment]
Then the InventoryClickEvent is causing your problems.
In this case you might hook into the api of my plugin.

**Comment by MedicOP** [comment]
Then I would have to edit multiple plugins not owned by me. They all have to hook into your API just to fix this bug? It's not just my plugin, there are hundreds of plugins that are all affected by this bug, including for example EchoPet.

Why not use my suggested fix:

Use InventoryClickEvent only for checking CRAFTING inventory. Use player.getOpenInventory().getType() != InventoryType.CRAFTING for all other inventories.

Or:

Use EventPriority.MONITOR for your InventoryClickEvent listener, and check if player.getOpenInventory() equals event.getInventory(), so you know whether the inventory is still open.

**Comment by Photon-GitHub** [comment]
Your suggestions are already implemented in 1.4.2.

**Comment by Mxngo** [comment]
Same!!!!

**Comment by Photon-GitHub** [comment]
Everything that was requested has been implemented, thus I will close this now.
