### ISSUE TITLE
onPacketReceiving exception

### ISSUE THREAD

**Issue by BestMark** [Photon-GitHub/AACAdditionPro#341]
AACAdditionPro 5.2.1
https://pastebin.com/4uYyaMh6

**Comment by Photon-GitHub** [comment]
First of all 4.2.1 is insanely outdated. Please update.
Secondly, you use ProtocolSupport which is explicitly listed as incompatible to AAC and might also have incompatibilities with AACAdditionPro. Both plugins only officially support ViaVersion as a Protocol hack.

**Comment by BestMark** [comment]
Sorry, I use 5.2.1 version
