### ISSUE TITLE
Inventory false positive

### ISSUE THREAD

**Issue by timr2000** [Photon-GitHub/AACAdditionPro#342]
Server version: Paper 1.13.2 637
AACAdditionPro version: 5.2.1
Plugin list: http://prntscr.com/oos3xg
Logs: https://pastebin.com/YkEEqHRf

Using Cele his optimized config.

**Comment by CeIebrimbor** [comment]
Steps to reproduce?

**Comment by leoncp9** [comment]
Disable Inventory , he is fully breaked

**Comment by leoncp9** [comment]
When i am on lobby and connect to other server, if i move inventory before teleport i get kikc for inventory for nothing
