### ISSUE TITLE
Skinblinker false positive

### ISSUE THREAD

**Issue by timr2000** [Photon-GitHub/AACAdditionPro#343]
Server version: Paper 1.13.2 637
AACAdditionPro version: 5.2.1
Plugin list: http://prntscr.com/oos3xg
Logs: https://pastebin.com/XKejcqLe

Using Cele his optimized config.

**Comment by CeIebrimbor** [comment]
Steps to reproduce?

**Comment by timr2000** [comment]
This happens when someone is using The Essentials /back. Using essentialsX

**Comment by timr2000** [comment]
You can close this, player had alot of lag
