### ISSUE TITLE
Invisibility cause by entity

### ISSUE THREAD

**Issue by leoncp9** [Photon-GitHub/AACAdditionPro#345]
Hello, my server is paper 1.12.2
i join with 1.8.8
When i join sometimes i can't see on tablist or on game other players
i have tryed to remove aacap and it is fixed
maybe the problem is entitykillaura :/
VIDEO:
Before and after with and without aacap plugin;
https://www.youtube.com/watch?v=URJJtfTdat8&feature=youtu.be

**Comment by Photon-GitHub** [comment]
Can you please disable KillauraEntity and see if the issue persists? After all, you should not really use KillauraEntity on production.

**Comment by leoncp9** [comment]
When i disalbe killaura entity i don't have this issue anymore
