### ISSUE TITLE
Performance issues 

### ISSUE THREAD

**Issue by runescapejon** [Photon-GitHub/AACAdditionPro#351]
There is a performance issue, I've also saved the web it's under the zip file..

![2c3b7d220fe386a95ca7be7b838a3819](https://user-images.githubusercontent.com/10858509/63993710-d0134980-cabf-11e9-9afd-20c671c45aa5.png)
[Lag-.zip](https://github.com/Photon-GitHub/AACAdditionPro/files/3558312/Lag-.zip)

EDIT: also here is the timings if it's help https://timings.aikar.co/?id=e38204ccd8ad4ae7aa09a18bd09b5a96

**Comment by Janmm14** [comment]
The ESP module IS performance heavy. If you have too many players online at some point no cpu can handle this - that is also a reason why in other games like csgo esp cheats still work too, because esp checking is not easy and generally a task why gpu's exist.

**Comment by runescapejon** [comment]
weird i am only using the optimize config made by Celebrimbor

**Comment by runescapejon** [comment]
Oops it seem the config i was using from Celebrimbor was one version down from the latest, nevertheless it's a mistake on my part and i will close this issue thank you.
