### ISSUE TITLE
KeepAlive FalsePositives

### ISSUE THREAD

**Issue by Pesticidus** [Photon-GitHub/AACAdditionPro#355]
Latest version AACAP
log: https://pastebin.com/Mkht0sXj

**Comment by vocan** [comment]
bump

**Comment by Puremin0rez** [comment]
This is definitely still an issue on 1.15.

Players will get kicked from just a few minutes of playing due to this.

Unfortunately the entire KeepAlive check must be disabled since it seems the "unregistered" check is not apart of any of the subparts that you can disable.

**Comment by untuned** [comment]
Still an issue for me, completely vanilla clients even get kicked.
