### ISSUE TITLE
Unhandled exception occured in onPacketSending(PacketEvent) for AACAdditionPro

### ISSUE THREAD

**Issue by leoncp9** [Photon-GitHub/AACAdditionPro#356]
log
https://pastebin.com/rKDmiVcS
server version paperspigot 1.14.4 latest build
protocolib for 1.14.4 build #18

**Comment by Leonardo-Fiori** [comment]
Happens also with the latest protocollib build.
Paperspigot 1.14.4
ViaVersion 2.2.1

**Comment by leoncp9** [comment]
nevert fix, don't ask  for refund, just collects the plugins :D

**Comment by leoncp9** [comment]
sei italiano?

**Comment by Leonardo-Fiori** [comment]
Yeah, i am from italy too!
I am getting a bit worried because i just bought this resource and it just does not work. Do they even test?

And i see that you reported this issue on 28 October.. still nothing? That's why i think that i should probably ask refund

**Comment by Photon-GitHub** [comment]
This is due to changes in the protocol of 1.14 as some packets have changed. 
Please disable DamageIndicator on 1.14 until I have fixed it.

**Comment by leoncp9** [comment]
done
