### ISSUE TITLE
 Unhandled exception occured in onPacketReceiving(PacketEvent) for AACAdditionPro

### ISSUE THREAD

**Issue by Leonardo-Fiori** [Photon-GitHub/AACAdditionPro#358]
Paper version 235 (1.14.4)
Via version 2.2.1
ProtocolLib 4.5.0 (latest dev build downlaoded yesterday)

Plugin unusable, errors in console, lagging a lot

[latest.log](https://github.com/Photon-GitHub/AACAdditionPro/files/3955731/latest.log)

**Comment by Photon-GitHub** [comment]
This is the move pattern of Inventory. Please disable until I update it.
