### ISSUE TITLE
/aacadditionpro = null

### ISSUE THREAD

**Issue by gorilletriton30** [Photon-GitHub/AACAdditionPro#361]
spigot version : spigot-1.8.8-R0.1-SNAPSHOT-latest.jar 

AACAdditionPro-6.0.0
ProtocolLib 4.4.0
AAC-4.3.4

https://pastebin.com/0EGp5iwH

**Comment by leoncp9** [comment]
https://pastebin.com/sPgcj8qY

**Comment by leoncp9** [comment]
Protocolib 4.5.0
https://www.spigotmc.org/resources/protocollib.1997/

**Comment by leoncp9** [comment]
server version paperspigot 1.15.1
