### ISSUE TITLE
Various Async Exceptions (PlayerAdditionViolationCommandEvent)

### ISSUE THREAD

**Issue by Puremin0rez** [Photon-GitHub/AACAdditionPro#363]
https://pastebin.com/4ET3EvUA
https://pastebin.com/hU49wezs

Seems to be the same as #357 but doesn't appear to be fixed.

Minecraft 1.15.1 running AAC 4.3.4, AACAdditionPro 6.0.0, ProtocolLib 4.5.0.

**Comment by Keviro** [comment]
I can confirm this on git-paper-33 (1.15.1)

https://pastebin.com/ytX9gsZ4

**Comment by Photon-GitHub** [comment]
Duplicate of #362
