### ISSUE TITLE
KeepAlive Async Issue (PlayerAdditionViolationCommandEvent)

### ISSUE THREAD

**Issue by Puremin0rez** [Photon-GitHub/AACAdditionPro#366]
Seems to still be a problem in 6.0.1.

https://pastebin.com/aCPFP7RF

Paper Minecraft 1.15.1 running AAC 4.3.4, AACAdditionPro 6.0.1, ProtocolLib 4.5.0.

**Comment by Keviro** [comment]
Jup, same here.

https://pastebin.com/vrywW5Es

**Comment by Photon-GitHub** [comment]
A missing negation. Should be fixed quite quickly.
