### ISSUE TITLE
"DamageIndicators" causing broken animations for living entities (1.15)

### ISSUE THREAD

**Issue by Puremin0rez** [Photon-GitHub/AACAdditionPro#367]
It appears that the way AACAdditionPro is spoofing the health in the "DamageIndicators" module affects 1.15 and it's ability to render entities movement.

If "DamageIndicators" is enabled, entities will lack all animation when moving around (most obviously, their leg movement). The client appears to dislike "NaN" as a health value in newer versions of Minecraft. (I think this is an issue in 1.14 too)

Players, and all other living entities alike will "slide" everywhere without showing any limb motion.

This is fairly easy to reproduce - just enable the module and observe living entities.

**Comment by Photon-GitHub** [comment]
I will just extend the villager handling (set to full health) for all other entities on newer versions.
