### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by FrankHeijden** [Photon-GitHub/AACAdditionPro#37]

**Comment by FrankHeijden** [comment]
I couldn't find the option at the pull request section to make a new post, im sorry ive put it in here.

Is it maybe possible to add the features of aacadditionpro in the aacadmin panel? And is it also possible to make permissions for each anticheat-section that would make it very useful for ranks/more compatible with other plugins that are using nonvanilla features :)

-Frank

**Comment by Photon-GitHub** [comment]
It is perfectly fine to post feature requests here.
(Thank you for being someone who actually read the line and came here for that.)
Sadly your request is not possible as aac's api does not provide functions to hook into the gui, therefore I would have to manipulate the inventory on packet level and this is not performant nor easy to do.
