### ISSUE TITLE
DamageIndicators Error - FieldAccessException (1.15)

### ISSUE THREAD

**Issue by Puremin0rez** [Photon-GitHub/AACAdditionPro#370]
https://pastebin.com/nhGYuck7

Seems to occur when players encounter each other.

Minecraft 1.15.1 running AAC 4.3.5, AACAdditionPro 6.0.3, ProtocolLib 4.5.0.

**Comment by Photon-GitHub** [comment]
Dang it, the protocol has probably changed regarding other players.

**Comment by Photon-GitHub** [comment]
Please check again, might be fixed on 6.0.4

**Comment by Puremin0rez** [comment]
Sorry for the late response - I get a ton of GitHub alerts a day and missed this.

Unfortunately, still seems to be an issue - new error:
https://pastebin.com/F3keNdVd

Tested on AACAdditionPro 6.0.4
