### ISSUE TITLE
[ignore this, im stupid] Sprinting + Holding left click false positive/ dropping server to 0.5

### ISSUE THREAD

**Issue by Insprill** [Photon-GitHub/AACAdditionPro#377]
### Issue description

If a player is sprint jumping and holding in left click, AAC started to kick/ ban them for move hacks, so i increase the tolerance a lot (30) and now if a player is sprint jumping and holding in left click for more then like 5 seconds it starts to lag the server, a lot. Once their doing it for like a minute the TPS drops to like 0.5-1.0 and and console is saying its running 650,000+ ms behind. Then once then once everything is that low and they keep doing it, it starts to mark them for Timings, and eventually kick/ ban them. The server is running on a Xeon X3220 with 7.5GB ram dedicated. And is literally using 100% CPU just pinned at 2.4GHz. I ran some timings and AAC was taking well over 400 ms per tick. I also tried it on a clone of the server but on a PC with 2x Xeon X5690's at 3.5GHz and 7.5GB ram. On there it only dropped the tps to about 13 after doing it for about a minute but it was using 30% CPU. I restarted the 1st server (with the X3220) and it was fine and as soon as my alt joined (one who was sprint jumping + holding in right click) the TPS went to 4 and CPU got pinned at 100%.
Update: I ran timings after i restarted the server and joined on my alt, here are the results: https://timings.aikar.co/?id=279ebbead35f4e829268c44b6f043b5d

**Here is the full timings report:** https://timings.aikar.co/?id=0cbf26e79e7a455facb74f3af15c69cb 
**Here is AACAdditionPro's latest log:** https://pastebin.com/RP6hWQH8
**Here is the servers latest log:** https://pastebin.com/TfEkekse (Although it only seems to have the 
last 2 minutes before i had to just end task it)
**Video of the TPS dropping when my alt joins:** https://youtu.be/tpFOa0bw38Q
**Random error that appeared in console:** https://pastebin.com/ZsJ25Ruj

**vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv**

**EDIT:** so i actually read the log and um yeah. i just disabled ESP and the issue went away.. so um yea. I set it to 10 and it did basically nothing so i just disabled it. (yes i restarted my server after i changed it)

**^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^**

**Note**: so apparently i can't read and it was AACAdditionPro not AAC so if some bits of this are from AAC ignore that lol

### Core information
**Server version**: 
Paper-95 1.15.2
**AACAdditionPro version**: 
6.0.4
**ProtocolLib version**: 
4.5.0
**Plugin list**: 
N/A
### Special environment information
**ViaVersion version**: ??
N/A
**ProtocolSupport version**: ??
N/A
**ViaBackwards version**: ??
N/A
**BungeeCord plugins**: ??
-BungeeMOTD
-BuycraftX
-CMIB1.0.0.0
-CommandSync-2.5.3-RELEASE
-nuvotifier

**Comment by Photon-GitHub** [comment]
Mostly some bug and/or error of ESP
