### ISSUE TITLE
[AACAdditionPro] Unhandled exception occured in onPacketReceiving(PacketEvent) for AACAdditionPro

### ISSUE THREAD

**Issue by Noahkemm** [Photon-GitHub/AACAdditionPro#385]
Full Error:
https://reporting.neruxvace.net/share/issue/85fff421cd4446c5ad8ed92f2b0ea22a/

Version:
AACAdditionPro 6.1.0
PaperSpigot 1.8.9

**Comment by Photon-GitHub** [comment]
Right now I think this could only happen with an incredibly unlucky logout.
Do you have any additional information or does this happen regularly?
