### ISSUE TITLE
False positive PacketAnalysis while attacking an entity

### ISSUE THREAD

**Issue by DanSeb2000** [Photon-GitHub/AACAdditionPro#388]
iSpigot 1.0.4b1
AACAdditionPro 6.1.0
AAC 4.3.7

When you attack and **right click** (blockhitting) an entity (mobs, players, etc) this appears:
![2020-03-21_17 11 56](https://user-images.githubusercontent.com/51137038/77235814-e980fd80-6b97-11ea-99e9-13a917b271a1.png)

**Comment by Janmm14** [comment]
Used client?

**Comment by DanSeb2000** [comment]
Optifine 1.8.9 HD-U-I3
I was testing for falses positives,

**Comment by Photon-GitHub** [comment]
Can you please record a video of the bug?
Does the bug also appear on a normal spigot/paperspigot?
The check is generally very sensitive to changes in the packet registering, therefore a custom fork might cause problems here.

**Comment by DanSeb2000** [comment]
Yes, here you got: https://www.youtube.com/watch?v=ODEK4gOJO7A
Like i said, that happen when you rclick and lclick at the same time.

I tested it on a normal Spigot ver1.8.8, same client like before Optifine 1.8.9

**Comment by Photon-GitHub** [comment]
Indeed the arm animation is not consistent on 1.8.8. The part will auto-disable on 1.8.8 in the future.
