### ISSUE TITLE
Scaffoldwalk bypass with LiquidBounce

### ISSUE THREAD

**Issue by MinecraftiUndCo** [Photon-GitHub/AACAdditionPro#39]
###Issue description

(On LPmitKev.de AAC-Testserver, Photon knows what I mean xD)

Scaffold walk with the LiquidBounce b20.2 without any sort of detection and no setbacks for unlimited distance possible.

* You can see our debug output in video (none xD) 
* https://www.youtube.com/watch?v=g9wBAiOKtiw&feature=youtu.be
* CyberTonix (hacking player)

###Core information
**Server version**: 1.8.9
**AAC version**: 3.0.5-b1
**AAC AdditionPro version**: 1.4.2
**AAC AdditionPro configuration part**: http://pastebin.com/C0ucmq4i
**ProtocolLib version**: #341 (V. 4.2.0)
**Plugin list**: AAC, AACAdditionPro, ProtocolLib, TestServerGui, GeiloCheat

**Hack client version**: LiquidBounce b20.2
**Hack type used**: Scaffold > Normal + AutoBlock

###Special environment information

**ViaVersion version**: none
**ProtocolSupport version**: none
**ViaBackwards version**: none
**BungeeCord plugins**: Our own plugins (should not affect aac in any way)

**Comment by Photon-GitHub** [comment]
Can you please record another video from outside (a spectator flying around the cheater)?

**Comment by MinecraftiUndCo** [comment]
Video from outside can be found here: **https://youtu.be/lWGyoiCJdDY**

**Comment by Photon-GitHub** [comment]
Should be fixed in 1.6
