### ISSUE TITLE
AACAdditionPro ate my server

### ISSUE THREAD

**Issue by SlimeDog** [Photon-GitHub/AACAdditionPro#390]
Spigot 1.15.2 (Jenkins 2650)
AACAddtionPro 6.1.0
Default config.yml

Two players on my test server, just standing still. AACAdditionPro consumed the CPU, TPS dropped through the floor. I disabled AACAddtionPro, and everything returned to normal. Here is the relevant [Spark trace](https://sparkprofiler.github.io/#CSffeubXTw). Please take a look, and let me know if there is something I can do to improve the situation.

**Comment by Photon-GitHub** [comment]
ESP is quite heavy and might have even worse performance on newer minecraft versions. Please disable ESP for now.

**Comment by SlimeDog** [comment]
Thanks. I'll give that a try.

**Comment by Photon-GitHub** [comment]
ESP has been optimized further in 6.3.1, but I think it still lacks the performance due to the changes of block accessing in minecraft :/
