### ISSUE TITLE
IMPORTANT! AACAdditionPro kicks ALL PLAYERS while combat

### ISSUE THREAD

**Issue by BestMark** [Photon-GitHub/AACAdditionPro#393]
AACAdditionPro kicks all players while combat.
Verbose: https://pastebin.com/QDs8rWCU
Video: https://youtu.be/uKuvBbvkQd8

**Server software:**
Paper 1.12.2
BungeeCord (latest)
ProtocolSupport

**Client software:**
Badlion Client 1.8.9

**Comment by Photon-GitHub** [comment]
Caused by incompatibility with ProtocolSupport. 
The PositionSpoof part will autodisable in the future when AACAdditonPro detects ProtocolSupport.
