### ISSUE TITLE
Bugged PacketAnalysis detection when connecting  to a 1.15.2 hub with a 1.8.9 client.

### ISSUE THREAD

**Issue by Ry4nw** [Photon-GitHub/AACAdditionPro#404]
I have issues with PacketAnalysis detection. When players join one of our 1.15.2 Servers with a Vanilla 1.8.9 client and they hit a player or NPC they get kicked for PacketAnalysis hacks. The threshold for kicks seems to be around hitting a player or NPC 4-8 times.

**Comment by Photon-GitHub** [comment]
I do not support ViaRewind or similar backwards Protocol hacks. I only support ViaVersion officially. Therefore, I will not fix this. Please disable PacketAnalysis for your server.
