### ISSUE TITLE
Suggestion for "Esp" Feature

### ISSUE THREAD

**Issue by Tomi010817** [Photon-GitHub/AACAdditionPro#407]
Hello! I've read the entire plugin description on Spigot, and I'm really amazed about the bunch of things that this plugin provides, I've already seen it working on big networks and I'm totally sure that this will be one of the firsts plugins that I will buy from the donations that I get from my server.
I just got stuck while reading at the check feature called "Esp", and got this idea that can be actually really dope for this plugin.  So currently this feature hides players and armors from Cheaters that uses "Tracers" or "NameEsp" with a fantastic method by using the "3rd person view" and all that, but what about making that feature, to also include Tile Entities? 
That could also prevent cheaters from watching Tile Entities such as chests, furnaces, enderchests, trappedchests, and much more. (and exempt Tile Entities that has a really high level of glow, since they can visually be buggy, to watch lights appear from nothing). 
And it could work either by turning the Tile Entities invisible when the player is in a position where he can't see it (don't know if it is already a thing, but be aware about transparent blocks when doing this, such as glass, iron_bars, barriers, etc), or use the method to transform the Tile Entity into a stone block in the same circunstance as the previous one. I would prefer the first option much more tho.
Thats pretty much it, I would be way very happy to get this suggestion accepted. Also I hope I can buy this plugin very soon, I want to test this on my server really bad x)
Cheers

EDIT: I've been reading other github issues, and realized that currently you are busy with the "Esp" feature since it is really heavy and causes TPS to drop. So I can imagine that including this feature would just make it much more heavy, so first lets hope you can make that feature smoother so then there is more chance about getting this one.

**Comment by Photon-GitHub** [comment]
I recommend a dedicated BlockObfuscator for chests and similar objects. The performance impact of raytracing is already way too high, especially on the latest minecraft versions which made direct block access much less performant. BlockObfuscation does have problems e.g. chests may be visible with ChestESP when they shouldn’t be, but the performance impact is much smaller than what I do here.

**Comment by Tomi010817** [comment]
I appreciate your recommendation, thanks a lot for replying Photon. I will use the ProximityHider feature from Orebfuscator for that I guess.
