### ISSUE TITLE
Scaffold false postitves

### ISSUE THREAD

**Issue by Pesticidus** [Photon-GitHub/AACAdditionPro#409]
This false positive is very easy to repeat. You need to set blocks along the wall.

First person video: https://youtu.be/m_udZZ2Yu68
Third person video: https://youtu.be/u3JP301WIRM
Log: https://pastebin.com/s8dfbWBm

AACAP ver: 6.3.0
Config: default
Server: Spigot 1.12.2
Plugins: AACAP, Protocollib, Essentials

**Comment by Photon-GitHub** [comment]
Thank you for the exemplary bug report :)
