### ISSUE TITLE
Mods and clients detections

### ISSUE THREAD

**Issue by RidaThe94** [Photon-GitHub/AACAdditionPro#415]
I would like to have a feature to detect more mods similar to hacked servers so for example it can check for some clients like fabric optifine badlion etc... and the ability to blacklist some forge mods. Also, a command to see what forge mods a player is using.

**Comment by Janmm14** [comment]
Badlion and Optifine should be undetectable.

**Comment by RidaThe94** [comment]
just the listing of the mods and mods blacklisting alone would be a cool feature
