### ISSUE TITLE
Console error: ConcurrentModificationException :O

### ISSUE THREAD

**Issue by MinecraftiUndCo** [Photon-GitHub/AACAdditionPro#42]
###Issue description

(On LPmitKev.de Mainserver, Photon knows what I mean xD)

Console error during operation

* http://pastebin.com/jw46pjH9

###Core information
**Server version**: 1.8.9
**AAC version**: 3.0.5-b1
**AAC AdditionPro version**: 1.4.2
**ProtocolLib version**: #341 (V. 4.2.0)
**Plugin list**: AAC, AACAdditionPro, ProtocolLib, GeiloCheat & more own game plugins (network api, etc.)

###Special environment information

**ViaVersion version**: none
**ProtocolSupport version**: none
**ViaBackwards version**: none
**BungeeCord plugins**: Our own plugins (should not affect aac in any way)

**Comment by Photon-GitHub** [comment]
Fixed in 1.5
