### ISSUE TITLE
Inventory Checks Not working properly | Plus a FP with inventory move

### ISSUE THREAD

**Issue by SnakeDaoust1232** [Photon-GitHub/AACAdditionPro#43]
The inventory checks aren't working right. As well, a FP with inventory move.

Video: https://www.youtube.com/watch?v=YTSNErV4lP8&feature=youtu.be

Core information

Server version: TacoSpigot 1.8 (Bug persists on either 1.7 client or 1.8 client)
AAC version: 3.1.0b1
AACAddition version: 1.5
ProtocolLib version: 4.2.0
Plugin list: https://gyazo.com/79111c31964e04b1631b0b36510e12ef

Special environment information

ViaVersion version: 1.0.4
ProtocolSupport version: 4.24
BungeeCord plugins: https://gyazo.com/1a3e07fc5194de5dfeb3ffdd9684457c

**Comment by Photon-GitHub** [comment]
Probably a bug in the new registering. Trying to sort this out asap.

**Comment by Photon-GitHub** [comment]
One missing exclamation mark caused both the false positives (they would occur on the other checks as well) and the malfunction of the checks 🙄

**Comment by Photon-GitHub** [comment]
Fixed in 1.5.1
