### ISSUE TITLE
ESP Error

### ISSUE THREAD

**Issue by W0lfyZRex** [Photon-GitHub/AACAdditionPro#430]
Server: Spigot-1.8.8

Plugins: Skript, Skript addons (9), WE, LuckPerms, Vault, ProtocolLib, AACAP, VulcanAC, TAB

The Anti-ESP check doesn't work at all because of the following error occurs when a non-bypassed player joins.
![image](https://user-images.githubusercontent.com/66094336/111042586-54c57e80-843e-11eb-8b10-5dfc26deff53.png)

**Comment by Photon-GitHub** [comment]
That error is basically saying that some players have no world that they exist in. Do you have any plugins that simulate players?

**Comment by W0lfyZRex** [comment]
No, I don't know if this is related but when someone joins he is put in spectator mode for a second or to to parse all items in his inventory and to delete his effects/variables etc.

**Comment by W0lfyZRex** [comment]
Exact list of plugins : 
![image](https://user-images.githubusercontent.com/66094336/111050848-52b7eb80-844f-11eb-88bc-0a97a83bfde1.png)
