### ISSUE TITLE
False Positives

### ISSUE THREAD

**Issue by KolakZ** [Photon-GitHub/AACAdditionPro#431]
A lot of players on my server including me keep getting kicked for cheats when they aren't even using any. The main ones that are detected as false positives are that a player has botlike eating behavior or they have suspicious inventory interactions. None of them do and it's really annoying. Could you make it so it only sends a message at high thresholds are disable it completely?

**Comment by Photon-GitHub** [comment]
Well, any notifications are customisable in the config of either AAC or AACAdditionPro. Could you please document the false positives so that they can be fixed?

**Comment by KolakZ** [comment]
Auto Eat & Botlike Inventory Interactions

**Comment by KolakZ** [comment]
I disabled it for now in config to avoid false positives but am hoping to see it fixed in the next update :)

**Comment by KolakZ** [comment]
It also kicks every single 1.8 player for suspicious packet behavior but they werent cheating

**Comment by Photon-GitHub** [comment]
Yes, in what situations do the false positives appear? 
At best please include a short video, or at least the log file with a description of what the players were doing.

**Comment by KolakZ** [comment]
they were just playing normally and it kept kicking them for velocity hacks and combat hacks

**Comment by taljafox** [comment]
I think I know why there is false positives because you didn't configure it properly

**Comment by KolakZ** [comment]
Couldn't find any configuration guide so I left it all on default

**Comment by KolakZ** [comment]
Plugin got recoded.
