### ISSUE TITLE
Conflicts with plugins

### ISSUE THREAD

**Issue by AZFire1** [Photon-GitHub/AACAdditionPro#437]
https://bin.bloom.host/ukokopehew

**Comment by Janmm14** [comment]
Its just spamming the console and shouldnt harm the server otherwise.

**Comment by AZFire1** [comment]
> 
> 
> Its just spamming the console and shouldnt harm the server otherwise.
> Solution will be for aacap to add a simple check to stop the spam.

yup, please add this, since it's impossible to look at the console rn.

**Comment by Photon-GitHub** [comment]
Should be fixed in 7.0.0. Please ping me if that should not be the case.
