### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Mxngo** [Photon-GitHub/AACAdditionPro#44]
27.03 20:13:14 [Server] INFO [+] MrBagelMC joined the server.
27.03 20:13:14 [Multicraft] MrBagelMC ran command Message of the Day
27.03 20:13:18 [Server] INFO ⎜ Member ⎜ Macaroni014 weba
27.03 20:13:21 [Server] INFO Macaroni014 issued server command: /home
27.03 20:13:22 [Disconnect] User MrBagelMC has disconnected, reason: Internal Exception: java.io.IOException: Connection reset by peer
27.03 20:13:22 [Server] INFO [-] MrBagelMC left the server.
27.03 20:13:22 [Server] ERROR Could not pass event ChunkUnloadEvent to AACAdditionPro v1.5
27.03 20:13:22 [Server] INFO org.bukkit.event.EventException
27.03 20:13:22 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.jar:git-Spigot-625bc00-d09304e]
27.03 20:13:22 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.jar:git-Spigot-625bc00-d09304e]
27.03 20:13:22 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.jar:git-Spigot-625bc00-d09304e]
27.03 20:13:22 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.jar:git-Spigot-625bc00-d09304e]
27.03 20:13:22 [Server] INFO at net.minecraft.server.v1_11_R1.ChunkProviderServer.unloadChunk(ChunkProviderServer.java:293) [spigot-1.11.jar:git-Spigot-625bc00-d09304e]
27.03 20:13:22 [Server] INFO at net.minecraft.server.v1_11_R1.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:268) [spigot-1.11.jar:git-Spigot-625bc00-d09304e]
27.03 20:13:22 [Server] INFO at net.minecraft.server.v1_11_R1.WorldServer.doTick(WorldServer.java:236) [spigot-1.11.jar:git-Spigot-625bc00-d09304e]
27.03 20:13:22 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:798) [spigot-1.11.jar:git-Spigot-625bc00-d09304e]
27.03 20:13:22 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.jar:git-Spigot-625bc00-d09304e]
27.03 20:13:22 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.jar:git-Spigot-625bc00-d09304e]
27.03 20:13:22 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.jar:git-Spigot-625bc00-d09304e]
27.03 20:13:22 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
27.03 20:13:22 [Server] INFO Caused by: java.util.ConcurrentModificationException
27.03 20:13:22 [Server] INFO at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437) ~[?:1.8.0_112]
27.03 20:13:22 [Server] INFO at java.util.HashMap$KeyIterator.next(HashMap.java:1461) ~[?:1.8.0_112]
27.03 20:13:22 [Server] INFO at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48) ~[spigot-1.11.jar:git-Spigot-625bc00-d09304e]
27.03 20:13:22 [Server] INFO at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48) ~[spigot-1.11.jar:git-Spigot-625bc00-d09304e]
27.03 20:13:22 [Server] INFO at de.photon.AACAdditionPro.f.f.b.a(Unknown Source) ~[?:?]
27.03 20:13:22 [Server] INFO at de.photon.AACAdditionPro.f.f.b.a(Unknown Source) ~[?:?]
27.03 20:13:22 [Server] INFO at de.photon.AACAdditionPro.f.f.c.a(Unknown Source) ~[?:?]
27.03 20:13:22 [Server] INFO at sun.reflect.GeneratedMethodAccessor57.invoke(Unknown Source) ~[?:?]
27.03 20:13:22 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
27.03 20:13:22 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
27.03 20:13:22 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.jar:git-Spigot-625bc00-d09304e]
27.03 20:13:22 [Server] INFO ... 11 more

**Comment by Photon-GitHub** [comment]
This can be fixed easily and will be fixed in 1.5.1.

**Comment by Photon-GitHub** [comment]
Fixed in 1.5.1
