### ISSUE TITLE
Hide enchantment details from other players

### ISSUE THREAD

**Issue by bigfinfrank** [Photon-GitHub/AACAdditionPro#447]
There are resource packs like [Visual Enchantments](https://curseforge.com/minecraft/texture-packs/visual-enchantments) that display what enchantments other players have on their armor. Would it be possible to prevent this? Potentially by always sending enchanted items with the same enchant, for example Infinity level 0 (as that would preserve armor and weapon enchant glint)?

**Comment by Janmm14** [comment]
Yes, thats possible

**Comment by Photon-GitHub** [comment]
Implemented in 7.3.0 as EnchantmentHider.
