### ISSUE TITLE
java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by KolakZ** [Photon-GitHub/AACAdditionPro#458]
I'm getting the following error on startup when using `AACAdditionPro 7.1.0`
https://bin.bloom.host/peveviyegu.csharp

**Comment by Janmm14** [comment]
Make sure you do the config changes the 7.1.0 update made to the default config

**Comment by Photon-GitHub** [comment]
Please read the error message, it will tell you that you need to update the config.
