### ISSUE TITLE
Unhandled exception occured in onPacketReceiving(PacketEvent)

### ISSUE THREAD

**Issue by KolakZ** [Photon-GitHub/AACAdditionPro#459]
I'm getting these two errors in console when using `AACAdditionPro 7.1.0` and typing `/kill`:
https://bin.bloom.host/rocuyugijo.properties

**Comment by Janmm14** [comment]
I have seen this exception occurring to multiple plugins so far, AACAP is definitely not a possible cause of this exception.

**Comment by Photon-GitHub** [comment]
As Jan said, most likely not from AACAdditionPro. I don't use zip files at all in my plugin.

**Comment by KolakZ** [comment]
It only happened when I updated to `AACAdditionPro 7.1.0`, when I reverted back to `AACAdditionPro 7.0.5`, I stopped getting these errors.

**Comment by KolakZ** [comment]
It got fixes when I regenerated the `config.yml`.

**Comment by KolakZ** [comment]
It got fixed when I regenerated the `config.yml`.
