### ISSUE TITLE
Inventory checks

### ISSUE THREAD

**Issue by Mxngo** [Photon-GitHub/AACAdditionPro#46]
**Huge false Inventory checks are kicking players please fix!** 

Plugins (60): AdvancedLogin, CustomOreGen, PlaceholderAPI, PlugMan, ChatReaction, OldCombatMechanics, DeluxeTags, AutoRestart, WorldEdit, ClearLag, ChatControl, ArmorEquipEvent, BuycraftX, MessageAnnouncer, Votifier, ProtocolLib, GuiRedeemMCMMO, eZProtector, MVdWPlaceholderAPI, PermissionsEx, FeatherBoard, mcMMO, ServerListPlus, Vault, ProtocolSupport, CustomCommands, QAPlugin, WorldGuard, AAC, ASkyBlock, ChatItem, PlayerVaults, Essentials, AnimatedNames, AACAdditionPro, LiteBans, SilkSpawners, Multiverse-Core, DeluxeChat, Citizens, CustomGUI, EssentialsChat, AuctionGUIPlus, SuperVanish, StackMob, ChestShop, NoFlyZone, HolographicDisplays, CoinFlip, CommandNPC, EssentialsSpawn, PvPManager, TitleManager, ShopGUIPlus, CrazyEnchantments, CrazyEnvoy, SpecializedCrates, ProVotes, LeaderHeads, ProQuests

**Comment by Photon-GitHub** [comment]
That issue is lacking lots of information. I won't be able to fix anything based on "there's a bug and here are my plugins"

**Comment by Photon-GitHub** [comment]
A quote of my discord-channel:
Even though I feel like I sent this text to lots of people and put this message at least 2 times into my Overview:

Report issues on the ISSUE TRACKER
https://github.com/Photon-GitHub/AACAdditionPro/issues

Your issue should also include the following information:
Server version
AAC version
AACAdditionPro version
Protocollib version
Logs of both AAC and AACAdditionPro
Error: Log of Server,
Error: Stacktrace
Bug: How to reproduce
Bug/Bypass: If possible provide a video
(Bypass: If possible obviously workings of the bypass / source code)
and other stuff that might be important to know, especially plugins that could affect the issue.(bearbeitet)

**Comment by Photon-GitHub** [comment]
As no further information has been provided, I close this now.
