### ISSUE TITLE
Inventory Falses

### ISSUE THREAD

**Issue by iFlamingoz** [Photon-GitHub/AACAdditionPro#465]
Video 1 (Moving/Jumping whilst having an open inventory):  https://youtu.be/yQ9uI6b-Cpg
Log  1: https://pastebin.com/DTh79ng8

Video 2 (New Rotations): https://youtu.be/YHdjrySi9GM
Log 2: https://pastebin.com/9hDptJ4s

Client Used: Badlion Client v3.2.2 1.8.9

Server Version: 1.8.8 (tested and working on paper 1.8.8)
AACAdditionPro ver: 7.1.0
Protocollib Ver: 4.6.0

Config: using Celebrimbor's Optimized AACAdditionpro Config.

**Comment by Photon-GitHub** [comment]
Given that rotations never got beyond vl 1 I guess I won’t fix that. The jumping one though I will fix.

**Comment by iFlamingoz** [comment]
Speed effects can also easily flag the inventory move flag.
https://streamable.com/ypfsiw
