### ISSUE TITLE
(2 Possible) Errors on player join (Sentinels)

### ISSUE THREAD

**Issue by iFlamingoz** [Photon-GitHub/AACAdditionPro#469]
- **Error 1:**
Error happens on player join with LabyMod 1.8.8 - 3.8.46
Error: https://pastebin.com/tcznanX6
This error can be fixed by changing Sentinel.AACFeatureScore to 1.

- **Error 2:**
Error happens on player join with the first error fixed.
Error: https://pastebin.com/esCM1rvR

Client Used: LabyMod 1.8.9 - 3.8.46

Server Version: 1.8.8 PaperSpigot
AACAdditionPro ver: 7.1.1
Protocollib Ver: 4.6.0

Config: Using default config + LabyModSentinel enabled

**Comment by Photon-GitHub** [comment]
Fixed in 7.1.2
