### ISSUE TITLE
Inventory Move FP | Urgent

### ISSUE THREAD

**Issue by SnakeDaoust1232** [Photon-GitHub/AACAdditionPro#47]
Info: There is more than just inventory move, but this is the only one ive been able to re-produce. It seems as if you click in your inventory a bunch, it false bans. But only sometimes, which means there is a certain circumstance that im not noticing. 

Video: https://www.youtube.com/watch?v=VL9UBK6HzPA&feature=youtu.be

Core information

Server version: TacoSpigot 1.8 (Bug persists on either 1.7 client or 1.8 client)
AAC version: 3.1.2
AACAdditionPro version: 1.5.1
ProtocolLib version: 4.2.0
Plugin list: https://gyazo.com/c17cf3dda13667a2bd5e5bb29c1b8271

Special environment information

ViaVersion version: 1.0.4
ProtocolSupport version: 4.24
BungeeCord plugins: https://gyazo.com/1a3e07fc5194de5dfeb3ffdd9684457c

**Comment by SnakeDaoust1232** [comment]
Related to @ https://github.com/Photon-GitHub/AACAdditionPro/issues/46?

**Comment by SnakeDaoust1232** [comment]
Just letting you know, there is a way to detect if someone has their inventory open right? It uses the achievement event "Use has opened their inventory for the first time".

Link: https://bukkit.org/threads/how-to-check-when-player-opens-his-inventory.321103/#post-2877820

**Comment by Photon-GitHub** [comment]
That cripples the complete achievement system and can annoy players, therefore I do not use it.

**Comment by SnakeDaoust1232** [comment]
I see, maybe you could make it an option since it seems like it would be more uesful then detecting if someone "clicks" in their inventory. I would use it for sure. As well, so would every other pvp server...only if it was more efficient, which i think it would be.

**Comment by Photon-GitHub** [comment]
It could easily be bypassed... the achievement could be ignored by the client. Thus I won't implement it, it is a one-line bypass...

**Comment by SnakeDaoust1232** [comment]
Ok, thats fine. Thanks for letting me know.

**Comment by Photon-GitHub** [comment]
Should be fixed in 1.6
