### ISSUE TITLE
false punish liteloder worlddownloader

### ISSUE THREAD

**Issue by leoncp9** [Photon-GitHub/AACAdditionPro#480]
my config
https://pastebin.com/fWzsR8UB
my video
https://www.youtube.com/watch?v=OAkyD4YGmcQ

description:
aacap think i use liteloader or wolrddownloader and i get punish
the server version is 1.17.1 paper
can you fix this problem?
the problem is not only for this version of minecraft...

**Comment by Janmm14** [comment]
you showed the wrong configuration section

**Comment by leoncp9** [comment]
yes i know, the problem is not the configuration, the problem is if i turn on the control for liteloader and worldownloader i get punish if i join with normal version of minecraft

**Comment by leoncp9** [comment]
https://pastebin.com/RUeWpkKH

**Comment by leoncp9** [comment]
also forge is not blocked .... :/
