### ISSUE TITLE
Scaffold False Positive

### ISSUE THREAD

**Issue by iFlamingoz** [Photon-GitHub/AACAdditionPro#482]
Jump = false?
Wall running: https://youtu.be/yj_lhbsm7J4
Trying to bridge up: https://youtu.be/BDT9trk1NOk

AACAdditionPro Version: 7.2

**Comment by Photon-GitHub** [comment]
Please add the scaffold logs as well.

**Comment by iFlamingoz** [comment]
https://pastebin.com/FCFSPdFd

**Comment by Photon-GitHub** [comment]
Should be fixed in 7.2.1
