### ISSUE TITLE
Moving player every second

### ISSUE THREAD

**Issue by sebastianbinder** [Photon-GitHub/AACAdditionPro#49]
Server version: `git-Paper-1075 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)`
Protocollib version: `4.2.1-SNAPSHOT-b347`
AACAdditionPro version: `1.5.1`

It seems like AACAdditionPro is moving/teleporting the player every second.
The video shows that the screen is kinda "moving". Then I'm switching to my second server, where I removed AACAdditionPro and it is gone. After switching back to first server (which obviously has AACAdditionPro installed) it appears again.

https://youtu.be/Y4KokumsdtY

**Comment by CeIebrimbor** [comment]
This is the Freecam check and an intended behavior.

When a player is stationary, AAC+ will move the player on the Y axis so their position is reset (if they are using Freecam). This is really the only way to block freecam hacks, so if annoyance trumps need to stop freecam, you can simply disable this one check.
