### ISSUE TITLE
Inventory Rotation Bug | Video

### ISSUE THREAD

**Issue by SnakeDaoust1232** [Photon-GitHub/AACAdditionPro#51]
Info: 
- Idk what exactly causes it, but it known to reach way over VL 15.

Video: https://www.youtube.com/watch?v=G47lEomQTO8&feature=youtu.be

Config: https://hastebin.com/kicivafemu.vbs

Core information

Server version: Paperspigot 1.8
AAC version: 3.1.3
AACAdditionPro Version: 1.6.1
ProtocolLib version: 4.2.0
Plugin list: https://gyazo.com/62230b456a22877a8803245f9132ccee

Special environment information

ViaVersion version: 1.0.4
ProtocolSupport version: 4.24
BungeeCord plugins: https://gyazo.com/b5d2b4e81fd8ee3a44b7472e9caf939d

**Comment by Photon-GitHub** [comment]
Can you please record a video with verbose?

**Comment by SnakeDaoust1232** [comment]
I could post the logs as well. I'll will get a video of the bug today.

**Comment by SnakeDaoust1232** [comment]
Logs: https://hastebin.com/alafesomag.rb

*I've been trying for 1 hour to reproduce and i cant. Its such a rare occurrence.*

**Comment by OWERLORD01** [comment]
I have got the same issue sometimes
But the vl climb only to VL 5 (7 is max)

**Comment by SnakeDaoust1232** [comment]
When the bug occurs. It flags the other inventory checks as well. Someone got it up to 300+ earlier. Whenever the bug happends, if you do not update your inventory, it will just keep climbing.

**Comment by Photon-GitHub** [comment]
That is normal for my inventory checks as they use the same data. I need the situation in which this fp occurs.

**Comment by SnakeDaoust1232** [comment]
I was forced to disable all the inventory checks due to this bug. Its causing people to get false banned for all of them. Had 20 people false banned today.

**Comment by Photon-GitHub** [comment]
That wont't help me fix the problem, I need a real situation that is reproducable to fix this...

**Comment by CeIebrimbor** [comment]
1.8.8 server w/ ViaVersion

Connect with a 1.11 client and click around while moving. That got me to VL 20+ no problem.

**Comment by Janmm14** [comment]
could this be beacon-related?

**Comment by Hyronymos** [comment]
Snake, do you use/have a bungeecord?

**Comment by CeIebrimbor** [comment]
Yes he does @Hyronymos 

This seems tied to Bungee

**Comment by Photon-GitHub** [comment]
Close due to inactivity. Please comment to reopen.
