### ISSUE TITLE
Heuristic Addition | Bug?

### ISSUE THREAD

**Issue by OWERLORD01** [Photon-GitHub/AACAdditionPro#52]
## Description
Hey, heuristic addition is not working for me..
I have just enabled it and when heuristic detects me its counting lvs like 2 4 8 10 (counting vls forever, its not stopping) and its not executing my commands from AACAdditionPro... 

## Errors?
There is no errors in console

## Configs
My AAC (latest) Config:
https://hastebin.com/yowuxuyowo.bash

My AACAdditionPro (latest) config:
https://hastebin.com/olikepazup.bash

## Thanks
I don't know what am i doing wrong... Please help me or if it's bug, please fix it!
Thanks ~OpenSource

**Comment by OWERLORD01** [comment]
Note: I have tried putting `thresholds: {}` by request from @Janmm14 

> @OpenSource try putting thresholds: {} for heuristics in aac config

**Comment by Photon-GitHub** [comment]
Can you please post all three here when my addon is not detecting it:
- AAC log
- AACAdditionPro log
- Server log

**Comment by OWERLORD01** [comment]
>Can you please post all three here when my addon is not detecting it:
>
>AAC log
>AACAdditionPro log
>Server log

Server log + AACLog (Console verbose is enabled) - https://hastebin.com/epirumamug.md
AACAdditionPro log - https://hastebin.com/osubulomag.rb

**Comment by Photon-GitHub** [comment]
I will look into it.

**Comment by Photon-GitHub** [comment]
I recently recoded some of my addition structure and it seems like I forgot to register the Heuristics-Addition again. This is fixed in the next update.

**Comment by Photon-GitHub** [comment]
Fixed in 1.7
