### ISSUE TITLE
Stack Trace

### ISSUE THREAD

**Issue by SnakeDaoust1232** [Photon-GitHub/AACAdditionPro#54]
Stack Trace: https://hastebin.com/qatohahugo.lua

Core information

Server version: Paperspigot 1.8
AAC version: 3.1.3
AACAdditionPro Version: 1.7.1
ProtocolLib version: 4.2.0
Plugin list: https://gyazo.com/62230b456a22877a8803245f9132ccee

Special environment information

ViaVersion version: 1.0.4
ProtocolSupport version: 4.24
BungeeCord plugins: https://gyazo.com/b5d2b4e81fd8ee3a44b7472e9caf939d

**Comment by Photon-GitHub** [comment]
Should be fixed in 1.7.3
