### ISSUE TITLE
Anti-Xray

### ISSUE THREAD

**Issue by SnakeDaoust1232** [Photon-GitHub/AACAdditionPro#58]
Since spigots anti-xray isn't configurable enough... the only other option is orebfuscator. Orebfuscator only supports like 1.10 and above and it has a really good anti-xray feature that AACAdditionPro should pick up. The proximity hider. Essentially, if you arent within a certain distance from a block/ore, it will change the block/ore to something else. I used to have it set like this. If you arent within 15 blocks of diamond ore, iron ore, etc, etc, then change the diamond ore, iron ore, etc, etc to air. Xray mods cant work properly if every ore at least 15 blocks away from you are changed to air.

**Comment by Photon-GitHub** [comment]
Orebfuscator is a good plugin and the older versions work perfectly well. It would be a lot of work to accomplish something that is similar to orebfuscator.

**Comment by SnakeDaoust1232** [comment]
No they dont but ok i guess.
