### ISSUE TITLE
Inventory-checks bug

### ISSUE THREAD

**Issue by FrankHeijden** [Photon-GitHub/AACAdditionPro#61]
Heya,

When an other player pushes another player on my server he will get kicked for inventorymove when he's crafting a tool or something else in his inventory. Is there a fix for this?

Frank

**Comment by CeIebrimbor** [comment]
It is assumed you have the latest AAC and AACaddition...but please confirm.

**Comment by FrankHeijden** [comment]
Yes. AACAdditionPro 1.8.2 and AAC 3.1.5-b3

**Comment by CeIebrimbor** [comment]
I think @Photon-GitHub may have gone to sleep for the day (Germany), but good to give as much info as possible.

**Comment by FrankHeijden** [comment]
Ah yes that's possible. Im from the netherlands :P 00:04 here. But there's not much info i could give about this, only that when you push a player AACAdditionPro will detect it as InventoryMove/InventoryRotation etc.

**Comment by Janmm14** [comment]
Uhm it shouldn't detect inventoryrotation

**Comment by FrankHeijden** [comment]
It did :P but there's aslo a bugg when a player is opening a chest before he actually stands still -- then he will also be checked.

**Comment by SnakeDaoust1232** [comment]
Its prolly related to my bug. For some reason, the plugin is thinking we are in our inventories when we are not.

**Comment by Photon-GitHub** [comment]
Should be fixed in 1.9
