### ISSUE TITLE
Inventory Tracker | Feature

### ISSUE THREAD

**Issue by SnakeDaoust1232** [Photon-GitHub/AACAdditionPro#63]
Maybe some better way of tracking if an inventory is open or not. Also, maybe forcing the inventory closed after certain conditions. This would fix the inventory bugs that are still out there. 

- Only reason i bring this up is because im still waiting for the inventory bugs to be fixed. :(

**Comment by Photon-GitHub** [comment]
As long as I don't have ideas for the "certain conditions" or the "better tracking" I cannot do anything.

**Comment by SnakeDaoust1232** [comment]
Well, as you know. There are rare instances where the plugin thinks that the player has their inventory open when its not actually open. Maybe AACAddition Pro could hook the inventory event and handle it better than vanilla minecraft, to make sure that inventory is never open when it shouldnt be.

**Comment by Janmm14** [comment]
any plugins which close the inventory for a player?

**Comment by SnakeDaoust1232** [comment]
@Janmm14 No sir

**Comment by SnakeDaoust1232** [comment]
@photon Maybe instead of cancelling the "movement" when these violation happen, just "refresh" the inventory. Open it, update it, and close it, really fast, using code. This way, if someone isn't using an inventory hack, and they reach a certain violation level, it "refreshes" the inventory to make sure it's not glitched. Someone using an inventory hack, will continue to flag over and over after the inventory is being refreshed, confirming they are actually cheating. I think this should be done for all inventory checks(including rotation), since there are ways to glitch the inventories but we can't reproduce them easily.

**Comment by SnakeDaoust1232** [comment]
?? :(

**Comment by SnakeDaoust1232** [comment]
I gotta disable the plugin until the inventory check system is looked into. To many people getting falsebanned yet its hard to reproduce the falseban.

**Comment by Photon-GitHub** [comment]
No solutions were pointed out that are realizable without negative side effects.
