### ISSUE TITLE
Mod Checker | Feature

### ISSUE THREAD

**Issue by SnakeDaoust1232** [Photon-GitHub/AACAdditionPro#64]
Maybe instead of running commands if a mod is detected, we could use a command like /modcheck {player} and it would return a list of all the mods that that player is using.

**Comment by CeIebrimbor** [comment]
You can run any command you want on the mods that can actually be directly detected(Forge and WDL), so I don't think it makes sense for AAC+ to do what a simple plugin could do on the side. What's the point of collecting that info? Just use aacstaffnotify if you don't want to kick. There are a few mods that cannot be directly identified (like schematica and LabyMod), so this would only apply to a few of them anyway.

**Comment by Photon-GitHub** [comment]
Most mods cannot be detected, apart from those which have an API allowing the detection. Otherwise it would be easy to detect client modifications... just blacklist the hacked clients...
I will close this as it is unachievable.
