### ISSUE TITLE
[AACAdditionPro] Task #99 Some Error?

### ISSUE THREAD

**Issue by DesignerHD** [Photon-GitHub/AACAdditionPro#65]
Hello,

I have notice that my players has been being pulled back a little when running or pulled back when mining blocks this is what I have as an error?

[AACAdditionPro] Task #99 for AACAdditionPro v1.8.2 generated an exception
java.lang.NullPointerException

Anyway of getting this fixed?

Thanks,

-CC
DesignerHD

**Comment by CeIebrimbor** [comment]
Could you provide your server version, AAC version and protocollib version?

**Comment by DesignerHD** [comment]
AAC: 1.9.10
Protocollib: 4.2.0

**Comment by CeIebrimbor** [comment]
Latest AACaddition is only able to start with AAC 3.1.4+, so you likely have an obsolete AACaddition too. v1.9.10 of AAC is now 5 months obsolete and not supported.

Request reopen if you update to 3.1.5-b3 of AAC and the issues still occur.

**Comment by DesignerHD** [comment]
I know you closed this but the lastest update for AAC don't work on 1.8.8 so really I wasted my money yes?

**Comment by CeIebrimbor** [comment]
The lastest version (3.1.5-b3) supports 1.8.8, 1.9.2/4, 1.10.x and 1.11.x

Please read the overview: https://www.spigotmc.org/resources/aac-advanced-anti-cheat-hack-kill-aura-blocker.6442/
