### ISSUE TITLE
[AACAdditionPro] Task #98 for AACAdditionPro v1.8.2 and another error?

### ISSUE THREAD

**Issue by DesignerHD** [Photon-GitHub/AACAdditionPro#66]
Hello,

I have updated all my plugins for the AAC and AACAdditionPro to work but I noticed 2 or more problems.

AAC Version: 3.1.5-b3
AACAdditionPro Version: 1.8.2
Protocollib Version: Latest

Error: https://pastebin.com/rsXe1dF2

Any clue?

**Comment by CeIebrimbor** [comment]
Odd...

Can you see if v4.2.0 of ProtocolLib cases the same?

http://ci.dmulloy2.net/job/ProtocolLib/341/

**Comment by DesignerHD** [comment]
Hello,

Looks like that may have fixed the issue I haven't had anything come up in console,

I'll keep my eye out if it does it again and ill report it again.

Would you prefer me to report it on this ticket? or a new?

**Comment by CeIebrimbor** [comment]
You can report here and the issue can be reopened if needed. Thank you for active retesting and feedback.

@Photon-GitHub I think something is amiss in ProtocolLib 4.2.1 for 1.8-1.10 servers. Most issues are resolved by jumping back to 4.2.0. Thoughts?

**Comment by DesignerHD** [comment]
Hello,

I am sort of in a rush as I need to get to work (I will respond but it It will probably be slowly.) But I have an error just like the one before, except its task #90.

This happened when I Placed hoppers on the back of my chests at my cactus farm.

Here is the error log.

https://pastebin.com/Vzi9mWFc

**Comment by Photon-GitHub** [comment]
Problem of the current ESP check with the new Packetwrappers.

**Comment by Photon-GitHub** [comment]
Should be fixed in 1.9
