### ISSUE TITLE
Gamemode 3 and AACAdditionPro

### ISSUE THREAD

**Issue by Metisuneatn** [Photon-GitHub/AACAdditionPro#67]
Finally writing it on github! 
1.11.2 - Latest version

So when in spectate it USED TO flicker from the following: (when watching players)
The players would:
-lose their armor showing their skin
-be breaking blocks and doing things with nothing in their hand (while stuff is clearly in their hands)
-vanish fully

We would need to go in and out of walls to get them to come back. 

Now currently:
-It is not flickering in and out, now we cannot see armor period
-Also cannot not see anything in their hands now
-They still flicker in vanish and can come back if you go through the walls.

**Comment by Metisuneatn** [comment]
Update: So err.. all players can see this happen, and we also are no longer in spectate and can see this happen.

**Comment by Janmm14** [comment]
Disable esp check will hotfix this for you, would be great if you can maybe get some more details why it does flicker also in survival mode.

**Comment by Metisuneatn** [comment]
Apologies, was in a hurry. Players said they noticed other players vanishing in survival. They also state they can see players gear vanish, showing their entire skin. It like "flashes" according to them. We do have some minigames and it is the most noticeable in them. Few feel it is distance related or when they first teleport to another player, but I dont have enough to really track what causes it. 

Now for gm3, it used to flicker in and out if you messed around by going in and out of walls or just by waiting, now it just stays constant. I need to go into creative to see them. When I am in creative I do not have the problem at all.

**Comment by Photon-GitHub** [comment]
Should be fixed in 1.9
