### ISSUE TITLE
Error: https://hastebin.com/ehifurigaj.css

### ISSUE THREAD

**Issue by Felix5566** [Photon-GitHub/AACAdditionPro#68]
Please fix the consol spam: https://hastebin.com/ehifurigaj.css

Version:
Server: Spigot 1.8.8
AAC: 3.1.5
AACAdditionPro: 1.8.2
ProtocolLob: 4.2.1

**Comment by Janmm14** [comment]
Please go to the start of your log file, there the full error can be seen

**Comment by Felix5566** [comment]
this is the full error

**Comment by Janmm14** [comment]
No, because java removes useful information if an execption occurrs often to reduce computing time.

**Comment by Felix5566** [comment]
sorry, yes: https://hastebin.com/afonexocol.css

**Comment by Photon-GitHub** [comment]
Duplicate of #66
