### ISSUE TITLE
Plugin Start Up Error

### ISSUE THREAD

**Issue by Felix5566** [Photon-GitHub/AACAdditionPro#70]
https://hastebin.com/oxufedevoj.css

Versions:
AAC: 3.1.6 (latest)
AACAdditionPro: 1.9 (latest)
ProtocolLib: 4.2.0
Server: 1.8.8

The ERROR is still in the Console: https://hastebin.com/umeratoham.css

**Comment by CeIebrimbor** [comment]
Oops...

Downgrade to the known stable 1.8.2

**Comment by Felix5566** [comment]
the secons ERROR is also in 1.8.2

**Comment by CeIebrimbor** [comment]
What about?
AAC v3.1.5-b3 and AACaddition v1.8.2

**Comment by Felix5566** [comment]
why AAC v3.1.5-b3 sooo old from Apr 16, 2017.

No
Update please

**Comment by CeIebrimbor** [comment]
I only bother mentioning since 3.1.5-b3 is still the recommended stable build (most servers run). I am not suggesting that as the permanent fix, just trying to help you out while the AAC+ developer is asleep.

**Comment by Felix5566** [comment]
I also need sleep

Please Fix it! The First and Second Error
thanks
good night

**Comment by Felix5566** [comment]
the fist error is onley when the folder has been creadet.

**Comment by Photon-GitHub** [comment]
The second error is probably caused as of your old ProtocolLib version. Please update to latest.
The first error does not affect functionality and can safely be ignored until it is fixed.

**Comment by Felix5566** [comment]
AAC say: 

Correct. 4.2.0

4.2.1 has been known to cause issues with 1.8 servers. Even though ProtocolLib advertises to be cross-version compatible. It is something AAC needs to work on (why I still labeled with "Error"), but I just wanted to see if reverting to 4.2.0 would remedy the error.

**Comment by Felix5566** [comment]
Error Update: https://hastebin.com/rovalejumu.vbs

**Comment by Photon-GitHub** [comment]
Should be fixed in 1.9.1
