### ISSUE TITLE
Jumping and running is detected as fly after updating to latest AAcAdditionPro

### ISSUE THREAD

**Issue by Fonzee9** [Photon-GitHub/AACAdditionPro#71]
I will have to downgrade for now because of that problem.

**Comment by Photon-GitHub** [comment]
No logs, no video, nothing?

**Comment by Fonzee9** [comment]
Okay the problem is somehow with logs being enabled as its fine with it enabled but i normally disable it.

 # Do you want AACAdditionPro to log into a log-file
   file: false

Disable that in your config and run and sprint and it will detect you as fly.

**Comment by Fonzee9** [comment]
With AACAdditonPro disabled AAC works great but with AACAdditonPro AAC has this fly error:

Log: https://pastebin.com/m93fLYkc

**Comment by Photon-GitHub** [comment]
Logs, not just one log...
Please post your server log and both the full AAC and AACAdditionPro log.

**Comment by Fonzee9** [comment]
Thats the best information AACAdditionPro had no logs only AAC. I suggest you test it out yourself.

**Comment by Photon-GitHub** [comment]
Problem of AAC.

**Comment by Fonzee9** [comment]
This isn't a problem with aac proof: https://github.com/konsolas/AAC-Issues/issues/648

Someone said: I made a issue that looks similar. If not, remove aacadditionpro.. For some reasons the plugins aren't meshing properly.

**Comment by Janmm14** [comment]
There are apparantly multiple underlying issues causing random fly violations as far as I got it now.
