### ISSUE TITLE
Heuristics Api Event not working in new versions

### ISSUE THREAD

**Issue by MinecraftiUndCo** [Photon-GitHub/AACAdditionPro#73]
###Issue description

(On LPmitKev.de Testserver, Photon knows what I mean xD)

Since update of AAC to new Heuristic system, the Heuristics Api Event is not called at all even when fighting with a blatant killaura 

###Core information
**Server version**: 1.8.9
**AAC version**: 3.1.6-b2
**AAC AdditionPro version**: 1.9.1
**ProtocolLib version**: V. 4.2.1
**Plugin list**: AAC, AACAdditionPro, ProtocolLib, GeiloCheat & more own game plugins (network api, etc.)

###Special environment information

**ViaVersion version**: none
**ProtocolSupport version**: none
**ViaBackwards version**: none
**BungeeCord plugins**: Our own plugins (should not affect aac in any way)

**Comment by Photon-GitHub** [comment]
Konsolas is currently a bit busy and I think I should talk to him when it comes to this topic, therefore I pause this issue til everyone has time again.

**Comment by Photon-GitHub** [comment]
Should be fixed in 1.9.3
