### ISSUE TITLE
Nullpointer during operation

### ISSUE THREAD

**Issue by MinecraftiUndCo** [Photon-GitHub/AACAdditionPro#74]
###Issue description

(On LPmitKev.de Testserver, Photon knows what I mean xD)

Nullpointer in Task 30:

**https://pastebin.com/J4dX0Kad**

###Core information
**Server version**: 1.8.9
**AAC version**: 3.1.6-b2
**AAC AdditionPro version**: 1.9.1
**ProtocolLib version**: V. 4.2.1
**Plugin list**: AAC, AACAdditionPro, ProtocolLib, GeiloCheat & more own game plugins (network api, etc.)

###Special environment information

**ViaVersion version**: none
**ProtocolSupport version**: none
**ViaBackwards version**: none
**BungeeCord plugins**: Our own plugins (should not affect aac in any way)

**Comment by Photon-GitHub** [comment]
Should be fixed in 1.9.2

**Comment by Photon-GitHub** [comment]
Fixed in 1.9.3 as the information-hider is no longer available for 1.8 servers.
