### ISSUE TITLE
FreeCam bug

### ISSUE THREAD

**Issue by OWERLORD01** [Photon-GitHub/AACAdditionPro#77]
## Bug Description
When someone is not walking, and not doing anything, every chunk around him disappears.... It looks like this... http://prnt.sc/f5gk7e

## Core Info
AAC: Latest
AACAdditionPro 1.9
ProtocolLib: one of the latest dev builds

### Thanks!

**Comment by Photon-GitHub** [comment]
Several problems here:
1) Please update to 1.9.1
2) Server version? Server logs? 
3) Freecam only tps a user, why should chunks disappear on a tp to the position a player is currently standing? 
4) As of 3) are you sure that no other plugin modifies chunk loading and Freecam is the sole issue ?

**Comment by SnakeDaoust1232** [comment]
Are you sure that this is not just your video settings? Try changing your chunk loading settings from multicore to default or smooth.

**Comment by OWERLORD01** [comment]
>Several problems here:
Please update to 1.9.1
Server version? Server logs?
Freecam only tps a user, why should chunks disappear on a tp to the position a player is currently standing?
As of 3) are you sure that no other plugin modifies chunk loading and Freecam is the sole issue ?

Around 30/100 players have the same issue...
I'll update it and i'll record a video on it...

My plugins are: AAC, AAC+, Advanced Portals, AuthMe Reloaded, AutoBroadcast, Ban Animations & BanWave, BlockHub, CoreProtect, ChatControlPro, CoinFlipp, ConsoleInGame, CorditionalCommands, DeluxeChat, EssentialsX (+Spawn, Protect and else), FactionsMobs, Factions, FastAsyncWorldEdit, FeatherBoard, HeadDatabase, HolographicDisplays, iDisguise, JoinMessagePlus, LuckPerms, MassiveCore, mcMMO, nuvotifier, superbvotes, stopproxy, TrollBoss, BungeeTabListBringe, Vault, WorldEdit, WorldGuard, Smileys, StripArmour and AuthMeBringe

**Comment by Photon-GitHub** [comment]
As no additional information has been provided I will close this now.

**Comment by OWERLORD01** [comment]
Other users are having the same problem too
https://github.com/konsolas/AAC-Issues/issues/683

**Comment by OWERLORD01** [comment]
Look at the post #5 by Piggy
https://www.ecocitycraft.com/forum/threads/loading-bug.166174/
Its the same image as mine

**Comment by andrewkm** [comment]
@photon very many of our users have these same issues. This is clearly a problem with AACAddition Pro.

**Comment by OWERLORD01** [comment]
@Photon-GitHub you should probably reopen this issue...

**Comment by andrewkm** [comment]
@OWERLORD01 I was told we should just disable freecam check to prevent this from happening.

**Comment by OWERLORD01** [comment]
@andrewkm I know, but when I buy something, i expect it to work..

**Comment by andrewkm** [comment]
@OWERLORD01 I know I do too. :(

**Comment by OWERLORD01** [comment]
@andrewkm if he keeps ignoring me, i'll give him a nice review :) U should do it too

**Comment by SnakeDaoust1232** [comment]
Threatening someone is not the way to get their attention. Really immature.

**Comment by andrewkm** [comment]
Threatening bad reviews is not the way to go. We need to help the developer fix the issue instead.

**Comment by OWERLORD01** [comment]
> Threatening bad reviews is not the way to go. We need to help the developer fix the issue instead.

How can I help him with it while he's ignoring me?

**Comment by Photon-GitHub** [comment]
If one want that I do not ignore issues he should answer all the questions I ask him. As long as I don't have all the information I need I cannot work. I have asked you to tell me your server version, give me logs and you promised me a video. I have recieved nothing of that list yet. If you cannot even provide this basic information I cannot do anything for you.

**Comment by CeIebrimbor** [comment]
@andrewkm @OWERLORD01 
This was reopened, not because of the threats of review, but because I wanted Photon to look into this deeper. He will this weekend after his exams, **IF** the requested info/evidence is provided.

**Comment by andrewkm** [comment]
I would just like to add that I just received confirmation regarding freecam. Disabling the freecam check does not fix this issue. It continued to persist. I am now testing without the use of AACAddition Pro.

**Comment by OWERLORD01** [comment]
@andrewkm for me, its working, i'll record a vid soon, sorry @Photon-GitHub :(
I dont have any console errors, and what logs do u want? Freecam is not logging anything.

**Comment by andrewkm** [comment]
Would like to report that removing the plugin AACAddition Pro has solved all our freecam/screen glitching issues.

Linking this in reference: https://github.com/konsolas/AAC-Issues/issues/683 (From AAC issues, however now closed as determined to be an AACAddition Pro problem).

**Comment by Photon-GitHub** [comment]
Full server log @OWERLORD01

**Comment by SnakeDaoust1232** [comment]
I just started having this issue. Im confused.

**Comment by Photon-GitHub** [comment]
Fixed in 3.0.1 with the new config option
