### ISSUE TITLE
Freecam Teleport FPs 

### ISSUE THREAD

**Issue by SnakeDaoust1232** [Photon-GitHub/AACAdditionPro#82]
Info: 
- This only happens on 1.7 clients. Please take a look into it if its an easy compatibility fix :(

Video: https://www.youtube.com/watch?v=sDCVkYltkTQ&feature=youtu.be

Core information

Server version: Paperspigot 1.8.8
AAC version: 3.1.6b4
AACAdditionPro Version: 1.9.2
ProtocolLib version: 4.2.1
Plugin list: (Upon request)

Special environment information

ViaVersion version: 1.0.4
ProtocolSupport version: 4.24
BungeeCord plugins: (Upon request)

**Comment by Photon-GitHub** [comment]
Sadly it is not some easy compatibility fix. The protocol of 1.7 is different from 1.8 in a lot of ways and there is a reason that we don't support 1.7...

**Comment by Photon-GitHub** [comment]
Apart from the fact mentioned above I also doubt that I could fix this in my plugin. I rather think that konsolas is your man there.

**Comment by SnakeDaoust1232** [comment]
I understand. Thanks anyways

**Comment by Janmm14** [comment]
Maybe it might be a possibility to disable / changing how the freecam check and the pingspoof check work for players with not supoorted clients

**Comment by SnakeDaoust1232** [comment]
I was hoping but it doesn't sound like it. Ill just have to disable the freecam check and install another plugin that is compatible.
