### ISSUE TITLE
feature request to block / limit sound distances similar to NCP

### ISSUE THREAD

**Issue by zetglob** [Photon-GitHub/AACAdditionPro#83]
could https://github.com/NoCheatPlus/Docs/wiki/%5BNet%5D-Sounddistance be added to AACAdditionPro?

**Comment by Photon-GitHub** [comment]
It is pretty much useless, the only information you can get from such a modification is "A wither/enderdragon/lightning bolt appeared, thus there must be a player somewhere near this location". As most servers do not have a long entity-visibility and you can only estimate a players location with an accuracy of about 50 blocks this mod is practically useless. Apart from this the module is yet to be coded in a modern client.

**Comment by zetglob** [comment]
it is actually much bigger than that. there are even public clients that have a simple thunder sound grabber and players can easily use the sounds to triangulate other players and get very accurate co-ordinates even hundreds thousands of blocks away. i get that survival pvp servers aren't that many these days but there are still a few around that would benefit from this option. having this feature be added is a big incentive for me to get aacadition

**Comment by Janmm14** [comment]
I die not see any client wirh such a module yet; if you think its important you can use NCP for blocking that.

**Comment by zetglob** [comment]
I am currently using NCP just to block this literal only thing with it, but it would be nice to completely disable NCP, also some features of NCP aren't possible to turn off. It ends up using unnecessary cpu.

The feature was popular in clients from previous times when there were many more pvp survival servers than there are these days, but it is still very relevant in custom or private clients and programmers can easily create a small mod specifically just to abuse how the thunder sound works. I thought it would be a very nice feature considering every other type of feature AACaddition adds. It should be easy to add as NCP has source on github.
