### ISSUE TITLE
PlayerViolationEvent error with Heuristics-Addtions

### ISSUE THREAD

**Issue by Hyronymos** [Photon-GitHub/AACAdditionPro#84]
Latest AAC (3.1.6-B5) & AACAddtions (1.9.2) Version

(I use the AAC & AACAddtions config from Celebrimbor)

Server-Version: 1.8.8

Protocollib Version: 4.1.0

LOG: https://hastebin.com/xucenineda.md

**Comment by Photon-GitHub** [comment]
Should be fixed with 1.9.3
