### ISSUE TITLE
Unhandled exception occured in onPacketSending(PacketEvent)

### ISSUE THREAD

**Issue by andrewkm** [Photon-GitHub/AACAdditionPro#85]
### Issue description

Continuous console spam with the following error:
https://gist.githubusercontent.com/andrewkm/c095e2f73151bfca6c20c82d13a452ff/raw/3095d880b4f2d938c5b482b97d667f0334d412c8/gistfile1.txt

### Core information
**Server version**: 1.11.2 - Spigot Build 1251

**AAC version**: 3.1.6-b5

**AACAddition Pro version**: 1.9.3

**ProtocolLib version**: 4.2.1 Build 354

**Plugin list**: (on request via Discord - andrewkm-1759)

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by Photon-GitHub** [comment]
Should be fixed in 1.9.4
