### ISSUE TITLE
Unhandled exception occured in onPacketReceiving(PacketEvent)

### ISSUE THREAD

**Issue by andrewkm** [Photon-GitHub/AACAdditionPro#86]
### Issue description

Continuous console spam with the following error:
https://gist.githubusercontent.com/andrewkm/f36cde34d0ca3b8d77447b89429a440b/raw/81e0eaba792e662c327dbfeff99c2d728eedcfd5/gistfile1.txt

### Core information
**Server version**: 1.11.2 - Spigot Build 1251

**AAC version**: 3.1.6-b5

**AACAddition Pro version**: 1.9.3

**ProtocolLib version**: 4.2.1 Build 354

**Plugin list**: (on request via Discord - andrewkm-1759)

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by Photon-GitHub** [comment]
Should be fixed in 1.9.4
