### ISSUE TITLE
Fishing kicks for legitimate fishing.

### ISSUE THREAD

**Issue by andrewkm** [Photon-GitHub/AACAdditionPro#88]
### Issue description

"On more than one occasion, fishing under normal circumstances has triggered the server anti-cheat to wrongly execute a kick. I believe this is a bug and not normal behavior due to the ease in reproducing an anti-cheat trigger."

Full report in following thread: https://www.ecocitycraft.com/forum/threads/fishing-and-anti-cheat-bug.166217/

Unsure if this bug is related to AACAddition Pro or to the config I am using.

### Core information
**Server version**: 1.11.2 - Spigot Build 1251

**AAC version**: 3.1.6-b5
**AAC config**: Default by Celebrimbor. (Cannot post as private)

**AACAddition Pro version**: 1.9.3
**AACAddition Pro config**: Default by Celebrimbor. (Cannot post as private)

**ProtocolLib version**: 4.2.1 Build 354

**Plugin list**: (on request via Discord - andrewkm-1759)

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by Photon-GitHub** [comment]
This is basically trying to get detected, as Autofish measures the time after a bite to detect suspicious behavior. If you want to disable that part of AutoFish I can include a config option in the next release.

**Comment by andrewkm** [comment]
Thing is many players literally fish like this. We've had enormous amounts of issues with the fishing check. A disable for this would be very helpful indeed.
