### ISSUE TITLE
Constant full server crashses. java.util.NoSuchElementException. "Exception ticking world entities"

### ISSUE THREAD

**Issue by andrewkm** [Photon-GitHub/AACAdditionPro#89]
### Issue description

Continuous server crashes with the following error:
https://gist.github.com/andrewkm/b4ed1b61741222dd621d5aa90846886a
&
https://gist.githubusercontent.com/andrewkm/df3a5ee5e58bac774d546cc6eb13ccae/raw/43bd1c7b4548163b49871247d879d135de4c016f/gistfile1.txt

Id like to reference this issue: https://github.com/konsolas/AAC-Issues/issues/551 as well as this most recent one: https://github.com/konsolas/AAC-Issues/issues/681

I have determined with certainty that the issue stems directly from AAC Addition Pro. The plugin is sadly no longer usable by me. I would love to however revisit it's usage in the future and will glady assist you should you find a possible fix. (Will load it on our production servers/networks and monitor for crashes)

### Core information
**Server version**: 1.11.2 - Spigot Build 1251

**AAC version**: 3.1.6-b5
**AAC config**: Default by Celebrimbor. (Cannot post as private)

**AACAddition Pro version**: 1.9.3
**AACAddition Pro config**: Default by Celebrimbor. (Cannot post as private)

**ProtocolLib version**: 4.2.1 Build 354

**Plugin list**: (on request via Discord - andrewkm-1759)

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by Photon-GitHub** [comment]
I cannot see what is causing this as the stacktrace gives no hint whatsoever...

**Comment by andrewkm** [comment]
Running YourKit as the server crashes would show you the cause very effectively. Unfortunately I cannot do this on my production environment.

**Comment by Photon-GitHub** [comment]
Any idea how to reproduce ?

**Comment by andrewkm** [comment]
Honestly I wouldn't know where to begin. It would happen around the 6-12 hour mark ALWAYS on our production server with 60-100 players. Removing it and we've been good with zero crashes for about a week now. Sadly during my vacation I cannot risk testing on our production boxes. However when I'm back home, I'll see what I can do during off-peak hours. When i'm home from Vegas I can perhaps go over my AAC Addition logs and check what happened during the exact time of the crashes (as in the violations).. Perhaps we'll catch a pattern or something that will help us get down to the issue.

**Comment by Photon-GitHub** [comment]
Should be fixed in 2.0.0

**Comment by andrewkm** [comment]
What was the issue?

**Comment by Janmm14** [comment]
@andrewkm asynchronous usage of bukkit api
