### ISSUE TITLE
ChestESP and Tracers block. Feature request.

### ISSUE THREAD

**Issue by JuliCarles** [Photon-GitHub/AACAdditionPro#9]
The title says it itself, just to ask for ChestESP and Tracers blockage.

**Comment by Photon-GitHub** [comment]
For ChestEsp please use Orebfuscator. I may block tracers at some time, but it is hard to do, especially when thinking of third-person mode...

**Comment by Janmm14** [comment]
Hiding sneaking people behind walls would be possible

Orebfuscator does not block chestesp really, eapecially in minigames where the chests have air blocks near them.

**Comment by Photon-GitHub** [comment]
Ok, the long explanation:
A ridiculous amount of trigonometry and hitbox calculation would be needed to do that.. Also I have the problem of nametags, as those are rendered completely different than the player. Moreover calculating this completely accurate for every player would probably make a huge cpu load. Hiding sneaking players is also difficult as of the third-person camera.

**Comment by Photon-GitHub** [comment]
I decided that I will try to implement a tracer-blocker with invisible fake-players around a player, which can be done clientsided (no server-lag) and is somewhat effective.

This is nonetheless last priority as it is a big project, so don't expect it anytime soon.

**Comment by JuliCarles** [comment]
Great dessicion, I think it's great as this hack is definitely used a lot. Thanks.

**Comment by Photon-GitHub** [comment]
Chest ESP will never be blocked, use Orebfuscator for this. ESP is mostly implemented and version 1.2.1 will have huge improvements to the check.

**Comment by Photon-GitHub** [comment]
1.2.1 is now released.
