### ISSUE TITLE
Stack Trace

### ISSUE THREAD

**Issue by SnakeDaoust1232** [Photon-GitHub/AACAdditionPro#90]
https://gyazo.com/18e8b23ba68953b31b472ac82d65d53c

**Comment by Photon-GitHub** [comment]
As it is just a non-harmful error on disable I will mark it as unimportant.

**Comment by SnakeDaoust1232** [comment]
https://gyazo.com/ab0bb3877196c63e027a7fc56ccb0981

**Comment by SnakeDaoust1232** [comment]
Not fixed. https://gyazo.com/f3bd414c3c6a489b224b6d8ae2d0e979 :(

**Comment by SnakeDaoust1232** [comment]
Not fixed: https://gyazo.com/c1fe147e6752b81f7383769062d841dd

**Comment by Janmm14** [comment]
Fixed in code.

**Comment by Photon-GitHub** [comment]
Fixed in 3.0.0
