### ISSUE TITLE
Heuristic Addon- Broken

### ISSUE THREAD

**Issue by SnakeDaoust1232** [Photon-GitHub/AACAdditionPro#91]
Error in console: https://gyazo.com/94452e315b0bd2af39226da45cc312c9

AAC Config: https://hastebin.com/uholuvosup.bash
AAcAdditionPro Config: https://hastebin.com/ewewacenim.scala

**Comment by Photon-GitHub** [comment]
Known problem.

**Comment by CeIebrimbor** [comment]
1.9.3 @SnakeDaoust1232 
1.9.3 = 1.9.4 w/o the AutoFish upgrades

**Comment by Photon-GitHub** [comment]
Should be fixed in 2.0.0
