### ISSUE TITLE
Inventory Rotation FP

### ISSUE THREAD

**Issue by Hyronymos** [Photon-GitHub/AACAdditionPro#93]
Server-log: https://hastebin.com/gikoforuni.md

AAC: latest
PROTOCOLLIB: 4.2.0
AACADDTIONPRO: latest
ViaVersion: yes sir!

Video (last 6 sec): https://www.youtube.com/watch?v=Rmb5jOIQ9uY&feature=youtu.be

Full Video: https://www.youtube.com/watch?v=bfUcUqO5lkY&feature=youtu.be

**Comment by Photon-GitHub** [comment]
Can you please fix your bedwars plugin?
It is hard to read the logs...

**Comment by Photon-GitHub** [comment]
This should be fixed, can you confirm @Hyronymos ?

**Comment by Hyronymos** [comment]
yeah, its fixed
