### ISSUE TITLE
AACAdditionPro does not start

### ISSUE THREAD

**Issue by Hyronymos** [Photon-GitHub/AACAdditionPro#95]
Log: https://hastebin.com/udukerukoh.md
Server-Version: 1.8.8 PaperSpigot
ViaVersion: Yes sir!

AAC-Version: latest
AACAdditionPro-Version: latest

**Comment by CeIebrimbor** [comment]
Did you modify the config? There seems to be an error in the autopotion check.

**Comment by Photon-GitHub** [comment]
"Config-Section is null when loading: AutoPotion.thresholds"
You have messed up your configuration.
