### ISSUE TITLE
KillAura Entity

### ISSUE THREAD

**Issue by OWERLORD01** [Photon-GitHub/AACAdditionPro#96]
KillAura entity is not showing on TacoSpigot #101 for 1.11...
Is it working only on 1.8? I'm using the latest protocollib build for 1.11.

**Comment by Photon-GitHub** [comment]
There is a reason why it is labeled "highly experimental".

**Comment by CeIebrimbor** [comment]
Do you not plan on improving the feature? If you didn't want feedback, you should not have added the option to use it. I figured user feedback would be helpful, not discouraged.

**Comment by OWERLORD01** [comment]
> Do you not plan on improving the feature? If you didn't want feedback, you should not have added the option to use it. I figured user feedback would be helpful, not discouraged.

He really want me to change my review :)
