### ISSUE TITLE
Unhandled exception occured in onPacketReceiving(PacketEvent)

### ISSUE THREAD

**Issue by MurryPuppins** [Photon-GitHub/AACAdditionPro#99]
Hello, 
   I contacted Cel about this issue, and he said to report it here as you were having a difficult time trying to reproduce. I have a good bit of data on it, so hopefully that helps? I will delete AAC+ and reinstall it and see if the problem persists.

I'm using the latest versions of AAC and AAC+, and their latest configs
Pastebin- https://pastebin.com/WgQPVT1A
Plugin List- https://gyazo.com/5de52a03c65133ed72a5c6fd03e9a443

I hope you are able to assist and resolve! Best of luck

**Comment by CeIebrimbor** [comment]
Error reportedly stopped after downgrade to 2.0.2

**Comment by MurryPuppins** [comment]
Error still continues in 2.0.2

**Comment by maxlehot1234** [comment]
Same for me. Server in 1.12

**Comment by Summerfeeling** [comment]
Still present on 2.0.3 MC 1.8.8: https://paste.lpmitkev.de/rich/74f9ccfe

**Comment by Photon-GitHub** [comment]
Fixed in 3.0.0
